import { DAILY_QUESTION_IMAGES as IMG } from './dailyQuestionsImages';
import type { DailyQuestionCategory } from './dailyQuestionsTypes';

export const EXTRA_DAILY_QUESTION_CATEGORIES: DailyQuestionCategory[] = [
  {
    id: 'childhood_memories',
    emoji: '🧸',
    title: 'Детские воспоминания',
    questions: [
      { id: 'ch1', type: 'text', text: 'Какое детское воспоминание ты бы хотел(а) пережить вместе со мной?' },
      { id: 'ch2', type: 'choice', text: 'Что из детства ты сохранил(а) в себе до сих пор?', options: [{ id: 'playful', label: 'Игривость и смех' }, { id: 'curious', label: 'Любопытство к миру' }, { id: 'sensitive', label: 'Чувствительность и мечтательность' }] },
      { id: 'ch3', type: 'text', text: 'Какая семейная традиция из детства могла бы стать нашей?' },
      { id: 'ch4', type: 'choice', text: 'Если бы мы встретились в детстве, чем бы занялись?', options: [{ id: 'playground', label: 'Играли бы на площадке' }, { id: 'adventure', label: 'Устроили бы приключение' }, { id: 'secret', label: 'Придумали бы тайный клуб' }] },
    ],
  },
  {
    id: 'family_traditions',
    emoji: '👨‍👩‍👧',
    title: 'Семейные традиции',
    questions: [
      { id: 'fa1', type: 'choice', text: 'Как ты относишься к семейным праздникам?', options: [{ id: 'love', label: 'Обожаю — это связь поколений' }, { id: 'selective', label: 'Выбираю самые близкие' }, { id: 'create', label: 'Хочу создавать свои' }] },
      { id: 'fa2', type: 'text', text: 'Какую традицию из своей семьи ты хотел(а) бы передать нашим детям?' },
      { id: 'fa3', type: 'choice', text: 'Как часто ты хочешь видеть родственников?', options: [{ id: 'often', label: 'Часто — семья рядом' }, { id: 'holidays', label: 'На праздниках достаточно' }, { id: 'balance', label: 'Баланс — и своё пространство' }] },
      { id: 'fa4', type: 'text', text: 'Какой семейный рецепт или ритуал ты хочешь сохранить?' },
    ],
  },
  {
    id: 'trust_foundations',
    emoji: '🤝',
    title: 'Фундамент доверия',
    questions: [
      { id: 'tr1', type: 'text', text: 'Когда ты впервые понял(а), что можешь мне доверять?' },
      { id: 'tr2', type: 'choice', text: 'Что для тебя важнее всего в доверии?', options: [{ id: 'honesty', label: 'Честность, даже когда больно' }, { id: 'reliability', label: 'Надёжность и слова на деле' }, { id: 'transparency', label: 'Открытость без секретов' }] },
      { id: 'tr3', type: 'text', text: 'Был ли момент, когда доверие между нами стало крепче?' },
      { id: 'tr4', type: 'choice', text: 'Как восстановить доверие, если оно пошатнулось?', options: [{ id: 'talk', label: 'Долгий честный разговор' }, { id: 'time', label: 'Время и последовательность' }, { id: 'actions', label: 'Дела, а не только слова' }] },
    ],
  },
  {
    id: 'conflict_style',
    emoji: '⚡',
    title: 'Стиль конфликтов',
    questions: [
      { id: 'co1', type: 'choice', text: 'Когда мы ссоримся, ты обычно...', options: [{ id: 'withdraw', label: 'Замыкаешься и молчишь' }, { id: 'express', label: 'Выражаешь эмоции сразу' }, { id: 'analyze', label: 'Пытаешься разобраться логически' }] },
      { id: 'co2', type: 'text', text: 'О чём нам сложнее всего спорить, но важно обсудить?' },
      { id: 'co3', type: 'choice', text: 'Что помогает тебе не наговорить лишнего в ссоре?', options: [{ id: 'pause', label: 'Пауза и выход из комнаты' }, { id: 'breathe', label: 'Глубокое дыхание' }, { id: 'remind', label: 'Напомнить себе, что мы — команда' }] },
      { id: 'co4', type: 'text', text: 'Какой урок из прошлых конфликтов помог бы нам сейчас?' },
    ],
  },
  {
    id: 'saying_sorry',
    emoji: '🕊️',
    title: 'Искренние извинения',
    questions: [
      { id: 'so1', type: 'choice', text: 'Как ты обычно извиняешься?', options: [{ id: 'words', label: 'Словами — «прости»' }, { id: 'actions', label: 'Делами и заботой' }, { id: 'time', label: 'Нужно время, потом говорю' }] },
      { id: 'so2', type: 'text', text: 'Какое извинение от меня тебе запомнилось больше всего?' },
      { id: 'so3', type: 'choice', text: 'Что делает извинение настоящим для тебя?', options: [{ id: 'acknowledge', label: 'Признание своей ошибки' }, { id: 'change', label: 'Попытка измениться' }, { id: 'patience', label: 'Терпение с моими чувствами' }] },
      { id: 'so4', type: 'text', text: 'За что ты хотел(а) бы извиниться передо мной прямо сейчас?' },
    ],
  },
  {
    id: 'jealousy_talk',
    emoji: '💚',
    title: 'Ревность и честность',
    questions: [
      { id: 'je1', type: 'choice', text: 'Как ты относишься к лёгкой ревности?', options: [{ id: 'normal', label: 'Это нормально — значит, не всё равно' }, { id: 'uncomfortable', label: 'Некомфортно, но бывает' }, { id: 'avoid', label: 'Стараюсь не ревновать' }] },
      { id: 'je2', type: 'text', text: 'Что помогает тебе чувствовать себя уверенно в отношениях?' },
      { id: 'je3', type: 'choice', text: 'Как лучше говорить о ревности?', options: [{ id: 'direct', label: 'Прямо и без обвинений' }, { id: 'humor', label: 'С юмором и лёгкостью' }, { id: 'later', label: 'Когда эмоции улеглись' }] },
      { id: 'je4', type: 'text', text: 'Был ли момент, когда ревность научила нас чему-то важному?' },
    ],
  },
  {
    id: 'personal_space',
    emoji: '🚪',
    title: 'Личное пространство',
    questions: [
      { id: 'ps1', type: 'choice', text: 'Сколько времени наедине с собой тебе нужно в неделю?', options: [{ id: 'daily', label: 'Хотя бы час каждый день' }, { id: 'few', label: 'Несколько раз в неделю' }, { id: 'little', label: 'Мало — я энергичнее рядом с тобой' }] },
      { id: 'ps2', type: 'text', text: 'Чем ты занимаешься, когда хочешь побыть одному(одной)?' },
      { id: 'ps3', type: 'choice', text: 'Как ты реагируешь, когда я прошу побыть одному?', options: [{ id: 'support', label: 'Поддерживаю без обид' }, { id: 'worry', label: 'Немного переживаю' }, { id: 'use', label: 'Использую время для себя тоже' }] },
      { id: 'ps4', type: 'text', text: 'Как нам найти баланс между «вместе» и «отдельно»?' },
    ],
  },
  {
    id: 'couple_rituals',
    emoji: '🕯️',
    title: 'Ритуалы пары',
    questions: [
      { id: 'cr1', type: 'text', text: 'Какой наш ритуал ты ценишь больше всего?' },
      { id: 'cr2', type: 'choice', text: 'Какой новый ритуал ты хотел(а) бы завести?', options: [{ id: 'weekly', label: 'Еженедельное свидание' }, { id: 'morning', label: 'Утренний ритуал' }, { id: 'goodnight', label: 'Вечернее «спокойной ночи»' }] },
      { id: 'cr3', type: 'text', text: 'Есть ли ритуал, который мы потеряли и стоит вернуть?' },
      { id: 'cr4', type: 'choice', text: 'Ритуалы для тебя — это...', options: [{ id: 'anchor', label: 'Якорь стабильности' }, { id: 'romance', label: 'Способ сохранить романтику' }, { id: 'fun', label: 'Повод для радости' }] },
    ],
  },
  {
    id: 'date_night_ideas',
    emoji: '🌹',
    title: 'Идеи для свиданий',
    questions: [
      { id: 'dn1', type: 'image', text: 'Какое свидание тебе ближе?', images: [{ id: 'restaurant_candle', label: 'Романтический ресторан', url: IMG.restaurant_candle }, { id: 'picnic_park', label: 'Пикник в парке', url: IMG.picnic_park }] },
      { id: 'dn2', type: 'choice', text: 'Как часто тебе нужны «настоящие» свидания?', options: [{ id: 'weekly', label: 'Раз в неделю' }, { id: 'biweekly', label: 'Раз в две недели' }, { id: 'monthly', label: 'Раз в месяц — но особенные' }] },
      { id: 'dn3', type: 'text', text: 'Какое свидание из наших ты бы повторил(а)?' },
      { id: 'dn4', type: 'choice', text: 'Идеальное свидание без телефонов — это...', options: [{ id: 'walk', label: 'Долгая прогулка' }, { id: 'cook', label: 'Готовка вместе' }, { id: 'surprise', label: 'Сюрприз от партнёра' }] },
    ],
  },
  {
    id: 'weekend_vibes',
    emoji: '🛋️',
    title: 'Выходные вдвоём',
    questions: [
      { id: 'wv1', type: 'choice', text: 'Идеальные выходные для тебя — это...', options: [{ id: 'active', label: 'Активность и приключения' }, { id: 'lazy', label: 'Лень и сериалы' }, { id: 'mix', label: 'Микс отдыха и дел' }] },
      { id: 'wv2', type: 'text', text: 'Какой последний выходной с тобой запомнился особенно?' },
      { id: 'wv3', type: 'choice', text: 'Как ты относишься к планам на выходные?', options: [{ id: 'plan', label: 'Люблю заранее планировать' }, { id: 'spontaneous', label: 'Спонтанно — как пойдёт' }, { id: 'flexible', label: 'Один день по плану, один — нет' }] },
      { id: 'wv4', type: 'text', text: 'Что бы ты хотел(а) сделать в ближайшие выходные?' },
    ],
  },
  {
    id: 'home_chores',
    emoji: '🧹',
    title: 'Домашние дела',
    questions: [
      { id: 'hc1', type: 'choice', text: 'Какое домашнее дело тебе нравится больше всего?', options: [{ id: 'cooking', label: 'Готовка' }, { id: 'cleaning', label: 'Уборка — терапия' }, { id: 'none', label: 'Ни одно 😅' }] },
      { id: 'hc2', type: 'text', text: 'Как мы можем честнее делить обязанности дома?' },
      { id: 'hc3', type: 'choice', text: 'Когда партнёр делает дела без напоминания, ты...', options: [{ id: 'grateful', label: 'Безмерно благодарен(на)' }, { id: 'noticed', label: 'Замечаю и ценю' }, { id: 'expected', label: 'Это норма в паре' }] },
      { id: 'hc4', type: 'text', text: 'Какой бытовой лайфхак ты хочешь внедрить вместе?' },
    ],
  },
  {
    id: 'cooking_bond',
    emoji: '👨‍🍳',
    title: 'Готовим вместе',
    questions: [
      { id: 'cb1', type: 'text', text: 'Какое блюдо мы готовили вместе лучше всего?' },
      { id: 'cb2', type: 'choice', text: 'Твоя роль на кухне в паре — это...', options: [{ id: 'chef', label: 'Шеф-повар' }, { id: 'sous', label: 'Помощник' }, { id: 'taster', label: 'Дегустатор и моральная поддержка' }] },
      { id: 'cb3', type: 'text', text: 'Какое блюдо ты хочешь научиться готовить со мной?' },
      { id: 'cb4', type: 'choice', text: 'Музыка на кухне — это...', options: [{ id: 'must', label: 'Обязательно!' }, { id: 'sometimes', label: 'Иногда для настроения' }, { id: 'quiet', label: 'Лучше тишина и болтовня' }] },
    ],
  },
  {
    id: 'money_matters',
    emoji: '💰',
    title: 'Разговор о деньгах',
    questions: [
      { id: 'mo1', type: 'choice', text: 'Как ты относишься к совместным тратам?', options: [{ id: 'equal', label: 'Поровну — всё честно' }, { id: 'flexible', label: 'Гибко — кто сколько может' }, { id: 'separate', label: 'Часть отдельно, часть вместе' }] },
      { id: 'mo2', type: 'text', text: 'О каких финансовых целях ты мечтаешь вместе со мной?' },
      { id: 'mo3', type: 'choice', text: 'Разговоры о деньгах для тебя...', options: [{ id: 'easy', label: 'Легко и открыто' }, { id: 'hard', label: 'Сложно, но важно' }, { id: 'avoid', label: 'Стараюсь избегать' }] },
      { id: 'mo4', type: 'text', text: 'Какая покупка «для нас» принесла бы больше всего радости?' },
    ],
  },
  {
    id: 'shared_savings',
    emoji: '🏦',
    title: 'Общие накопления',
    questions: [
      { id: 'sa1', type: 'text', text: 'На что ты хотел(а) бы копить вместе в первую очередь?' },
      { id: 'sa2', type: 'choice', text: 'Стиль накоплений — какой твой?', options: [{ id: 'steady', label: 'Регулярно понемногу' }, { id: 'goal', label: 'На конкретную цель' }, { id: 'spontaneous', label: 'Когда получается' }] },
      { id: 'sa3', type: 'text', text: 'Какая финансовая привычка из детства повлияла на тебя?' },
      { id: 'sa4', type: 'choice', text: 'Если бы у нас появилась «копилка мечты», что в ней было бы?', options: [{ id: 'travel', label: 'Путешествие' }, { id: 'home', label: 'Дом или ремонт' }, { id: 'experience', label: 'Незабываемый опыт' }] },
    ],
  },
  {
    id: 'career_cheers',
    emoji: '🎯',
    title: 'Поддержка в карьере',
    questions: [
      { id: 'cc1', type: 'text', text: 'Как я могу лучше поддерживать тебя в работе?' },
      { id: 'cc2', type: 'choice', text: 'Когда у тебя тяжёлый день на работе, тебе нужно...', options: [{ id: 'listen', label: 'Чтобы выслушали' }, { id: 'distraction', label: 'Отвлечься и переключиться' }, { id: 'advice', label: 'Совет или помощь' }] },
      { id: 'cc3', type: 'text', text: 'Какой твой профессиональный успех ты хочешь отпраздновать со мной?' },
      { id: 'cc4', type: 'choice', text: 'Карьера vs отношения — как ты видишь баланс?', options: [{ id: 'both', label: 'Оба важны — ищу баланс' }, { id: 'career', label: 'Сейчас карьера в приоритете' }, { id: 'us', label: 'Мы важнее любой работы' }] },
    ],
  },
  {
    id: 'work_balance',
    emoji: '⚖️',
    title: 'Баланс работы и любви',
    questions: [
      { id: 'wb1', type: 'choice', text: 'Когда ты «приносишь работу домой», это...', options: [{ id: 'stress', label: 'Стресс, о котором хочу рассказать' }, { id: 'silence', label: 'Молчание — не хочу грузить' }, { id: 'rare', label: 'Редко — умею отключаться' }] },
      { id: 'wb2', type: 'text', text: 'Как мы можем защитить наше время от рабочих звонков?' },
      { id: 'wb3', type: 'choice', text: 'Идеальный вечер после рабочего дня — это...', options: [{ id: 'talk', label: 'Рассказать друг другу о дне' }, { id: 'relax', label: 'Молча отдохнуть рядом' }, { id: 'activity', label: 'Что-то активное' }] },
      { id: 'wb4', type: 'text', text: 'Что помогает тебе переключиться с «рабочего режима» на «домашний»?' },
    ],
  },
  {
    id: 'big_dreams',
    emoji: '🌟',
    title: 'Большие мечты',
    questions: [
      { id: 'bd1', type: 'text', text: 'Какая мечта кажется безумной, но ты всё равно о ней думаешь?' },
      { id: 'bd2', type: 'choice', text: 'Мечты для тебя — это...', options: [{ id: 'fuel', label: 'Топливо для жизни' }, { id: 'guide', label: 'Компас к целям' }, { id: 'fun', label: 'Просто приятно фантазировать' }] },
      { id: 'bd3', type: 'text', text: 'Какую мечту ты хочешь, чтобы мы осуществили в ближайшие 3 года?' },
      { id: 'bd4', type: 'choice', text: 'Если бы деньги не были проблемой, что бы мы сделали завтра?', options: [{ id: 'travel', label: 'Отправились в кругосветку' }, { id: 'home', label: 'Построили дом мечты' }, { id: 'help', label: 'Помогли близким и проектам' }] },
    ],
  },
  {
    id: 'hobbies_share',
    emoji: '🎨',
    title: 'Хобби и увлечения',
    questions: [
      { id: 'ho1', type: 'choice', text: 'Хочешь ли ты, чтобы я разделял(а) твоё хобби?', options: [{ id: 'yes', label: 'Да — это сближает' }, { id: 'partly', label: 'Иногда — но и своё нужно' }, { id: 'no', label: 'Нет — пусть будет моим' }] },
      { id: 'ho2', type: 'text', text: 'Какое моё увлечение тебя удивило или восхитило?' },
      { id: 'ho3', type: 'choice', text: 'Совместное хобби — это...', options: [{ id: 'dream', label: 'Мечта — найти своё' }, { id: 'have', label: 'У нас уже есть!' }, { id: 'optional', label: 'Не обязательно' }] },
      { id: 'ho4', type: 'text', text: 'Какое новое увлечение ты хотел(а) бы попробовать вместе?' },
    ],
  },
  {
    id: 'learn_together',
    emoji: '📚',
    title: 'Учимся вместе',
    questions: [
      { id: 'lt1', type: 'text', text: 'Чему бы ты хотел(а) научиться вместе со мной?' },
      { id: 'lt2', type: 'choice', text: 'Когда я учусь чему-то новому, ты...', options: [{ id: 'support', label: 'Поддерживаешь и интересуешься' }, { id: 'join', label: 'Присоединяешься' }, { id: 'space', label: 'Даёшь пространство' }] },
      { id: 'lt3', type: 'text', text: 'Был ли момент, когда мы чему-то научили друг друга?' },
      { id: 'lt4', type: 'choice', text: 'Идеальный «учебный» вечер вдвоём — это...', options: [{ id: 'language', label: 'Изучение языка' }, { id: 'skill', label: 'Новый навык — танцы, рисование' }, { id: 'documentary', label: 'Документалка и обсуждение' }] },
    ],
  },
  {
    id: 'reading_pair',
    emoji: '📖',
    title: 'Читаем вместе',
    questions: [
      { id: 'rd1', type: 'choice', text: 'Читать одну книгу вдвоём — это...', options: [{ id: 'romantic', label: 'Романтично и уютно' }, { id: 'fun', label: 'Весело — обсуждать главы' }, { id: 'hard', label: 'Сложно — разные темпы' }] },
      { id: 'rd2', type: 'text', text: 'Какая книга могла бы стать «нашей»?' },
      { id: 'rd3', type: 'text', text: 'Расскажи о книге или истории, которая тебя тронула недавно' },
      { id: 'rd4', type: 'choice', text: 'Перед сном ты предпочитаешь...', options: [{ id: 'read', label: 'Читать' }, { id: 'talk', label: 'Разговаривать' }, { id: 'screen', label: 'Сериал или телефон' }] },
    ],
  },
  {
    id: 'gaming_us',
    emoji: '🎮',
    title: 'Играем вместе',
    questions: [
      { id: 'gu1', type: 'choice', text: 'Совместные игры — это...', options: [{ id: 'love', label: 'Наш способ повеселиться' }, { id: 'sometimes', label: 'Иногда — зависит от игры' }, { id: 'competitive', label: 'Соревнование — я хочу выиграть!' }] },
      { id: 'gu2', type: 'text', text: 'Какая игра или настолка лучше всего показывает наш характер?' },
      { id: 'gu3', type: 'choice', text: 'Когда я выигрываю, ты...', options: [{ id: 'happy', label: 'Рад(а) за меня' }, { id: 'rematch', label: 'Хочешь реванш' }, { id: 'sore', label: 'Немного обидно 😄' }] },
      { id: 'gu4', type: 'text', text: 'В какую игру ты хотел(а) бы сыграть со мной впервые?' },
    ],
  },
  {
    id: 'creative_us',
    emoji: '✏️',
    title: 'Творим вместе',
    questions: [
      { id: 'cu1', type: 'text', text: 'Какой совместный творческий проект ты представляешь?' },
      { id: 'cu2', type: 'choice', text: 'Творчество в паре — это...', options: [{ id: 'bond', label: 'Способ сблизиться' }, { id: 'separate', label: 'Каждый своё, но рядом' }, { id: 'new', label: 'Хочу попробовать' }] },
      { id: 'cu3', type: 'text', text: 'Что бы мы создали, если бы у нас был один свободный день?' },
      { id: 'cu4', type: 'choice', text: 'Когда я творю, ты...', options: [{ id: 'watch', label: 'Любишь наблюдать' }, { id: 'join', label: 'Присоединяешься' }, { id: 'inspire', label: 'Вдохновляешь идеями' }] },
    ],
  },
  {
    id: 'art_dates',
    emoji: '🖼️',
    title: 'Свидания с искусством',
    questions: [
      { id: 'ar1', type: 'image', text: 'Куда пойти на свидание?', images: [{ id: 'art_studio', label: 'Творческая мастерская', url: IMG.art_studio }, { id: 'museum_art', label: 'Музей искусств', url: IMG.museum_art }] },
      { id: 'ar2', type: 'text', text: 'Какое произведение искусства ты хотел(а) бы увидеть вместе?' },
      { id: 'ar3', type: 'choice', text: 'Рисовать или лепить вместе — это...', options: [{ id: 'fun', label: 'Весело, даже если криво' }, { id: 'romantic', label: 'Романтично' }, { id: 'stress', label: 'Стресс — я не умею' }] },
      { id: 'ar4', type: 'text', text: 'Как искусство может стать частью нашей жизни?' },
    ],
  },
  {
    id: 'fitness_pair',
    emoji: '💪',
    title: 'Спорт вдвоём',
    questions: [
      { id: 'fp1', type: 'image', text: 'Какой формат активности ближе?', images: [{ id: 'gym_couple', label: 'Тренировка в зале', url: IMG.gym_couple }, { id: 'yoga_calm', label: 'Йога и спокойствие', url: IMG.yoga_calm }] },
      { id: 'fp2', type: 'choice', text: 'Тренироваться вместе — это...', options: [{ id: 'motivate', label: 'Мотивация не сдаваться' }, { id: 'fun', label: 'Ещё один способ провести время' }, { id: 'solo', label: 'Лучше каждому своё' }] },
      { id: 'fp3', type: 'text', text: 'Какой спортивный вызов ты хотел(а) бы принять вместе?' },
      { id: 'fp4', type: 'choice', text: 'После совместной тренировки ты...', options: [{ id: 'proud', label: 'Горд(а) друг другом' }, { id: 'tired', label: 'Падаем на диван' }, { id: 'food', label: 'Идём есть!' }] },
    ],
  },
  {
    id: 'wellness_us',
    emoji: '🧘',
    title: 'Забота о себе',
    questions: [
      { id: 'we1', type: 'choice', text: 'Как ты заботишься о себе в стрессовые периоды?', options: [{ id: 'rest', label: 'Отдых и сон' }, { id: 'move', label: 'Движение и спорт' }, { id: 'talk', label: 'Разговор с близкими' }] },
      { id: 'we2', type: 'text', text: 'Как я могу помочь тебе заботиться о себе?' },
      { id: 'we3', type: 'choice', text: 'Совместные практики заботы — это...', options: [{ id: 'want', label: 'Хочу попробовать — медитация, прогулки' }, { id: 'have', label: 'У нас уже есть' }, { id: 'personal', label: 'Это личное' }] },
      { id: 'we4', type: 'text', text: 'Какой ритуал заботы о себе ты хотел(а) бы добавить в нашу жизнь?' },
    ],
  },
  {
    id: 'mental_health',
    emoji: '🧠',
    title: 'Ментальное здоровье',
    questions: [
      { id: 'mh1', type: 'text', text: 'Когда тебе тяжело эмоционально, что помогает больше всего?' },
      { id: 'mh2', type: 'choice', text: 'Говорить о ментальном здоровье в паре — это...', options: [{ id: 'important', label: 'Очень важно' }, { id: 'learning', label: 'Учимся постепенно' }, { id: 'hard', label: 'Сложно, но пробуем' }] },
      { id: 'mh3', type: 'text', text: 'Какой знак от тебя говорит мне «мне нужна поддержка»?' },
      { id: 'mh4', type: 'choice', text: 'Когда я грущу, ты обычно...', options: [{ id: 'hold', label: 'Обнимаешь и молчишь' }, { id: 'talk', label: 'Спрашиваешь и слушаешь' }, { id: 'cheer', label: 'Пытаешься развеселить' }] },
    ],
  },
  {
    id: 'stress_support',
    emoji: '🫂',
    title: 'Поддержка в стрессе',
    questions: [
      { id: 'st1', type: 'choice', text: 'Твой главный источник стресса сейчас — это...', options: [{ id: 'work', label: 'Работа' }, { id: 'life', label: 'Жизненные обстоятельства' }, { id: 'relations', label: 'Отношения или семья' }] },
      { id: 'st2', type: 'text', text: 'Что я могу сделать сегодня, чтобы облегчить твой день?' },
      { id: 'st3', type: 'choice', text: 'Когда ты в стрессе, тебе лучше...', options: [{ id: 'alone', label: 'Побыть одному(одной)' }, { id: 'together', label: 'Быть рядом, даже молча' }, { id: 'distraction', label: 'Отвлечься — фильм, прогулка' }] },
      { id: 'st4', type: 'text', text: 'Какой момент показал, что мы справляемся со стрессом лучше вместе?' },
    ],
  },
  {
    id: 'pet_lovers',
    emoji: '🐾',
    title: 'Любовь к питомцам',
    questions: [
      { id: 'pl1', type: 'image', text: 'Какой питомец ближе к твоей душе?', images: [{ id: 'puppy_cuddle', label: 'Собака — верный друг', url: IMG.puppy_cuddle }, { id: 'cat_lap', label: 'Кошка — уют на коленях', url: IMG.cat_lap }] },
      { id: 'pl2', type: 'text', text: 'Какое животное ты хотел(а) бы завести вместе?' },
      { id: 'pl3', type: 'choice', text: 'Питомец в нашей паре — это...', options: [{ id: 'dream', label: 'Мечта!' }, { id: 'maybe', label: 'Может быть, когда-нибудь' }, { id: 'no', label: 'Не для нас' }] },
      { id: 'pl4', type: 'text', text: 'Как бы мы назвали нашего воображаемого питомца?' },
    ],
  },
  {
    id: 'future_pets',
    emoji: '🐕',
    title: 'Питомцы будущего',
    questions: [
      { id: 'fpt1', type: 'choice', text: 'Когда заводить питомца — лучше...', options: [{ id: 'now', label: 'Сейчас — почему ждать?' }, { id: 'stable', label: 'Когда стабилизируем быт' }, { id: 'never', label: 'Не планируем' }] },
      { id: 'fpt2', type: 'text', text: 'Какие обязанности по уходу за питомцем ты готов(а) взять?' },
      { id: 'fpt3', type: 'choice', text: 'Собака или кошка — или что-то другое?', options: [{ id: 'dog', label: 'Собака' }, { id: 'cat', label: 'Кошка' }, { id: 'exotic', label: 'Что-то необычное — попугай, кролик' }] },
      { id: 'fpt4', type: 'text', text: 'Как питомец изменил бы нашу повседневную жизнь?' },
    ],
  },
  {
    id: 'travel_ways',
    emoji: '✈️',
    title: 'Как мы путешествуем',
    questions: [
      { id: 'tw1', type: 'image', text: 'Какой транспорт для путешествия мечты?', images: [{ id: 'airplane_window', label: 'Самолёт — далеко и быстро', url: IMG.airplane_window }, { id: 'train_travel', label: 'Поезд — медленно и романтично', url: IMG.train_travel }] },
      { id: 'tw2', type: 'choice', text: 'В путешествии ты — это...', options: [{ id: 'planner', label: 'Планировщик маршрута' }, { id: 'explorer', label: 'Исследователь без карты' }, { id: 'follower', label: 'Следую за партнёром' }] },
      { id: 'tw3', type: 'text', text: 'Какое наше путешествие ты бы назвал(а) идеальным?' },
      { id: 'tw4', type: 'choice', text: 'Сувенир из поездки — это...', options: [{ id: 'thing', label: 'Предмет на память' }, { id: 'photo', label: 'Фото и впечатления' }, { id: 'tradition', label: 'Новая традиция' }] },
    ],
  },
  {
    id: 'road_trips',
    emoji: '🚗',
    title: 'Дорожные приключения',
    questions: [
      { id: 'rt1', type: 'image', text: 'Идеальный road trip — это...', images: [{ id: 'roadtrip_car', label: 'Автомобиль и дорога', url: IMG.roadtrip_car }, { id: 'camping_tent', label: 'Кемпинг под звёздами', url: IMG.camping_tent }] },
      { id: 'rt2', type: 'text', text: 'Какой маршрут ты мечтаешь проехать вместе?' },
      { id: 'rt3', type: 'choice', text: 'За рулём в паре — кто?', options: [{ id: 'me', label: 'Я' }, { id: 'partner', label: 'Партнёр' }, { id: 'switch', label: 'Меняемся' }] },
      { id: 'rt4', type: 'text', text: 'Какая песня должна звучать в нашей машине мечты?' },
    ],
  },
  {
    id: 'nature_walks',
    emoji: '🌲',
    title: 'Прогулки на природе',
    questions: [
      { id: 'nw1', type: 'image', text: 'Куда пойти гулять вдвоём?', images: [{ id: 'forest_walk', label: 'Лесная тропа', url: IMG.forest_walk }, { id: 'lake_calm', label: 'Спокойное озеро', url: IMG.lake_calm }] },
      { id: 'nw2', type: 'text', text: 'Какая прогулка на природе запомнилась тебе больше всего?' },
      { id: 'nw3', type: 'choice', text: 'Прогулки без телефона — это...', options: [{ id: 'need', label: 'Нужны нам регулярно' }, { id: 'nice', label: 'Приятно, но редко' }, { id: 'hard', label: 'Сложно — привык(ла) к телефону' }] },
      { id: 'nw4', type: 'text', text: 'Что ты замечаешь на прогулках, чего я могу не видеть?' },
    ],
  },
  {
    id: 'city_dates',
    emoji: '🏙️',
    title: 'Городские свидания',
    questions: [
      { id: 'cd1', type: 'choice', text: 'Идеальное городское свидание — это...', options: [{ id: 'cafe', label: 'Кафе и долгий разговор' }, { id: 'walk', label: 'Прогулка по незнакомым улицам' }, { id: 'event', label: 'Концерт, выставка, событие' }] },
      { id: 'cd2', type: 'text', text: 'Какое место в городе ты хочешь показать мне?' },
      { id: 'cd3', type: 'choice', text: 'Турист в своём городе — это...', options: [{ id: 'fun', label: 'Весело — открываю новое' }, { id: 'rare', label: 'Редко, но стоит попробовать' }, { id: 'no', label: 'Не моё' }] },
      { id: 'cd4', type: 'text', text: 'Куда бы ты сводил(а) меня, если бы я приехал(а) впервые?' },
    ],
  },
  {
    id: 'outdoor_fun',
    emoji: '🏖️',
    title: 'Отдых на природе',
    questions: [
      { id: 'of1', type: 'image', text: 'Идеальный день на природе — это...', images: [{ id: 'sunset_beach', label: 'Закат на пляже', url: IMG.sunset_beach }, { id: 'stargazing', label: 'Наблюдение за звёздами', url: IMG.stargazing }] },
      { id: 'of2', type: 'text', text: 'Какой outdoor-активности ты хочешь попробовать вместе?' },
      { id: 'of3', type: 'choice', text: 'Пикник или барбекю — что ближе?', options: [{ id: 'picnic', label: 'Пикник с пледом' }, { id: 'bbq', label: 'Барбекю с друзьями' }, { id: 'both', label: 'И то, и другое!' }] },
      { id: 'of4', type: 'text', text: 'Какой сезон лучше всего подходит для приключений вдвоём?' },
    ],
  },
  {
    id: 'seasons_us',
    emoji: '🍂',
    title: 'Времена года',
    questions: [
      { id: 'se1', type: 'choice', text: 'Любимое время года для тебя — это...', options: [{ id: 'spring', label: 'Весна — пробуждение' }, { id: 'summer', label: 'Лето — энергия' }, { id: 'autumn', label: 'Осень — уют' }, { id: 'winter', label: 'Зима — тепло дома' }] },
      { id: 'se2', type: 'text', text: 'Какое сезонное воспоминание с тобой самое тёплое?' },
      { id: 'se3', type: 'choice', text: 'Как мы можем сделать каждый сезон особенным?', options: [{ id: 'tradition', label: 'Сезонные традиции' }, { id: 'trip', label: 'Мини-поездки' }, { id: 'home', label: 'Уют дома' }] },
      { id: 'se4', type: 'text', text: 'Что ты ждёшь от следующего сезона вместе?' },
    ],
  },
  {
    id: 'weather_mood',
    emoji: '🌧️',
    title: 'Погода и настроение',
    questions: [
      { id: 'wm1', type: 'image', text: 'Какая погода задаёт романтическое настроение?', images: [{ id: 'rainy_window', label: 'Дождь за окном', url: IMG.rainy_window }, { id: 'snow_couple', label: 'Снежная прогулка', url: IMG.snow_couple }] },
      { id: 'wm2', type: 'choice', text: 'Плохая погода — это повод...', options: [{ id: 'cuddle', label: 'Устроиться дома вдвоём' }, { id: 'brave', label: 'Выйти и гулять' }, { id: 'sleep', label: 'Спать и отдыхать' }] },
      { id: 'wm3', type: 'text', text: 'Как погода влияет на твоё настроение в отношениях?' },
      { id: 'wm4', type: 'choice', text: 'Идеальный «дождливый» день вместе — это...', options: [{ id: 'movies', label: 'Фильмы и плед' }, { id: 'cook', label: 'Готовка и чай' }, { id: 'walk', label: 'Прогулка под зонтом' }] },
    ],
  },
  {
    id: 'rainy_plans',
    emoji: '☔',
    title: 'Планы на дождливый день',
    questions: [
      { id: 'rp1', type: 'text', text: 'Что мы делаем, когда за окном льёт дождь?' },
      { id: 'rp2', type: 'choice', text: 'Дождь для тебя — это...', options: [{ id: 'cozy', label: 'Уют и романтика' }, { id: 'gloomy', label: 'Грусть и лень' }, { id: 'neutral', label: 'Ничего особенного' }] },
      { id: 'rp3', type: 'text', text: 'Какой фильм или книга идеальны для дождливого дня вдвоём?' },
      { id: 'rp4', type: 'choice', text: 'Если бы мы застряли дома на три дня, что бы сделали?', options: [{ id: 'projects', label: 'Домашние проекты' }, { id: 'games', label: 'Игры и развлечения' }, { id: 'talk', label: 'Глубокие разговоры' }] },
    ],
  },
  {
    id: 'home_decor',
    emoji: '🏠',
    title: 'Стиль дома',
    questions: [
      { id: 'hd1', type: 'image', text: 'Какой интерьер тебе ближе?', images: [{ id: 'boho_decor', label: 'Бохо и уют', url: IMG.boho_decor }, { id: 'minimalist_home', label: 'Минимализм и свет', url: IMG.minimalist_home }] },
      { id: 'hd2', type: 'text', text: 'Какая деталь интерьера делает дом «нашим»?' },
      { id: 'hd3', type: 'choice', text: 'Выбирать мебель вместе — это...', options: [{ id: 'fun', label: 'Увлекательно' }, { id: 'compromise', label: 'Компромиссы, но результат радует' }, { id: 'stress', label: 'Стресс — разные вкусы' }] },
      { id: 'hd4', type: 'text', text: 'Какую комнату ты хочешь оформить вместе в первую очередь?' },
    ],
  },
  {
    id: 'cozy_home',
    emoji: '🕯️',
    title: 'Уют дома',
    questions: [
      { id: 'cy1', type: 'choice', text: 'Что делает дом по-настоящему уютным для тебя?', options: [{ id: 'light', label: 'Мягкий свет и свечи' }, { id: 'textile', label: 'Пледы и подушки' }, { id: 'smell', label: 'Запахи — выпечка, кофе' }] },
      { id: 'cy2', type: 'text', text: 'Какой уютный момент дома ты любишь больше всего?' },
      { id: 'cy3', type: 'choice', text: 'Идеальный вечер дома — это...', options: [{ id: 'cook', label: 'Готовка и ужин' }, { id: 'couch', label: 'Диван и сериал' }, { id: 'bath', label: 'Ванна и расслабление' }] },
      { id: 'cy4', type: 'text', text: 'Какой маленький штрих сделал бы наш дом ещё уютнее?' },
    ],
  },
  {
    id: 'morning_ritual',
    emoji: '☀️',
    title: 'Утренние ритуалы',
    questions: [
      { id: 'mr1', type: 'image', text: 'Идеальное утро вдвоём — это...', images: [{ id: 'coffee_morning', label: 'Кофе и разговор', url: IMG.coffee_morning }, { id: 'breakfast_bed', label: 'Завтрак в постели', url: IMG.breakfast_bed }] },
      { id: 'mr2', type: 'choice', text: 'Ты — жаворонок или сова в паре?', options: [{ id: 'lark', label: 'Жаворонок' }, { id: 'owl', label: 'Сова' }, { id: 'match', label: 'Мы совпадаем!' }] },
      { id: 'mr3', type: 'text', text: 'Какой утренний ритуал ты хотел(а) бы завести?' },
      { id: 'mr4', type: 'choice', text: 'Просыпаться вместе — это...', options: [{ id: 'best', label: 'Лучшее начало дня' }, { id: 'rare', label: 'Редкость — разные графики' }, { id: 'hard', label: 'Сложно — нужен сон' }] },
    ],
  },
  {
    id: 'coffee_love',
    emoji: '☕',
    title: 'Кофе и разговоры',
    questions: [
      { id: 'cl1', type: 'choice', text: 'Кофе или чай — что ближе?', options: [{ id: 'coffee', label: 'Кофе!' }, { id: 'tea', label: 'Чай' }, { id: 'both', label: 'Зависит от настроения' }] },
      { id: 'cl2', type: 'text', text: 'Какой разговор за чашкой кофе запомнился тебе?' },
      { id: 'cl3', type: 'choice', text: 'Утренний кофе вместе — это...', options: [{ id: 'ritual', label: 'Наш ритуал' }, { id: 'luxury', label: 'Роскошь — редко получается' }, { id: 'want', label: 'Хочу, чтобы было чаще' }] },
      { id: 'cl4', type: 'text', text: 'В каком кафе ты хотел(а) бы проводить со мной больше времени?' },
    ],
  },
  {
    id: 'dinner_us',
    emoji: '🍽️',
    title: 'Ужин вдвоём',
    questions: [
      { id: 'di1', type: 'text', text: 'Какой наш ужин ты бы назвал(а) идеальным?' },
      { id: 'di2', type: 'choice', text: 'Готовить ужин или заказать — что чаще?', options: [{ id: 'cook', label: 'Готовим' }, { id: 'order', label: 'Заказываем' }, { id: 'mix', label: 'По ситуации' }] },
      { id: 'di3', type: 'text', text: 'О чём ты мечтаешь поговорить за следующим ужином?' },
      { id: 'di4', type: 'choice', text: 'Ужин при свечах — это...', options: [{ id: 'often', label: 'Можем устроить и просто так' }, { id: 'special', label: 'Для особых случаев' }, { id: 'cliche', label: 'Банально, но приятно' }] },
    ],
  },
  {
    id: 'food_explore',
    emoji: '🌮',
    title: 'Гастрономические открытия',
    questions: [
      { id: 'fe1', type: 'choice', text: 'Попробовать экзотическую еду — это...', options: [{ id: 'yes', label: 'Да! Люблю эксперименты' }, { id: 'careful', label: 'Осторожно, но попробую' }, { id: 'no', label: 'Лучше привычное' }] },
      { id: 'fe2', type: 'text', text: 'Какую кухню мира ты хочешь исследовать вместе?' },
      { id: 'fe3', type: 'text', text: 'Какое блюдо ты готов(а) готовить для меня, даже если не умеешь?' },
      { id: 'fe4', type: 'choice', text: 'Идеальный food-фестиваль для нас — это...', options: [{ id: 'street', label: 'Уличная еда' }, { id: 'fine', label: 'Fine dining' }, { id: 'market', label: 'Рынок и дегустации' }] },
    ],
  },
  {
    id: 'movie_date',
    emoji: '🎬',
    title: 'Кино-свидания',
    questions: [
      { id: 'md1', type: 'image', text: 'Идеальный кино-вечер — это...', images: [{ id: 'cinema_date', label: 'Поход в кинотеатр', url: IMG.cinema_date }, { id: 'couch_movie', label: 'Фильм на диване', url: IMG.couch_movie }] },
      { id: 'md2', type: 'text', text: 'Какой фильм ты хотел(а) бы пересмотреть со мной?' },
      { id: 'md3', type: 'choice', text: 'Жанр для свидания — какой выбираешь?', options: [{ id: 'romcom', label: 'Романтическая комедия' }, { id: 'thriller', label: 'Триллер — держимся за руки' }, { id: 'doc', label: 'Документалка и обсуждение' }] },
      { id: 'md4', type: 'text', text: 'Какой фильм мог бы рассказать нашу историю?' },
    ],
  },
  {
    id: 'binge_watch',
    emoji: '📺',
    title: 'Сериалы и марафоны',
    questions: [
      { id: 'bw1', type: 'choice', text: 'Смотреть сериал вместе — это...', options: [{ id: 'must', label: 'Обязательно синхронно!' }, { id: 'flexible', label: 'Можно в разном темпе' }, { id: 'solo', label: 'Иногда каждый своё' }] },
      { id: 'bw2', type: 'text', text: 'Какой сериал ты хотел(а) бы начать смотреть со мной?' },
      { id: 'bw3', type: 'choice', text: 'Когда я смотрю «ещё одну серию» без тебя, ты...', options: [{ id: 'fine', label: 'Нормально — догоню' }, { id: 'wait', label: 'Жду, чтобы вместе' }, { id: 'spoiler', label: 'Боюсь спойлеров!' }] },
      { id: 'bw4', type: 'text', text: 'Какой сериальный персонаж похож на нас?' },
    ],
  },
  {
    id: 'playlist_us',
    emoji: '🎧',
    title: 'Наш плейлист',
    questions: [
      { id: 'pu1', type: 'text', text: 'Какую песню ты добавил(а) бы в «наш» плейлист прямо сейчас?' },
      { id: 'pu2', type: 'choice', text: 'Музыка в машине — кто выбирает?', options: [{ id: 'driver', label: 'Водитель' }, { id: 'passenger', label: 'Пассажир' }, { id: 'shuffle', label: 'Случайный плейлист' }] },
      { id: 'pu3', type: 'text', text: 'Какая песня мгновенно возвращает тебя к нашему моменту?' },
      { id: 'pu4', type: 'choice', text: 'Концерт вместе — это...', options: [{ id: 'dream', label: 'Мечта!' }, { id: 'done', label: 'Уже были — хотим ещё' }, { id: 'home', label: 'Лучше дома с колонкой' }] },
    ],
  },
  {
    id: 'live_music',
    emoji: '🎤',
    title: 'Живая музыка',
    questions: [
      { id: 'lm1', type: 'choice', text: 'Живой концерт vs запись — что лучше?', options: [{ id: 'live', label: 'Живое — энергия!' }, { id: 'record', label: 'Запись — комфортнее' }, { id: 'both', label: 'Зависит от настроения' }] },
      { id: 'lm2', type: 'text', text: 'На какой концерт ты хотел(а) бы сходить вместе?' },
      { id: 'lm3', type: 'text', text: 'Какой музыкальный момент с тобой запомнился больше всего?' },
      { id: 'lm4', type: 'choice', text: 'Если бы мы играли в группе, кто на чём?', options: [{ id: 'vocal', label: 'Я — вокал, ты — инструмент' }, { id: 'both', label: 'Оба поём' }, { id: 'dj', label: 'DJ-сет вдвоём' }] },
    ],
  },
  {
    id: 'dance_us',
    emoji: '💃',
    title: 'Танцуем вместе',
    questions: [
      { id: 'da1', type: 'image', text: 'Какой танец ближе к нам?', images: [{ id: 'dance_floor', label: 'Танцпол и энергия', url: IMG.dance_floor }, { id: 'wedding_dance', label: 'Медленный свадебный танец', url: IMG.wedding_dance }] },
      { id: 'da2', type: 'choice', text: 'Танцевать вместе — это...', options: [{ id: 'love', label: 'Обожаю!' }, { id: 'shy', label: 'Смущаюсь, но попробую' }, { id: 'funny', label: 'Смешно — и это прикол' }] },
      { id: 'da3', type: 'text', text: 'Какую песню ты бы выбрал(а) для нашего медленного танца?' },
      { id: 'da4', type: 'choice', text: 'На свадьбе друга мы...', options: [{ id: 'dance', label: 'Танцуем всю ночь' }, { id: 'watch', label: 'Смотрим и болтаем' }, { id: 'leave', label: 'Уходим рано' }] },
    ],
  },
  {
    id: 'party_mode',
    emoji: '🎉',
    title: 'Вечеринки и тусовки',
    questions: [
      { id: 'pm1', type: 'image', text: 'Идеальный вечер с друзьями — это...', images: [{ id: 'party_friends', label: 'Вечеринка с друзьями', url: IMG.party_friends }, { id: 'wine_evening', label: 'Тихий вечер с вином', url: IMG.wine_evening }] },
      { id: 'pm2', type: 'choice', text: 'На вечеринках мы — это...', options: [{ id: 'together', label: 'Всегда рядом' }, { id: 'social', label: 'Общаемся с разными людьми' }, { id: 'early', label: 'Уходим пораньше' }] },
      { id: 'pm3', type: 'text', text: 'Какой совместный выход «в свет» запомнился тебе?' },
      { id: 'pm4', type: 'choice', text: 'Приглашать друзей домой — это...', options: [{ id: 'love', label: 'Люблю устраивать' }, { id: 'sometimes', label: 'Иногда — не часто' }, { id: 'no', label: 'Предпочитаю только нас' }] },
    ],
  },
  {
    id: 'friend_circle',
    emoji: '👥',
    title: 'Круг друзей',
    questions: [
      { id: 'fc1', type: 'choice', text: 'Друзья в отношениях — это...', options: [{ id: 'important', label: 'Важная часть жизни' }, { id: 'few', label: 'Мало, но близкие' }, { id: 'us', label: 'Главное — мы вдвоём' }] },
      { id: 'fc2', type: 'text', text: 'Какой друг повлиял на наши отношения больше всего?' },
      { id: 'fc3', type: 'choice', text: 'Знакомить партнёра с друзьями — это...', options: [{ id: 'excited', label: 'Волнительно и приятно' }, { id: 'nervous', label: 'Немного стрессно' }, { id: 'natural', label: 'Естественно' }] },
      { id: 'fc4', type: 'text', text: 'Как мы можем лучше интегрировать друг друга в свои круги?' },
    ],
  },
  {
    id: 'our_friends',
    emoji: '🤗',
    title: 'Общие друзья',
    questions: [
      { id: 'ouf1', type: 'text', text: 'Какой общий друг стал важен для нас обоих?' },
      { id: 'ouf2', type: 'choice', text: 'Двойные свидания с друзьями — это...', options: [{ id: 'fun', label: 'Весело!' }, { id: 'ok', label: 'Нормально, но редко' }, { id: 'prefer', label: 'Лучше только мы' }] },
      { id: 'ouf3', type: 'text', text: 'Кого из моих друзей ты хотел(а) бы узнать лучше?' },
      { id: 'ouf4', type: 'choice', text: 'Если бы мы устроили ужин для друзей, что бы приготовили?', options: [{ id: 'fancy', label: 'Что-то впечатляющее' }, { id: 'simple', label: 'Простое и вкусное' }, { id: 'order', label: 'Заказали бы — честно' }] },
    ],
  },
  {
    id: 'meet_family',
    emoji: '🏡',
    title: 'Знакомство с семьёй',
    questions: [
      { id: 'mf1', type: 'text', text: 'Как ты себя чувствовал(а), когда знакомился(лась) с моей семьёй?' },
      { id: 'mf2', type: 'choice', text: 'Семья партнёра для тебя — это...', options: [{ id: 'warm', label: 'Тёплые люди, часть жизни' }, { id: 'learning', label: 'Учусь понимать' }, { id: 'complex', label: 'Сложно, но стараюсь' }] },
      { id: 'mf3', type: 'text', text: 'Какой момент с моей семьёй запомнился тебе?' },
      { id: 'mf4', type: 'choice', text: 'Семейные ужины — как часто?', options: [{ id: 'monthly', label: 'Раз в месяц' }, { id: 'holidays', label: 'Только праздники' }, { id: 'rare', label: 'Редко — и это OK' }] },
    ],
  },
  {
    id: 'in_laws',
    emoji: '🤝',
    title: 'Отношения с роднёй',
    questions: [
      { id: 'il1', type: 'choice', text: 'Советы от родителей партнёра — это...', options: [{ id: 'welcome', label: 'Приветствую' }, { id: 'filter', label: 'Слушаю, но фильтрую' }, { id: 'hard', label: 'Сложно воспринимаю' }] },
      { id: 'il2', type: 'text', text: 'Как нам сохранять границы с родственниками?' },
      { id: 'il3', type: 'choice', text: 'Праздники с двумя семьями — это...', options: [{ id: 'rotate', label: 'Чередуем' }, { id: 'together', label: 'Собираем всех' }, { id: 'separate', label: 'Отмечаем отдельно' }] },
      { id: 'il4', type: 'text', text: 'Что ты ценишь в моих родителях или родственниках?' },
    ],
  },
  {
    id: 'kids_talk',
    emoji: '👶',
    title: 'Разговор о детях',
    questions: [
      { id: 'kt1', type: 'choice', text: 'Дети в наших планах — это...', options: [{ id: 'yes', label: 'Да, хотим' }, { id: 'maybe', label: 'Может быть, позже' }, { id: 'no', label: 'Нет / не уверен(а)' }] },
      { id: 'kt2', type: 'text', text: 'Каким родителем ты видишь меня?' },
      { id: 'kt3', type: 'choice', text: 'Как мы будем делить родительские обязанности?', options: [{ id: 'equal', label: 'Поровну' }, { id: 'strengths', label: 'По сильным сторонам' }, { id: 'discuss', label: 'Обсудим, когда придёт время' }] },
      { id: 'kt4', type: 'text', text: 'Какую ценность ты хочешь передать нашим детям?' },
    ],
  },
  {
    id: 'family_values',
    emoji: '💎',
    title: 'Семейные ценности',
    questions: [
      { id: 'fv1', type: 'text', text: 'Какая ценность из твоей семьи самая важная для тебя?' },
      { id: 'fv2', type: 'choice', text: 'Семья для тебя — это прежде всего...', options: [{ id: 'support', label: 'Поддержка' }, { id: 'tradition', label: 'Традиции' }, { id: 'love', label: 'Безусловная любовь' }] },
      { id: 'fv3', type: 'text', text: 'Какие ценности мы уже разделяем как пара?' },
      { id: 'fv4', type: 'choice', text: 'Если бы мы написали «семейный манифест», что там было бы первым?', options: [{ id: 'honesty', label: 'Честность' }, { id: 'fun', label: 'Радость и смех' }, { id: 'respect', label: 'Уважение' }] },
    ],
  },
  {
    id: 'talk_style',
    emoji: '🗣️',
    title: 'Стиль общения',
    questions: [
      { id: 'ts1', type: 'choice', text: 'Ты предпочитаешь говорить или слушать?', options: [{ id: 'talk', label: 'Говорить — мне нужно высказаться' }, { id: 'listen', label: 'Слушать — так понимаю лучше' }, { id: 'both', label: 'Зависит от темы' }] },
      { id: 'ts2', type: 'text', text: 'Когда я молчу, что ты думаешь?' },
      { id: 'ts3', type: 'choice', text: 'Серьёзные разговоры лучше проводить...', options: [{ id: 'face', label: 'Лицом к лицу' }, { id: 'walk', label: 'На прогулке' }, { id: 'evening', label: 'Вечером, когда спокойно' }] },
      { id: 'ts4', type: 'text', text: 'Какой мой стиль общения ты ценишь больше всего?' },
    ],
  },
  {
    id: 'love_language',
    emoji: '💝',
    title: 'Языки любви',
    questions: [
      { id: 'll1', type: 'choice', text: 'Твой главный язык любви — это...', options: [{ id: 'words', label: 'Слова поддержки' }, { id: 'time', label: 'Качественное время' }, { id: 'touch', label: 'Прикосновения' }, { id: 'gifts', label: 'Подарки' }, { id: 'acts', label: 'Помощь и забота' }] },
      { id: 'll2', type: 'text', text: 'Когда ты последний раз почувствовал(а) мою любовь на «своём языке»?' },
      { id: 'll3', type: 'choice', text: 'Какой язык любви партнёра ты учишься понимать?', options: [{ id: 'same', label: 'Наши совпадают!' }, { id: 'learning', label: 'Учусь говорить на его/её' }, { id: 'different', label: 'Разные — и это вызов' }] },
      { id: 'll4', type: 'text', text: 'Что я могу сделать завтра, чтобы ты почувствовал(а) себя любимым(ой)?' },
    ],
  },
  {
    id: 'compliments',
    emoji: '✨',
    title: 'Сила комплиментов',
    questions: [
      { id: 'cm1', type: 'text', text: 'Какой комплимент от меня запомнился тебе больше всего?' },
      { id: 'cm2', type: 'choice', text: 'Комплименты для тебя — это...', options: [{ id: 'need', label: 'Нужны регулярно' }, { id: 'nice', label: 'Приятно, но не обязательно' }, { id: 'shy', label: 'Смущают — но нравятся' }] },
      { id: 'cm3', type: 'text', text: 'За что ты хотел(а) бы получить комплимент прямо сейчас?' },
      { id: 'cm4', type: 'choice', text: 'Как ты предпочитаешь получать комплименты?', options: [{ id: 'public', label: 'При всех — мне приятно' }, { id: 'private', label: 'Наедине' }, { id: 'text', label: 'В сообщении — могу перечитать' }] },
    ],
  },
  {
    id: 'gratitude',
    emoji: '🙏',
    title: 'Благодарность',
    questions: [
      { id: 'gr1', type: 'text', text: 'За что ты благодарен(на) мне сегодня?' },
      { id: 'gr2', type: 'choice', text: 'Говорить «спасибо» в паре — это...', options: [{ id: 'daily', label: 'Каждый день' }, { id: 'when', label: 'Когда по-настоящему чувствую' }, { id: 'actions', label: 'Показываю делами' }] },
      { id: 'gr3', type: 'text', text: 'Какой момент с тобой вызывает благодарность, когда оглядываешься назад?' },
      { id: 'gr4', type: 'choice', text: 'Как мы можем практиковать благодарность вместе?', options: [{ id: 'journal', label: 'Дневник благодарности' }, { id: 'evening', label: 'Вечерний «за что спасибо»' }, { id: 'surprise', label: 'Случайные записки' }] },
    ],
  },
  {
    id: 'forgiveness',
    emoji: '🌱',
    title: 'Прощение',
    questions: [
      { id: 'fg1', type: 'choice', text: 'Простить — для тебя это...', options: [{ id: 'quick', label: 'Быстро — не держу обиду' }, { id: 'time', label: 'Нужно время' }, { id: 'hard', label: 'Сложно, но стараюсь' }] },
      { id: 'fg2', type: 'text', text: 'Когда я прощаю тебя, что для тебя значит больше всего?' },
      { id: 'fg3', type: 'text', text: 'Есть ли что-то, что ты ещё не простил(а) — и готов(а) обсудить?' },
      { id: 'fg4', type: 'choice', text: 'Как пара может расти через прощение?', options: [{ id: 'talk', label: 'Честные разговоры' }, { id: 'understand', label: 'Понимание мотивов' }, { id: 'move', label: 'Отпустить и идти дальше' }] },
    ],
  },
  {
    id: 'open_up',
    emoji: '🫀',
    title: 'Открыться',
    questions: [
      { id: 'ou1', type: 'text', text: 'О чём ты давно хочешь поговорить, но откладываешь?' },
      { id: 'ou2', type: 'choice', text: 'Открываться партнёру — это...', options: [{ id: 'natural', label: 'Естественно' }, { id: 'gradual', label: 'Постепенно — доверие растёт' }, { id: 'scary', label: 'Страшно, но важно' }] },
      { id: 'ou3', type: 'text', text: 'Когда ты чувствуешь, что можешь быть полностью собой?' },
      { id: 'ou4', type: 'choice', text: 'Что помогает тебе открыться?', options: [{ id: 'trust', label: 'Доверие и время' }, { id: 'questions', label: 'Правильные вопросы' }, { id: 'silence', label: 'Тишина и терпение' }] },
    ],
  },
  {
    id: 'emotional_intimacy',
    emoji: '💞',
    title: 'Эмоциональная близость',
    questions: [
      { id: 'ei1', type: 'text', text: 'Когда ты чувствуешь эмоциональную близость со мной сильнее всего?' },
      { id: 'ei2', type: 'choice', text: 'Эмоциональная близость для тебя — это...', options: [{ id: 'share', label: 'Делиться переживаниями' }, { id: 'understand', label: 'Быть понятым без слов' }, { id: 'safe', label: 'Чувствовать себя в безопасности' }] },
      { id: 'ei3', type: 'text', text: 'Что мешает тебе быть эмоционально ближе — и как я могу помочь?' },
      { id: 'ei4', type: 'choice', text: 'Глубокая эмоциональная связь — это...', options: [{ id: 'have', label: 'У нас уже есть' }, { id: 'growing', label: 'Растёт с каждым днём' }, { id: 'want', label: 'Хочу больше' }] },
    ],
  },
  {
    id: 'physical_affection',
    emoji: '🤗',
    title: 'Физическая нежность',
    questions: [
      { id: 'pa1', type: 'choice', text: 'Какой вид прикосновений ты любишь больше всего?', options: [{ id: 'hug', label: 'Долгие объятия' }, { id: 'hand', label: 'Держаться за руки' }, { id: 'cuddle', label: 'Прижаться и молчать' }] },
      { id: 'pa2', type: 'text', text: 'Когда я обнимаю тебя неожиданно — что ты чувствуешь?' },
      { id: 'pa3', type: 'choice', text: 'Публичная нежность — для тебя это...', options: [{ id: 'love', label: 'Нравится' }, { id: 'sometimes', label: 'Зависит от места' }, { id: 'private', label: 'Лучше наедине' }] },
      { id: 'pa4', type: 'text', text: 'Как я могу чаще показывать нежность так, как тебе приятно?' },
    ],
  },
  {
    id: 'secret_wishes',
    emoji: '✨',
    title: 'Тайные желания',
    questions: [
      { id: 'sw1', type: 'text', text: 'О чём ты мечтаешь, но ещё не говорил(а) мне?' },
      { id: 'sw2', type: 'choice', text: 'Делиться тайными желаниями — это...', options: [{ id: 'exciting', label: 'Волнительно и приятно' }, { id: 'scary', label: 'Страшновато' }, { id: 'ready', label: 'Готов(а) попробовать' }] },
      { id: 'sw3', type: 'text', text: 'Какое желание мы могли бы исполнить друг для друга в этом месяце?' },
      { id: 'sw4', type: 'choice', text: 'Если бы я исполнил(а) одно твоё желание завтра — что бы это было?', options: [{ id: 'experience', label: 'Впечатление или приключение' }, { id: 'comfort', label: 'Забота и уют' }, { id: 'surprise', label: 'Сюрприз — угадай сам(а)' }] },
    ],
  },
  {
    id: 'boundaries',
    emoji: '🚧',
    title: 'Здоровые границы',
    questions: [
      { id: 'bo1', type: 'choice', text: 'Границы в отношениях — это...', options: [{ id: 'essential', label: 'Необходимость' }, { id: 'learning', label: 'Учимся вместе' }, { id: 'unclear', label: 'Пока неясно' }] },
      { id: 'bo2', type: 'text', text: 'Какая граница для тебя особенно важна?' },
      { id: 'bo3', type: 'text', text: 'Был ли момент, когда тебе нужно было обозначить границу?' },
      { id: 'bo4', type: 'choice', text: 'Когда я уважаю твои границы, ты...', options: [{ id: 'safe', label: 'Чувствуешь себя в безопасности' }, { id: 'closer', label: 'Становимся ближе' }, { id: 'grateful', label: 'Благодарен(на)' }] },
    ],
  },
  {
    id: 'alone_time',
    emoji: '🧘‍♀️',
    title: 'Время на себя',
    questions: [
      { id: 'at1', type: 'text', text: 'Что ты делаешь в своё личное время, о чём я могу не знать?' },
      { id: 'at2', type: 'choice', text: 'Скучать друг по другу — это...', options: [{ id: 'sweet', label: 'Мило и романтично' }, { id: 'normal', label: 'Нормально — мы не слиплись' }, { id: 'rare', label: 'Редко — мы много вместе' }] },
      { id: 'at3', type: 'text', text: 'Как мы можем поддерживать личное пространство друг друга?' },
      { id: 'at4', type: 'choice', text: 'После времени на себя ты...', options: [{ id: 'recharged', label: 'Возвращаешься с энергией' }, { id: 'miss', label: 'Скучаешь и рад(а) видеть' }, { id: 'same', label: 'Ничего не меняется' }] },
    ],
  },
  {
    id: 'phone_habits',
    emoji: '📱',
    title: 'Телефон в паре',
    questions: [
      { id: 'ph1', type: 'choice', text: 'Телефон за ужином — это...', options: [{ id: 'no', label: 'Табу — мы вместе' }, { id: 'sometimes', label: 'Иногда — если важно' }, { id: 'normal', label: 'Нормально' }] },
      { id: 'ph2', type: 'text', text: 'Когда телефон партнёра мешает общению, что ты чувствуешь?' },
      { id: 'ph3', type: 'choice', text: 'Как мы можем меньше отвлекаться на экраны?', options: [{ id: 'box', label: 'Коробка для телефонов' }, { id: 'rule', label: 'Правило «без телефона» вечером' }, { id: 'trust', label: 'Просто договориться' }] },
      { id: 'ph4', type: 'text', text: 'Какое сообщение от меня ты любишь получать больше всего?' },
    ],
  },
  {
    id: 'screen_time',
    emoji: '💻',
    title: 'Экранное время',
    questions: [
      { id: 'sc1', type: 'choice', text: 'Сериалы vs реальное время вместе — баланс...', options: [{ id: 'us', label: 'Мы важнее экрана' }, { id: 'share', label: 'Смотрим вместе — это тоже «мы»' }, { id: 'struggle', label: 'Борюсь с этим' }] },
      { id: 'sc2', type: 'text', text: 'Какой контент ты хотел(а) бы смотреть или обсуждать вместе?' },
      { id: 'sc3', type: 'choice', text: 'Цифровой детокс вдвоём — это...', options: [{ id: 'want', label: 'Хочу попробовать' }, { id: 'tried', label: 'Пробовали — помогло' }, { id: 'hard', label: 'Слишком сложно' }] },
      { id: 'sc4', type: 'text', text: 'Как технологии помогают нашим отношениям?' },
    ],
  },
  {
    id: 'social_online',
    emoji: '🌐',
    title: 'Мы в соцсетях',
    questions: [
      { id: 'soc1', type: 'choice', text: 'Посты о нас в соцсетях — это...', options: [{ id: 'love', label: 'Люблю делиться' }, { id: 'private', label: 'Предпочитаю приватность' }, { id: 'sometimes', label: 'Иногда — особые моменты' }] },
      { id: 'soc2', type: 'text', text: 'Как ты относишься к тому, что я лайкаю или комментирую?' },
      { id: 'soc3', type: 'choice', text: 'Пара в интернете — показывать или скрывать?', options: [{ id: 'open', label: 'Открыто — нам нечего скрывать' }, { id: 'minimal', label: 'Минимум' }, { id: 'none', label: 'Не наш формат' }] },
      { id: 'soc4', type: 'text', text: 'Какой наш момент ты бы не постил, но он дорог?' },
    ],
  },
  {
    id: 'nostalgia',
    emoji: '📼',
    title: 'Ностальгия',
    questions: [
      { id: 'no1', type: 'text', text: 'На какой период наших отношений ты оглядываешься с теплотой?' },
      { id: 'no2', type: 'choice', text: 'Ностальгия для тебя — это...', options: [{ id: 'sweet', label: 'Сладкая грусть' }, { id: 'motivation', label: 'Мотивация для будущего' }, { id: 'rare', label: 'Редко — живу настоящим' }] },
      { id: 'no3', type: 'text', text: 'Какой «старый» момент с тобой ты бы хотел(а) пережить снова?' },
      { id: 'no4', type: 'choice', text: 'Фото или вещи из прошлого — это...', options: [{ id: 'treasure', label: 'Сокровища' }, { id: 'sometimes', label: 'Приятно, но не застреваю' }, { id: 'forward', label: 'Смотрю вперёд' }] },
    ],
  },
  {
    id: 'photo_wall',
    emoji: '🖼️',
    title: 'Стена воспоминаний',
    questions: [
      { id: 'pw1', type: 'image', text: 'Как хранить воспоминания?', images: [{ id: 'polaroid_wall', label: 'Стена полароидов', url: IMG.polaroid_wall }, { id: 'vintage_room', label: 'Винтажный уголок', url: IMG.vintage_room }] },
      { id: 'pw2', type: 'text', text: 'Какое фото с нами — твоё любимое?' },
      { id: 'pw3', type: 'choice', text: 'Печатать фото или хранить в телефоне?', options: [{ id: 'print', label: 'Печатать — хочу видеть' }, { id: 'digital', label: 'В телефоне достаточно' }, { id: 'both', label: 'И то, и другое' }] },
      { id: 'pw4', type: 'text', text: 'Какое воспоминание ты хотел(а) бы оформить в рамку?' },
    ],
  },
  {
    id: 'anniversaries',
    emoji: '💍',
    title: 'Годовщины',
    questions: [
      { id: 'an1', type: 'choice', text: 'Отмечать годовщины — это...', options: [{ id: 'must', label: 'Обязательно — каждый год' }, { id: 'flexible', label: 'Главное — помнить' }, { id: 'surprise', label: 'Люблю сюрпризы, не даты' }] },
      { id: 'an2', type: 'text', text: 'Какую годовщину ты ждёшь с особым нетерпением?' },
      { id: 'an3', type: 'text', text: 'Как мы отметили нашу лучшую годовщину?' },
      { id: 'an4', type: 'choice', text: 'Идеальный подарок на годовщину — это...', options: [{ id: 'experience', label: 'Впечатление вместе' }, { id: 'symbol', label: 'Что-то символичное' }, { id: 'letter', label: 'Письмо или слова' }] },
    ],
  },
  {
    id: 'milestones',
    emoji: '🏆',
    title: 'Важные вехи',
    questions: [
      { id: 'mi1', type: 'text', text: 'Какая веха в наших отношениях для тебя самая значимая?' },
      { id: 'mi2', type: 'choice', text: 'Праздновать маленькие победы — это...', options: [{ id: 'yes', label: 'Да — каждый шаг важен' }, { id: 'sometimes', label: 'Иногда забываем' }, { id: 'big', label: 'Только большие события' }] },
      { id: 'mi3', type: 'text', text: 'Какую следующую веху ты хочешь достичь вместе?' },
      { id: 'mi4', type: 'choice', text: 'Когда мы достигаем цели, ты...', options: [{ id: 'celebrate', label: 'Празднуем!' }, { id: 'quiet', label: 'Тихо радуемся' }, { id: 'next', label: 'Сразу ставим новую' }] },
    ],
  },
  {
    id: 'love_notes',
    emoji: '💌',
    title: 'Любовные записки',
    questions: [
      { id: 'ln1', type: 'image', text: 'Какой романтический жест ближе?', images: [{ id: 'handwritten_note', label: 'Записка от руки', url: IMG.handwritten_note }, { id: 'flowers_bouquet', label: 'Букет цветов', url: IMG.flowers_bouquet }] },
      { id: 'ln2', type: 'text', text: 'Получал(а) ли ты когда-нибудь записку от меня? Как это было?' },
      { id: 'ln3', type: 'choice', text: 'Письма и записки — это...', options: [{ id: 'romantic', label: 'Очень романтично' }, { id: 'cute', label: 'Мило, но редко' }, { id: 'old', label: 'Старомодно — лучше сообщения' }] },
      { id: 'ln4', type: 'text', text: 'Что бы ты написал(а) мне в записке, если бы оставил(а) её утром?' },
    ],
  },
  {
    id: 'surprises_us',
    emoji: '🎊',
    title: 'Сюрпризы',
    questions: [
      { id: 'su1', type: 'choice', text: 'Сюрпризы для тебя — это...', options: [{ id: 'love', label: 'Обожаю!' }, { id: 'mixed', label: 'Зависит — люблю приятные' }, { id: 'plan', label: 'Предпочитаю знать заранее' }] },
      { id: 'su2', type: 'text', text: 'Какой сюрприз от меня ты никогда не забудешь?' },
      { id: 'su3', type: 'choice', text: 'Устраивать сюрпризы — это...', options: [{ id: 'fun', label: 'Весело — люблю готовить' }, { id: 'stress', label: 'Стресс — боюсь не угадать' }, { id: 'rare', label: 'Редко, но от души' }] },
      { id: 'su4', type: 'text', text: 'Какой сюрприз ты хотел(а) бы устроить мне?' },
    ],
  },
  {
    id: 'city_nights',
    emoji: '🌃',
    title: 'Городские ночи',
    questions: [
      { id: 'cn1', type: 'image', text: 'Идеальный вечер — это...', images: [{ id: 'city_night', label: 'Огни города', url: IMG.city_night }, { id: 'sunset_beach', label: 'Закат у моря', url: IMG.sunset_beach }] },
      { id: 'cn2', type: 'text', text: 'Какой город ты мечтаешь исследовать вместе ночью?' },
      { id: 'cn3', type: 'choice', text: 'Ночные прогулки — это...', options: [{ id: 'romantic', label: 'Романтика!' }, { id: 'rare', label: 'Редко — устаём' }, { id: 'adventure', label: 'Приключение' }] },
      { id: 'cn4', type: 'text', text: 'Какой вечер в городе с тобой запомнился больше всего?' },
    ],
  },
  {
    id: 'market_stroll',
    emoji: '🥬',
    title: 'Рынок и прогулка',
    questions: [
      { id: 'mk1', type: 'image', text: 'Куда пойти в субботу?', images: [{ id: 'farmers_market', label: 'Фермерский рынок', url: IMG.farmers_market }, { id: 'vintage_room', label: 'Винтажная лавка', url: IMG.vintage_room }] },
      { id: 'mk2', type: 'text', text: 'Совместный поход за продуктами — свидание или рутина?' },
      { id: 'mk3', type: 'choice', text: 'Рынок или супермаркет — что ближе?', options: [{ id: 'market', label: 'Рынок — атмосфера' }, { id: 'super', label: 'Супермаркет — быстро' }, { id: 'delivery', label: 'Доставка' }] },
      { id: 'mk4', type: 'text', text: 'Что бы мы нашли на идеальном рынке?' },
    ],
  },
  {
    id: 'growth_together',
    emoji: '🌿',
    title: 'Растём вместе',
    questions: [
      { id: 'gt1', type: 'text', text: 'Чему я научил(а) тебя за время наших отношений?' },
      { id: 'gt2', type: 'choice', text: 'Расти как пара — это...', options: [{ id: 'conscious', label: 'Осознанная работа' }, { id: 'natural', label: 'Происходит само' }, { id: 'challenge', label: 'Вызов, но стоит того' }] },
      { id: 'gt3', type: 'text', text: 'В чём ты стал(а) лучше благодаря нашим отношениям?' },
      { id: 'gt4', type: 'choice', text: 'Как мы можем расти вместе в этом году?', options: [{ id: 'goals', label: 'Общие цели' }, { id: 'habits', label: 'Новые привычки' }, { id: 'talk', label: 'Больше глубоких разговоров' }] },
    ],
  },
  {
    id: 'change_adapt',
    emoji: '🔄',
    title: 'Изменения и адаптация',
    questions: [
      { id: 'ca1', type: 'choice', text: 'Когда жизнь меняется, ты...', options: [{ id: 'adapt', label: 'Быстро адаптируюсь' }, { id: 'stress', label: 'Стрессую, потом принимаю' }, { id: 'partner', label: 'Опираюсь на партнёра' }] },
      { id: 'ca2', type: 'text', text: 'Какое большое изменение мы пережили лучше всего?' },
      { id: 'ca3', type: 'text', text: 'Что пугает тебя в переменах — и как я могу помочь?' },
      { id: 'ca4', type: 'choice', text: 'Изменения в отношениях — это...', options: [{ id: 'growth', label: 'Рост' }, { id: 'scary', label: 'Страшно' }, { id: 'normal', label: 'Нормальная часть жизни' }] },
    ],
  },
  {
    id: 'humor_style',
    emoji: '😄',
    title: 'Юмор в паре',
    questions: [
      { id: 'hs1', type: 'choice', text: 'Твой тип юмора — это...', options: [{ id: 'sarcasm', label: 'Сарказм и ирония' }, { id: 'silly', label: 'Глупости и мемы' }, { id: 'warm', label: 'Тёплый и добрый' }] },
      { id: 'hs2', type: 'text', text: 'Когда мы смеёмся вместе — над чем чаще всего?' },
      { id: 'hs3', type: 'choice', text: 'Шутить в ссоре — это...', options: [{ id: 'helps', label: 'Помогает разрядить' }, { id: 'worse', label: 'Только хуже' }, { id: 'depends', label: 'Зависит от ситуации' }] },
      { id: 'hs4', type: 'text', text: 'Какая шутка или мем стала «нашей»?' },
    ],
  },
  {
    id: 'inside_jokes',
    emoji: '🤫',
    title: 'Секретные шутки',
    questions: [
      { id: 'ij1', type: 'text', text: 'Какая наша inside joke сразу заставляет тебя улыбнуться?' },
      { id: 'ij2', type: 'choice', text: 'Inside jokes — это...', options: [{ id: 'bond', label: 'Наша связь' }, { id: 'many', label: 'Их слишком много' }, { id: 'building', label: 'Ещё создаём' }] },
      { id: 'ij3', type: 'text', text: 'Как появилась наша самая странная шутка?' },
      { id: 'ij4', type: 'choice', text: 'Если бы посторонний услышал нас, он бы...', options: [{ id: 'confused', label: 'Ничего не понял' }, { id: 'laugh', label: 'Тоже засмеялся' }, { id: 'jealous', label: 'Завидовал нашей связи' }] },
    ],
  },
  {
    id: 'legacy_dreams',
    emoji: '🌍',
    title: 'Наследие и смысл',
    questions: [
      { id: 'ld1', type: 'text', text: 'Какой след ты хочешь оставить вместе со мной?' },
      { id: 'ld2', type: 'choice', text: 'Смысл жизни для тебя — это...', options: [{ id: 'love', label: 'Любовь и близкие' }, { id: 'create', label: 'Создавать что-то' }, { id: 'experience', label: 'Переживать и чувствовать' }] },
      { id: 'ld3', type: 'text', text: 'О чём ты хочешь, чтобы мы вспоминали через 20 лет?' },
      { id: 'ld4', type: 'choice', text: 'Если бы мы написали книгу о нас, жанр был бы...', options: [{ id: 'romance', label: 'Роман' }, { id: 'comedy', label: 'Комедия' }, { id: 'adventure', label: 'Приключения' }] },
    ],
  },
  {
    id: 'adventure_bucket',
    emoji: '🎒',
    title: 'Список приключений',
    questions: [
      { id: 'ab1', type: 'text', text: 'Какое приключение из «списка мечты» ты хочешь сделать первым?' },
      { id: 'ab2', type: 'choice', text: 'Адреналин или спокойствие — что выбираешь?', options: [{ id: 'adrenaline', label: 'Адреналин — прыжок, дайвинг' }, { id: 'calm', label: 'Спокойствие — треккинг, кемпинг' }, { id: 'mix', label: 'Микс' }] },
      { id: 'ab3', type: 'text', text: 'Какое безумное приключение мы ещё не пробовали?' },
      { id: 'ab4', type: 'choice', text: 'Список желаний для нас — это...', options: [{ id: 'have', label: 'Уже есть список!' }, { id: 'make', label: 'Пора составить' }, { id: 'spontaneous', label: 'Спонтанно — без списков' }] },
    ],
  },
  {
    id: 'quiet_moments',
    emoji: '🤍',
    title: 'Тихие моменты',
    questions: [
      { id: 'qm1', type: 'choice', text: 'Молчание вместе — это...', options: [{ id: 'comfort', label: 'Комфорт и близость' }, { id: 'awkward', label: 'Иногда неловко' }, { id: 'rare', label: 'Редко — мы болтаем' }] },
      { id: 'qm2', type: 'text', text: 'Какой тихий момент с тобой ты бы сохранил(а) навсегда?' },
      { id: 'qm3', type: 'choice', text: 'Идеальный тихий вечер — это...', options: [{ id: 'read', label: 'Читать рядом' }, { id: 'cuddle', label: 'Просто обниматься' }, { id: 'nature', label: 'Смотреть в окно или на звёзды' }] },
      { id: 'qm4', type: 'text', text: 'Что ты чувствуешь, когда мы просто молчим, но рядом?' },
    ],
  },
  {
    id: 'cozy_evenings',
    emoji: '🍷',
    title: 'Уютные вечера',
    questions: [
      { id: 'ce1', type: 'image', text: 'Как провести вечер?', images: [{ id: 'wine_evening', label: 'Бокал вина и разговор', url: IMG.wine_evening }, { id: 'couch_movie', label: 'Плед и фильм', url: IMG.couch_movie }] },
      { id: 'ce2', type: 'choice', text: 'Вечер дома vs выход — что чаще?', options: [{ id: 'home', label: 'Дома — уют' }, { id: 'out', label: 'Выходим' }, { id: 'balance', label: '50/50' }] },
      { id: 'ce3', type: 'text', text: 'Какой уютный вечер с тобой — идеал?' },
      { id: 'ce4', type: 'choice', text: 'Что делает вечер «идеальным»?', options: [{ id: 'presence', label: 'Полное присутствие друг друга' }, { id: 'comfort', label: 'Комфорт — еда, плед, тишина' }, { id: 'surprise', label: 'Небольшой сюрприз' }] },
    ],
  },
];
