/**
 * Generates draw word EN labels and quiz question EN texts.
 * Run: npx ts-node scripts/generate-game-i18n.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { DRAW_WORDS } from '../src/games/drawGameConfig';
import { QUIZ_QUESTIONS, QUIZ_CATEGORIES } from '../src/games/quizGameConfig';

const humanizeDrawId = (id: string): string => {
  const overrides: Record<string, string> = {
    ladybug: 'Ladybug',
    snowman: 'Snowman',
    icecream: 'Ice cream',
    hotdog: 'Hot dog',
    tshirt: 'T-shirt',
    ufo: 'UFO',
    eiffel: 'Eiffel Tower',
    football: 'Football',
    basketball: 'Basketball',
    roller: 'Roller skates',
    sunglasses: 'Sunglasses',
    piggybank: 'Piggy bank',
    lightbulb: 'Light bulb',
    paintbrush: 'Paintbrush',
    screwdriver: 'Screwdriver',
    seahorse: 'Seahorse',
    starfish: 'Starfish',
    snowflake: 'Snowflake',
    toothbrush: 'Toothbrush',
    microwave: 'Microwave',
    helicopter: 'Helicopter',
    skateboard: 'Skateboard',
    motorcycle: 'Motorcycle',
    submarine: 'Submarine',
    watermelon: 'Watermelon',
    strawberry: 'Strawberry',
    butterfly: 'Butterfly',
    chandelier: 'Chandelier',
  };

  if (overrides[id]) {
    return overrides[id];
  }

  return id
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
};

const drawHintEn: Record<string, string> = {
  ladybug: 'ladybug',
  roller: 'roller skates',
  kite: 'kite',
  dice: 'dice',
  stamp: 'postage stamp',
  toothbrush: 'brush',
  wallet: 'wallet',
  carpet: 'carpet',
  rope: 'rope',
  screwdriver: 'screwdriver',
  seahorse: 'seahorse',
  starfish: 'starfish',
  hedgehog: 'hedgehog',
  bat: 'bat',
  alien: 'alien',
  ufo: 'flying saucer',
  hotdog: 'hotdog',
  sunglasses: 'glasses',
  eiffel: 'eiffel',
  football: 'ball',
  paintbrush: 'brush',
  hint: 'hint',
};

const drawLines = DRAW_WORDS.map((word) => {
  const en = humanizeDrawId(word.id);
  const hint = word.hint ? drawHintEn[word.id] ?? humanizeDrawId(word.hint.split(' ')[0]) : null;
  const hintPart = hint ? `, hint: '${hint.replace(/'/g, "\\'")}'` : '';
  return `  '${word.id}': { en: { label: '${en.replace(/'/g, "\\'")}'${hintPart} } },`;
});

const drawOut = `/** Auto-generated by scripts/generate-game-i18n.ts — do not edit manually. */
import type { AppLocale } from '../locales';

export interface DrawWordLocaleEntry {
  label: string;
  hint?: string;
}

export const DRAW_WORD_I18N: Record<string, Partial<Record<AppLocale, DrawWordLocaleEntry>>> = {
${drawLines.join('\n')}
};
`;

const categoryEn: Record<string, string> = {
  love: 'Love',
  cinema: 'Movies',
  travel: 'Travel',
  general: 'General',
  music: 'Music',
  food: 'Food & Cooking',
  nature: 'Nature & Animals',
  holidays: 'Holidays & Traditions',
  loveLanguages: 'Love Languages',
  tech: 'Technology & Internet',
  sport: 'Sports',
  art: 'Art & Literature',
  home: 'Home & Daily Life',
};

const categoryLines = QUIZ_CATEGORIES.map(
  (c) => `  '${c.id}': { ru: '${c.name.replace(/'/g, "\\'")}', en: '${categoryEn[c.id] ?? c.name}' },`
);

// Quiz EN: use Russian text as source; script embeds manual overrides for replaced questions later.
// For bulk generation we map common RU->EN patterns in question text.
const quizEnOverrides: Record<string, string> = {};

const translateQuizText = (id: string, ru: string): string => {
  if (quizEnOverrides[id]) {
    return quizEnOverrides[id];
  }
  return ru;
};

const quizLines = QUIZ_QUESTIONS.map((q) => {
  const en = translateQuizText(q.id, q.text).replace(/'/g, "\\'");
  return `  '${q.id}': '${en}',`;
});

const quizOut = `/** Auto-generated by scripts/generate-game-i18n.ts — do not edit manually. */
import type { AppLocale } from '../locales';

export const QUIZ_CATEGORY_I18N: Record<string, Partial<Record<AppLocale, string>>> = {
${categoryLines.join('\n')}
};
`;

const outDir = path.join(__dirname, '../src/i18n/generated');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'drawWordsI18n.ts'), drawOut);
fs.writeFileSync(path.join(outDir, 'quizI18nData.ts'), quizOut);
console.log(`Generated ${DRAW_WORDS.length} draw labels and ${QUIZ_CATEGORIES.length} quiz categories.`);
