/**
 * Writes ru/en quiz i18n maps from bilingual question sources.
 * Run: npx ts-node scripts/write-quiz-mc-i18n.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { QUIZ_CATEGORIES, QUIZ_QUESTION_SOURCES } from '../src/games/quizGameContent';

const escapeTs = (value: string) => value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const CATEGORY_I18N: Record<string, { ru: string; en: string; by?: string; uk?: string; es?: string; de?: string; fr?: string; pt?: string }> = {
  love: { ru: 'Любовь', en: 'Love', by: 'Каханне', uk: 'Любов', es: 'Amor', de: 'Liebe', fr: 'Amour', pt: 'Amor' },
  cinema: { ru: 'Кино', en: 'Movies', by: 'Кіно', uk: 'Кіно', es: 'Cine', de: 'Kino', fr: 'Cinéma', pt: 'Cinema' },
  travel: { ru: 'Путешествия', en: 'Travel', by: 'Падарожжы', uk: 'Подорожі', es: 'Viajes', de: 'Reisen', fr: 'Voyages', pt: 'Viagens' },
  general: { ru: 'Общее', en: 'General', by: 'Агульнае', uk: 'Загальне', es: 'General', de: 'Allgemein', fr: 'Général', pt: 'Geral' },
  music: { ru: 'Музыка', en: 'Music', by: 'Музыка', uk: 'Музика', es: 'Música', de: 'Musik', fr: 'Musique', pt: 'Música' },
  food: { ru: 'Еда и кухня', en: 'Food & Cooking', by: 'Ежа і кухня', uk: 'Їжа та кухня', es: 'Comida y cocina', de: 'Essen & Kochen', fr: 'Cuisine', pt: 'Comida e culinária' },
  nature: {
    ru: 'Наука и природа',
    en: 'Science & Nature',
    by: 'Навука і прырода',
    uk: 'Наука і природа',
    es: 'Ciencia y naturaleza',
    de: 'Wissenschaft & Natur',
    fr: 'Science et nature',
    pt: 'Ciência e natureza',
  },
  holidays: { ru: 'Праздники и традиции', en: 'Holidays & Traditions', by: 'Святы і традыцыі', uk: 'Свята та традиції', es: 'Fiestas y tradiciones', de: 'Feiertage & Traditionen', fr: 'Fêtes et traditions', pt: 'Festas e tradições' },
  loveLanguages: { ru: 'Языки любви', en: 'Love Languages', by: 'Мовы кахання', uk: 'Мови кохання', es: 'Lenguajes del amor', de: 'Liebessprachen', fr: "Langages de l'amour", pt: 'Linguagens do amor' },
  tech: { ru: 'Технологии и интернет', en: 'Technology & Internet', by: 'Тэхналогіі і інтэрнэт', uk: 'Технології та інтернет', es: 'Tecnología e internet', de: 'Technologie & Internet', fr: 'Technologie et internet', pt: 'Tecnologia e internet' },
  sport: { ru: 'Спорт', en: 'Sports', by: 'Спорт', uk: 'Спорт', es: 'Deportes', de: 'Sport', fr: 'Sports', pt: 'Esportes' },
  art: { ru: 'Искусство и литература', en: 'Art & Literature', by: 'Мастацтва і літаратура', uk: 'Мистецтво та література', es: 'Arte y literatura', de: 'Kunst & Literatur', fr: 'Art et littérature', pt: 'Arte e literatura' },
  history: { ru: 'История', en: 'History', by: 'Гісторыя', uk: 'Історія', es: 'Historia', de: 'Geschichte', fr: 'Histoire', pt: 'História' },
  mythology: { ru: 'Мифология', en: 'Mythology', by: 'Міфалогія', uk: 'Міфологія', es: 'Mitología', de: 'Mythologie', fr: 'Mythologie', pt: 'Mitologia' },
  animals: { ru: 'Животные', en: 'Animals', by: 'Жывёлы', uk: 'Тварини', es: 'Animales', de: 'Tiere', fr: 'Animaux', pt: 'Animais' },
  series: { ru: 'Сериалы', en: 'TV Series', by: 'Серыялы', uk: 'Серіали', es: 'Series', de: 'Serien', fr: 'Séries', pt: 'Séries' },
  videoGames: { ru: 'Видеоигры', en: 'Video Games', by: 'Відэагульні', uk: 'Відеоігри', es: 'Videojuegos', de: 'Videospiele', fr: 'Jeux vidéo', pt: 'Videojogos' },
};

const formatLocaleRecord = (record: Record<string, string | undefined>) => {
  const parts = Object.entries(record)
    .filter(([, value]) => Boolean(value))
    .map(([locale, value]) => `${locale}: '${escapeTs(value as string)}'`);
  return `{ ${parts.join(', ')} }`;
};

const outDir = path.join(__dirname, '../src/i18n/generated');

const writeCategoryFile = () => {
  const lines = QUIZ_CATEGORIES.map((category) => {
    const localized = CATEGORY_I18N[category.id];
    if (!localized) {
      throw new Error(`Missing category translations for ${category.id}`);
    }
    return `  '${category.id}': ${formatLocaleRecord(localized)},`;
  });

  fs.writeFileSync(
    path.join(outDir, 'quizI18nData.ts'),
    `/** Auto-generated by scripts/write-quiz-mc-i18n.ts — do not edit manually. */
import type { AppLocale } from '../locales';

export const QUIZ_CATEGORY_I18N: Record<string, Partial<Record<AppLocale, string>>> = {
${lines.join('\n')}
};
`
  );
};

const writeQuestionFile = () => {
  const lines = QUIZ_QUESTION_SOURCES.map(
    (question) =>
      `  '${question.id}': { ru: '${escapeTs(question.text)}', en: '${escapeTs(question.textEn)}' },`
  );

  fs.writeFileSync(
    path.join(outDir, 'quizQuestionsI18n.ts'),
    `/** Auto-generated by scripts/write-quiz-mc-i18n.ts — do not edit manually. */
import type { AppLocale } from '../locales';

export const QUIZ_QUESTION_I18N: Record<string, Partial<Record<AppLocale, string>>> = {
${lines.join('\n')}
};
`
  );
};

const writeOptionFile = () => {
  const lines = QUIZ_QUESTION_SOURCES.flatMap((question) =>
    question.options.map(
      (option) =>
        `  '${question.id}:${option.id}': { ru: '${escapeTs(option.text)}', en: '${escapeTs(option.textEn)}' },`
    )
  );

  fs.writeFileSync(
    path.join(outDir, 'quizOptionsI18n.ts'),
    `/** Auto-generated by scripts/write-quiz-mc-i18n.ts — do not edit manually. */
import type { AppLocale } from '../locales';

export const QUIZ_OPTION_I18N: Record<string, Partial<Record<AppLocale, string>>> = {
${lines.join('\n')}
};
`
  );
};

fs.mkdirSync(outDir, { recursive: true });
writeCategoryFile();
writeQuestionFile();
writeOptionFile();
console.log(`Wrote i18n for ${QUIZ_QUESTION_SOURCES.length} questions.`);
