export const DRAW_LOBBY_COUNTDOWN_SEC = 3;
export const DRAW_ROUND_DRAWING_SEC = 90;
export const DRAW_ROUND_GUESSING_SEC = 60;
export const DRAW_MAX_ROUND_POINTS = 1000;
export const DRAW_MAX_SCORED_ROUNDS_PER_DAY = 10;
export const DRAW_MAX_GUESS_ATTEMPTS_PER_ROUND = 40;

export interface DrawWord {
  id: string;
  label: string;
  hint?: string;
}

export const DRAW_WORDS: DrawWord[] = [
  { id: 'cat', label: 'Кот' },
  { id: 'dog', label: 'Собака' },
  { id: 'sun', label: 'Солнце' },
  { id: 'house', label: 'Дом' },
  { id: 'tree', label: 'Дерево' },
  { id: 'car', label: 'Машина' },
  { id: 'heart', label: 'Сердце' },
  { id: 'flower', label: 'Цветок' },
  { id: 'pizza', label: 'Пицца' },
  { id: 'umbrella', label: 'Зонт' },
  { id: 'moon', label: 'Луна' },
  { id: 'fish', label: 'Рыба' },
  { id: 'book', label: 'Книга' },
  { id: 'phone', label: 'Телефон' },
  { id: 'cake', label: 'Торт' },
  { id: 'star', label: 'Звезда' },
  { id: 'bird', label: 'Птица' },
  { id: 'apple', label: 'Яблоко' },
  { id: 'boat', label: 'Лодка' },
  { id: 'clock', label: 'Часы' },
  { id: 'camera', label: 'Фотоаппарат' },
  { id: 'guitar', label: 'Гитара' },
  { id: 'snowman', label: 'Снеговик' },
  { id: 'bicycle', label: 'Велосипед' },
  { id: 'rainbow', label: 'Радуга' },
  { id: 'horse', label: 'Лошадь' },
  { id: 'elephant', label: 'Слон' },
  { id: 'butterfly', label: 'Бабочка' },
  { id: 'mountain', label: 'Гора' },
  { id: 'beach', label: 'Пляж' },
  { id: 'cloud', label: 'Облако' },
  { id: 'fire', label: 'Огонь' },
  { id: 'key', label: 'Ключ' },
  { id: 'glasses', label: 'Очки' },
  { id: 'hat', label: 'Шляпа' },
  { id: 'shoe', label: 'Ботинок' },
  { id: 'table', label: 'Стол' },
  { id: 'chair', label: 'Стул' },
  { id: 'lamp', label: 'Лампа' },
  { id: 'window', label: 'Окно' },
  { id: 'door', label: 'Дверь' },
  { id: 'bridge', label: 'Мост' },
  { id: 'castle', label: 'Замок' },
  { id: 'rocket', label: 'Ракета' },
  { id: 'planet', label: 'Планета' },
  { id: 'robot', label: 'Робот' },
  { id: 'dragon', label: 'Дракон' },
  { id: 'ghost', label: 'Привидение' },
  { id: 'pirate', label: 'Пират' },
  { id: 'crown', label: 'Корона' },
  { id: 'sword', label: 'Меч' },
  { id: 'balloon', label: 'Шарик' },
  { id: 'icecream', label: 'Мороженое' },
  { id: 'coffee', label: 'Кофе' },
  { id: 'bread', label: 'Хлеб' },
  { id: 'cheese', label: 'Сыр' },
  { id: 'banana', label: 'Банан' },
  { id: 'orange', label: 'Апельсин' },
  { id: 'grape', label: 'Виноград' },
  { id: 'carrot', label: 'Морковь' },
  { id: 'mushroom', label: 'Гриб' },
  { id: 'honey', label: 'Мёд' },
  { id: 'cookie', label: 'Печенье' },
  { id: 'soup', label: 'Суп' },
  { id: 'tea', label: 'Чай' },
  { id: 'milk', label: 'Молоко' },
  { id: 'egg', label: 'Яйцо' },
  { id: 'snake', label: 'Змея' },
  { id: 'frog', label: 'Лягушка' },
  { id: 'rabbit', label: 'Кролик' },
  { id: 'bear', label: 'Медведь' },
  { id: 'wolf', label: 'Волк' },
  { id: 'fox', label: 'Лиса' },
  { id: 'owl', label: 'Сова' },
  { id: 'penguin', label: 'Пингвин' },
  { id: 'dolphin', label: 'Дельфин' },
  { id: 'whale', label: 'Кит' },
  { id: 'crab', label: 'Краб' },
  { id: 'snail', label: 'Улитка' },
  { id: 'bee', label: 'Пчела' },
  { id: 'ladybug', label: 'Божья коровка', hint: 'коровка' },
  { id: 'spider', label: 'Паук' },
  { id: 'cactus', label: 'Кактус' },
  { id: 'palm', label: 'Пальма' },
  { id: 'forest', label: 'Лес' },
  { id: 'river', label: 'Река' },
  { id: 'waterfall', label: 'Водопад' },
  { id: 'island', label: 'Остров' },
  { id: 'volcano', label: 'Вулкан' },
  { id: 'desert', label: 'Пустыня' },
  { id: 'snowflake', label: 'Снежинка' },
  { id: 'lightning', label: 'Молния' },
  { id: 'tornado', label: 'Торнадо' },
  { id: 'compass', label: 'Компас' },
  { id: 'map', label: 'Карта' },
  { id: 'suitcase', label: 'Чемодан' },
  { id: 'airplane', label: 'Самолёт' },
  { id: 'train', label: 'Поезд' },
  { id: 'bus', label: 'Автобус' },
  { id: 'helicopter', label: 'Вертолёт' },
  { id: 'ship', label: 'Корабль' },
  { id: 'submarine', label: 'Подлодка' },
  { id: 'motorcycle', label: 'Мотоцикл' },
  { id: 'skateboard', label: 'Скейтборд' },
  { id: 'roller', label: 'Ролики', hint: 'роликовые коньки' },
  { id: 'ski', label: 'Лыжи' },
  { id: 'snowboard', label: 'Сноуборд' },
  { id: 'ball', label: 'Мяч' },
  { id: 'football', label: 'Футбол', hint: 'мяч' },
  { id: 'basketball', label: 'Баскетбол' },
  { id: 'tennis', label: 'Теннис' },
  { id: 'chess', label: 'Шахматы' },
  { id: 'puzzle', label: 'Пазл' },
  { id: 'dice', label: 'Кубик', hint: 'игральный кубик' },
  { id: 'kite', label: 'Воздушный змей', hint: 'змей' },
  { id: 'gift', label: 'Подарок' },
  { id: 'candle', label: 'Свеча' },
  { id: 'ring', label: 'Кольцо' },
  { id: 'necklace', label: 'Ожерелье' },
  { id: 'watch', label: 'Часы' },
  { id: 'backpack', label: 'Рюкзак' },
  { id: 'scissors', label: 'Ножницы' },
  { id: 'hammer', label: 'Молоток' },
  { id: 'paintbrush', label: 'Кисть', hint: 'кисточка' },
  { id: 'pencil', label: 'Карандаш' },
  { id: 'pen', label: 'Ручка' },
  { id: 'notebook', label: 'Тетрадь' },
  { id: 'envelope', label: 'Конверт' },
  { id: 'stamp', label: 'Марка', hint: 'почтовая марка' },
  { id: 'toothbrush', label: 'Зубная щётка', hint: 'щетка' },
  { id: 'soap', label: 'Мыло' },
  { id: 'towel', label: 'Полотенце' },
  { id: 'bathtub', label: 'Ванна' },
  { id: 'toilet', label: 'Унитаз' },
  { id: 'mirror', label: 'Зеркало' },
  { id: 'bed', label: 'Кровать' },
  { id: 'pillow', label: 'Подушка' },
  { id: 'blanket', label: 'Одеяло' },
  { id: 'fridge', label: 'Холодильник' },
  { id: 'microwave', label: 'Микроволновка' },
  { id: 'kettle', label: 'Чайник' },
  { id: 'cup', label: 'Чашка' },
  { id: 'plate', label: 'Тарелка' },
  { id: 'fork', label: 'Вилка' },
  { id: 'spoon', label: 'Ложка' },
  { id: 'pot', label: 'Кастрюля' },
  { id: 'pan', label: 'Сковорода' },
  { id: 'lion', label: 'Лев' },
  { id: 'tiger', label: 'Тигр' },
  { id: 'zebra', label: 'Зебра' },
  { id: 'giraffe', label: 'Жираф' },
  { id: 'monkey', label: 'Обезьяна' },
  { id: 'kangaroo', label: 'Кенгуру' },
  { id: 'crocodile', label: 'Крокодил' },
  { id: 'turtle', label: 'Черепаха' },
  { id: 'chicken', label: 'Курица' },
  { id: 'pig', label: 'Свинья' },
  { id: 'cow', label: 'Корова' },
  { id: 'sheep', label: 'Овца' },
  { id: 'goat', label: 'Коза' },
  { id: 'duck', label: 'Утка' },
  { id: 'parrot', label: 'Попугай' },
  { id: 'eagle', label: 'Орёл', hint: 'орел' },
  { id: 'shark', label: 'Акула' },
  { id: 'octopus', label: 'Осьминог' },
  { id: 'jellyfish', label: 'Медуза' },
  { id: 'seahorse', label: 'Морской конёк', hint: 'конек' },
  { id: 'starfish', label: 'Морская звезда', hint: 'звезда' },
  { id: 'flamingo', label: 'Фламинго' },
  { id: 'hedgehog', label: 'Ёжик', hint: 'еж' },
  { id: 'squirrel', label: 'Белка' },
  { id: 'hamster', label: 'Хомяк' },
  { id: 'chameleon', label: 'Хамелеон' },
  { id: 'lizard', label: 'Ящерица' },
  { id: 'bat', label: 'Летучая мышь', hint: 'мышь' },
  { id: 'ant', label: 'Муравей' },
  { id: 'caterpillar', label: 'Гусеница' },
  { id: 'watermelon', label: 'Арбуз' },
  { id: 'strawberry', label: 'Клубника' },
  { id: 'cherry', label: 'Вишня' },
  { id: 'lemon', label: 'Лимон' },
  { id: 'pear', label: 'Груша' },
  { id: 'peach', label: 'Персик' },
  { id: 'plum', label: 'Слива' },
  { id: 'corn', label: 'Кукуруза' },
  { id: 'tomato', label: 'Помидор' },
  { id: 'cucumber', label: 'Огурец' },
  { id: 'onion', label: 'Лук' },
  { id: 'garlic', label: 'Чеснок' },
  { id: 'pepper', label: 'Перец' },
  { id: 'cabbage', label: 'Капуста' },
  { id: 'broccoli', label: 'Брокколи' },
  { id: 'burger', label: 'Бургер' },
  { id: 'hotdog', label: 'Хот-дог', hint: 'хотдог' },
  { id: 'sandwich', label: 'Бутерброд' },
  { id: 'salad', label: 'Салат' },
  { id: 'donut', label: 'Пончик' },
  { id: 'cupcake', label: 'Кекс' },
  { id: 'lollipop', label: 'Леденец' },
  { id: 'chocolate', label: 'Шоколад' },
  { id: 'candy', label: 'Конфета' },
  { id: 'juice', label: 'Сок' },
  { id: 'water', label: 'Вода' },
  { id: 'wine', label: 'Вино' },
  { id: 'champagne', label: 'Шампанское' },
  { id: 'tent', label: 'Палатка' },
  { id: 'campfire', label: 'Костёр', hint: 'костер' },
  { id: 'lantern', label: 'Фонарь' },
  { id: 'flashlight', label: 'Фонарик' },
  { id: 'fireplace', label: 'Камин' },
  { id: 'chimney', label: 'Труба' },
  { id: 'fence', label: 'Забор' },
  { id: 'fountain', label: 'Фонтан' },
  { id: 'statue', label: 'Статуя' },
  { id: 'lighthouse', label: 'Маяк' },
  { id: 'windmill', label: 'Мельница' },
  { id: 'barn', label: 'Амбар' },
  { id: 'tractor', label: 'Трактор' },
  { id: 'ambulance', label: 'Скорая помощь', hint: 'скорая' },
  { id: 'taxi', label: 'Такси' },
  { id: 'tram', label: 'Трамвай' },
  { id: 'scooter', label: 'Самокат' },
  { id: 'anchor', label: 'Якорь' },
  { id: 'treasure', label: 'Сокровище' },
  { id: 'chest', label: 'Сундук' },
  { id: 'wizard', label: 'Волшебник' },
  { id: 'fairy', label: 'Фея' },
  { id: 'unicorn', label: 'Единорог' },
  { id: 'mermaid', label: 'Русалка' },
  { id: 'superhero', label: 'Супергерой' },
  { id: 'ninja', label: 'Ниндзя' },
  { id: 'astronaut', label: 'Космонавт' },
  { id: 'alien', label: 'Пришелец', hint: 'инопланетянин' },
  { id: 'ufo', label: 'НЛО', hint: 'тарелка' },
  { id: 'microscope', label: 'Микроскоп' },
  { id: 'telescope', label: 'Телескоп' },
  { id: 'magnet', label: 'Магнит' },
  { id: 'lightbulb', label: 'Лампочка' },
  { id: 'sunglasses', label: 'Солнечные очки', hint: 'очки' },
  { id: 'scarf', label: 'Шарф' },
  { id: 'gloves', label: 'Перчатки' },
  { id: 'boots', label: 'Сапоги' },
  { id: 'dress', label: 'Платье' },
  { id: 'pants', label: 'Штаны' },
  { id: 'shirt', label: 'Рубашка' },
  { id: 'tie', label: 'Галстук' },
  { id: 'handbag', label: 'Сумка' },
  { id: 'wallet', label: 'Кошелёк', hint: 'кошелек' },
  { id: 'coin', label: 'Монета' },
  { id: 'piggybank', label: 'Копилка' },
  { id: 'hospital', label: 'Больница' },
  { id: 'school', label: 'Школа' },
  { id: 'library', label: 'Библиотека' },
  { id: 'museum', label: 'Музей' },
  { id: 'church', label: 'Церковь' },
  { id: 'pyramid', label: 'Пирамида' },
  { id: 'eiffel', label: 'Эйфелева башня', hint: 'эйфелева' },
  { id: 'globe', label: 'Глобус' },
  { id: 'thermometer', label: 'Термометр' },
  { id: 'bandage', label: 'Пластырь' },
  { id: 'drum', label: 'Барабан' },
  { id: 'violin', label: 'Скрипка' },
  { id: 'flute', label: 'Флейта' },
  { id: 'piano', label: 'Пианино' },
  { id: 'microphone', label: 'Микрофон' },
  { id: 'popcorn', label: 'Попкорн' },
  { id: 'palette', label: 'Палитра' },
  { id: 'easel', label: 'Мольберт' },
  { id: 'vase', label: 'Ваза' },
  { id: 'carpet', label: 'Ковёр', hint: 'ковер' },
  { id: 'curtain', label: 'Штора' },
  { id: 'sofa', label: 'Диван' },
  { id: 'wardrobe', label: 'Шкаф' },
  { id: 'ladder', label: 'Лестница' },
  { id: 'screwdriver', label: 'Отвёртка', hint: 'отвертка' },
  { id: 'saw', label: 'Пила' },
  { id: 'rope', label: 'Верёвка', hint: 'веревка' },
  { id: 'chain', label: 'Цепь' },
  { id: 'safe', label: 'Сейф' },
  { id: 'bell', label: 'Колокол' },
  { id: 'alarm', label: 'Будильник' },
  { id: 'calendar', label: 'Календарь' },
  { id: 'hourglass', label: 'Песочные часы' },
  { id: 'newspaper', label: 'Газета' },
  { id: 'postcard', label: 'Открытка' },
  { id: 'flag', label: 'Флаг' },
  { id: 'fireworks', label: 'Фейерверк' },
  { id: 'pumpkin', label: 'Тыква' },
  { id: 'witch', label: 'Ведьма' },
  { id: 'vampire', label: 'Вампир' },
  { id: 'skeleton', label: 'Скелет' },
  { id: 'zombie', label: 'Зомби' },
  { id: 'mummy', label: 'Мумия' },
  { id: 'broom', label: 'Метла' },
  { id: 'potion', label: 'Зелье' },
  { id: 'crystal', label: 'Кристалл' },
  { id: 'diamond', label: 'Бриллиант' },
  { id: 'pearl', label: 'Жемчуг' },
  { id: 'earring', label: 'Серьги' },
  { id: 'bracelet', label: 'Браслет' },
];

export const getDrawWord = (wordId: string): DrawWord | undefined =>
  DRAW_WORDS.find((word) => word.id === wordId);

export const pickRandomDrawWord = (usedWordIds: string[]): DrawWord | null => {
  if (DRAW_WORDS.length === 0) {
    return null;
  }

  const unused = DRAW_WORDS.filter((word) => !usedWordIds.includes(word.id));
  const pool = unused.length > 0 ? unused : DRAW_WORDS;
  return pool[Math.floor(Math.random() * pool.length)];
};

/** После выбора слова: при исчерпании пула начинаем цикл заново. */
export const buildUsedWordIdsAfterPick = (usedWordIds: string[], pickedWordId: string): string[] => {
  const poolExhausted =
    DRAW_WORDS.length > 0 && DRAW_WORDS.every((word) => usedWordIds.includes(word.id));

  if (poolExhausted) {
    return [pickedWordId];
  }

  if (usedWordIds.includes(pickedWordId)) {
    return usedWordIds;
  }

  return [...usedWordIds, pickedWordId];
};

export const normalizeDrawGuess = (value: string) =>
  value
    .trim()
    .toLowerCase()
    .replace(/ё/g, 'е')
    .replace(/\s+/g, ' ');

export const isDrawGuessCorrect = (guess: string, word: DrawWord) => {
  const normalized = normalizeDrawGuess(guess);
  const label = normalizeDrawGuess(word.label);
  return normalized === label || (word.hint ? normalized === normalizeDrawGuess(word.hint) : false);
};

export const calculateDrawGuessScore = (secondsTaken: number): number => {
  const maxSec = DRAW_ROUND_DRAWING_SEC;
  const clamped = Math.max(0, Math.min(maxSec, secondsTaken));
  const score = Math.round(DRAW_MAX_ROUND_POINTS * (1 - clamped / maxSec));
  return Math.max(50, Math.min(DRAW_MAX_ROUND_POINTS, score));
};
