import type { QuizQuestionSource } from './quizGameTypes';

export const QUIZ_QUESTIONS_CUSTOM_SOURCE: QuizQuestionSource[] = [
  {
    id: 'love-1',
    categoryId: 'love',
    text: 'Какой праздник отмечают 14 февраля?',
    textEn: 'Which holiday is celebrated on February 14?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'День святого Валентина', textEn: "Valentine's Day" },
      { id: 'b', text: 'Хэллоуин', textEn: 'Halloween' },
      { id: 'c', text: 'Пасха', textEn: 'Easter' },
      { id: 'd', text: 'Международный женский день', textEn: "International Women's Day" },
    ],
  },
  {
    id: 'love-2',
    categoryId: 'love',
    text: 'Какой цвет чаще всего ассоциируют с романтикой?',
    textEn: 'Which color is most often associated with romance?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Красный', textEn: 'Red' },
      { id: 'b', text: 'Зелёный', textEn: 'Green' },
      { id: 'c', text: 'Серый', textEn: 'Gray' },
      { id: 'd', text: 'Коричневый', textEn: 'Brown' },
    ],
  },
  {
    id: 'love-3',
    categoryId: 'love',
    text: 'Какой город называют «городом влюблённых»?',
    textEn: 'Which city is often called the city of love?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Париж', textEn: 'Paris' },
      { id: 'b', text: 'Берлин', textEn: 'Berlin' },
      { id: 'c', text: 'Осло', textEn: 'Oslo' },
      { id: 'd', text: 'Дубай', textEn: 'Dubai' },
    ],
  },
  {
    id: 'love-4',
    categoryId: 'love',
    text: 'Как называется годовщина 50 лет брака?',
    textEn: 'What is the name of a 50th wedding anniversary?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Золотая свадьба', textEn: 'Golden anniversary' },
      { id: 'b', text: 'Серебряная свадьба', textEn: 'Silver anniversary' },
      { id: 'c', text: 'Ситцевая свадьба', textEn: 'Cotton anniversary' },
      { id: 'd', text: 'Бумажная свадьба', textEn: 'Paper anniversary' },
    ],
  },
  {
    id: 'love-5',
    categoryId: 'love',
    text: 'Как называется годовщина 25 лет брака?',
    textEn: 'What is the name of a 25th wedding anniversary?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Серебряная свадьба', textEn: 'Silver anniversary' },
      { id: 'b', text: 'Золотая свадьба', textEn: 'Golden anniversary' },
      { id: 'c', text: 'Рубиновая свадьба', textEn: 'Ruby anniversary' },
      { id: 'd', text: 'Бриллиантовая свадьба', textEn: 'Diamond anniversary' },
    ],
  },
  {
    id: 'love-6',
    categoryId: 'love',
    text: 'Как называется традиционная поездка сразу после свадьбы?',
    textEn: 'What is the traditional trip right after a wedding called?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Медовый месяц', textEn: 'Honeymoon' },
      { id: 'b', text: 'Командировка', textEn: 'Business trip' },
      { id: 'c', text: 'Паломничество', textEn: 'Pilgrimage' },
      { id: 'd', text: 'Экспедиция', textEn: 'Expedition' },
    ],
  },
  {
    id: 'love-7',
    categoryId: 'love',
    text: 'Какой цвет свадебного платья принят в западной традиции?',
    textEn: 'Which wedding-dress color is traditional in Western culture?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Белый', textEn: 'White' },
      { id: 'b', text: 'Чёрный', textEn: 'Black' },
      { id: 'c', text: 'Зелёный', textEn: 'Green' },
      { id: 'd', text: 'Оранжевый', textEn: 'Orange' },
    ],
  },
  {
    id: 'love-8',
    categoryId: 'love',
    text: 'Как зовут римского бога любви?',
    textEn: 'Who is the Roman god of love?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Купидон', textEn: 'Cupid' },
      { id: 'b', text: 'Зевс', textEn: 'Zeus' },
      { id: 'c', text: 'Марс', textEn: 'Mars' },
      { id: 'd', text: 'Посейдон', textEn: 'Poseidon' },
    ],
  },
  {
    id: 'love-9',
    categoryId: 'love',
    text: 'Под каким растением традиционно целуются на Рождество?',
    textEn: 'Under which plant do people traditionally kiss at Christmas?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Омела', textEn: 'Mistletoe' },
      { id: 'b', text: 'Кактус', textEn: 'Cactus' },
      { id: 'c', text: 'Папоротник', textEn: 'Fern' },
      { id: 'd', text: 'Бамбук', textEn: 'Bamboo' },
    ],
  },
  {
    id: 'love-10',
    categoryId: 'love',
    text: 'Какой цветок чаще всего считают символом любви?',
    textEn: 'Which flower is most often seen as a symbol of love?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Роза', textEn: 'Rose' },
      { id: 'b', text: 'Одуванчик', textEn: 'Dandelion' },
      { id: 'c', text: 'Кактус', textEn: 'Cactus' },
      { id: 'd', text: 'Крапива', textEn: 'Nettle' },
    ],
  },
  {
    id: 'love-11',
    categoryId: 'love',
    text: 'Как называется годовщина первого года брака?',
    textEn: 'What is the name of a first wedding anniversary?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Ситцевая свадьба', textEn: 'Cotton anniversary' },
      { id: 'b', text: 'Золотая свадьба', textEn: 'Golden anniversary' },
      { id: 'c', text: 'Серебряная свадьба', textEn: 'Silver anniversary' },
      { id: 'd', text: 'Бриллиантовая свадьба', textEn: 'Diamond anniversary' },
    ],
  },
  {
    id: 'love-12',
    categoryId: 'love',
    text: 'Как называется годовщина 60 лет брака?',
    textEn: 'What is the name of a 60th wedding anniversary?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Бриллиантовая свадьба', textEn: 'Diamond anniversary' },
      { id: 'b', text: 'Ситцевая свадьба', textEn: 'Cotton anniversary' },
      { id: 'c', text: 'Оловянная свадьба', textEn: 'Tin anniversary' },
      { id: 'd', text: 'Бумажная свадьба', textEn: 'Paper anniversary' },
    ],
  },
  {
    id: 'love-13',
    categoryId: 'love',
    text: 'На каком пальце традиционно носят обручальное кольцо?',
    textEn: 'On which finger is a wedding ring traditionally worn?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Безымянный', textEn: 'Ring finger' },
      { id: 'b', text: 'Большой', textEn: 'Thumb' },
      { id: 'c', text: 'Мизинец', textEn: 'Little finger' },
      { id: 'd', text: 'Указательный', textEn: 'Index finger' },
    ],
  },
  {
    id: 'love-14',
    categoryId: 'love',
    text: 'Как называется вечеринка невесты перед свадьбой?',
    textEn: "What is the bride's party before the wedding called?",
    correctId: 'a',
    options: [
      { id: 'a', text: 'Девичник', textEn: 'Bachelorette party' },
      { id: 'b', text: 'Мальчишник', textEn: 'Bachelor party' },
      { id: 'c', text: 'Выпускной', textEn: 'Graduation party' },
      { id: 'd', text: 'Корпоратив', textEn: 'Office party' },
    ],
  },
  {
    id: 'love-15',
    categoryId: 'love',
    text: 'Как называется вечеринка жениха перед свадьбой?',
    textEn: "What is the groom's party before the wedding called?",
    correctId: 'a',
    options: [
      { id: 'a', text: 'Мальчишник', textEn: 'Bachelor party' },
      { id: 'b', text: 'Девичник', textEn: 'Bachelorette party' },
      { id: 'c', text: 'Юбилей', textEn: 'Anniversary party' },
      { id: 'd', text: 'Капустник', textEn: 'Sketch night' },
    ],
  },
  {
    id: 'love-16',
    categoryId: 'love',
    text: 'Как называется обещание пожениться?',
    textEn: 'What is a formal promise to marry called?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Помолвка', textEn: 'Engagement' },
      { id: 'b', text: 'Развод', textEn: 'Divorce' },
      { id: 'c', text: 'Опека', textEn: 'Guardianship' },
      { id: 'd', text: 'Ипотека', textEn: 'Mortgage' },
    ],
  },
  {
    id: 'love-17',
    categoryId: 'love',
    text: 'Как зовут греческую богиню любви?',
    textEn: 'Who is the Greek goddess of love?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Афродита', textEn: 'Aphrodite' },
      { id: 'b', text: 'Афина', textEn: 'Athena' },
      { id: 'c', text: 'Гера', textEn: 'Hera' },
      { id: 'd', text: 'Артемида', textEn: 'Artemis' },
    ],
  },
  {
    id: 'love-18',
    categoryId: 'love',
    text: 'Что невеста традиционно бросает незамужним подругам?',
    textEn: 'What does the bride traditionally toss to unmarried friends?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Букет', textEn: 'Bouquet' },
      { id: 'b', text: 'Туфлю', textEn: 'Shoe' },
      { id: 'c', text: 'Кольцо', textEn: 'Ring' },
      { id: 'd', text: 'Фата', textEn: 'Veil' },
    ],
  },
  {
    id: 'love-19',
    categoryId: 'love',
    text: 'Кто традиционно ведёт невесту к алтарю?',
    textEn: 'Who traditionally walks the bride down the aisle?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Отец', textEn: 'Father' },
      { id: 'b', text: 'Судья', textEn: 'Judge' },
      { id: 'c', text: 'Фотограф', textEn: 'Photographer' },
      { id: 'd', text: 'Диджей', textEn: 'DJ' },
    ],
  },
  {
    id: 'love-20',
    categoryId: 'love',
    text: 'Как называется годовщина 40 лет брака?',
    textEn: 'What is the name of a 40th wedding anniversary?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Рубиновая свадьба', textEn: 'Ruby anniversary' },
      { id: 'b', text: 'Ситцевая свадьба', textEn: 'Cotton anniversary' },
      { id: 'c', text: 'Бумажная свадьба', textEn: 'Paper anniversary' },
      { id: 'd', text: 'Оловянная свадьба', textEn: 'Tin anniversary' },
    ],
  },
  {
    id: 'loveLanguages-1',
    categoryId: 'loveLanguages',
    text: 'Сколько языков любви в модели Гэри Чепмена?',
    textEn: "How many love languages are there in Gary Chapman's model?",
    correctId: 'a',
    options: [
      { id: 'a', text: '5', textEn: '5' },
      { id: 'b', text: '3', textEn: '3' },
      { id: 'c', text: '7', textEn: '7' },
      { id: 'd', text: '12', textEn: '12' },
    ],
  },
  {
    id: 'loveLanguages-3',
    categoryId: 'loveLanguages',
    text: 'Держаться за руки — какой язык любви?',
    textEn: 'Holding hands is an example of which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Физическое прикосновение', textEn: 'Physical touch' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Слова поддержки', textEn: 'Words of affirmation' },
      { id: 'd', text: 'Помощь', textEn: 'Acts of service' },
    ],
  },
  {
    id: 'loveLanguages-4',
    categoryId: 'loveLanguages',
    text: 'Комплимент партнёру — какой язык любви?',
    textEn: 'A compliment to your partner is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Слова поддержки', textEn: 'Words of affirmation' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Физическое прикосновение', textEn: 'Physical touch' },
      { id: 'd', text: 'Помощь', textEn: 'Acts of service' },
    ],
  },
  {
    id: 'loveLanguages-5',
    categoryId: 'loveLanguages',
    text: 'Приготовить завтрак партнёру — какой язык любви?',
    textEn: 'Cooking breakfast for your partner is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Качественное время', textEn: 'Quality time' },
      { id: 'd', text: 'Физическое прикосновение', textEn: 'Physical touch' },
    ],
  },
  {
    id: 'loveLanguages-6',
    categoryId: 'loveLanguages',
    text: 'Неожиданный подарок «просто так» — какой язык любви?',
    textEn: 'An unexpected gift for no special reason is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'b', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'c', text: 'Качественное время', textEn: 'Quality time' },
      { id: 'd', text: 'Слова поддержки', textEn: 'Words of affirmation' },
    ],
  },
  {
    id: 'loveLanguages-7',
    categoryId: 'loveLanguages',
    text: 'Ужин вдвоём без телефонов — какой язык любви?',
    textEn: 'Dinner together with phones away is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Качественное время', textEn: 'Quality time' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'd', text: 'Физическое прикосновение', textEn: 'Physical touch' },
    ],
  },
  {
    id: 'loveLanguages-8',
    categoryId: 'loveLanguages',
    text: 'Обнять при встрече — какой язык любви?',
    textEn: 'A hug when you meet is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Физическое прикосновение', textEn: 'Physical touch' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'd', text: 'Качественное время', textEn: 'Quality time' },
    ],
  },
  {
    id: 'loveLanguages-9',
    categoryId: 'loveLanguages',
    text: 'Сказать «я горжусь тобой» — какой язык любви?',
    textEn: 'Saying “I am proud of you” is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Слова поддержки', textEn: 'Words of affirmation' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'd', text: 'Качественное время', textEn: 'Quality time' },
    ],
  },
  {
    id: 'loveLanguages-10',
    categoryId: 'loveLanguages',
    text: 'Починить сломанную вещь для партнёра — какой язык любви?',
    textEn: 'Fixing something broken for your partner is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Слова поддержки', textEn: 'Words of affirmation' },
      { id: 'd', text: 'Физическое прикосновение', textEn: 'Physical touch' },
    ],
  },
  {
    id: 'loveLanguages-11',
    categoryId: 'loveLanguages',
    text: 'Слушать партнёра, не перебивая и не глядя в телефон, — какой язык любви?',
    textEn: 'Listening without interrupting or checking a phone is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Качественное время', textEn: 'Quality time' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'd', text: 'Физическое прикосновение', textEn: 'Physical touch' },
    ],
  },
  {
    id: 'loveLanguages-12',
    categoryId: 'loveLanguages',
    text: 'Массаж плеч после трудного дня — какой язык любви?',
    textEn: 'A shoulder massage after a hard day is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Физическое прикосновение', textEn: 'Physical touch' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'd', text: 'Слова поддержки', textEn: 'Words of affirmation' },
    ],
  },
  {
    id: 'loveLanguages-13',
    categoryId: 'loveLanguages',
    text: 'Короткая записка «спасибо, что ты есть» — какой язык любви?',
    textEn: 'A short note saying “thank you for being you” is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Слова поддержки', textEn: 'Words of affirmation' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Качественное время', textEn: 'Quality time' },
      { id: 'd', text: 'Помощь', textEn: 'Acts of service' },
    ],
  },
  {
    id: 'loveLanguages-14',
    categoryId: 'loveLanguages',
    text: 'Забрать партнёра с работы, чтобы ему не ехать самому, — какой язык любви?',
    textEn: 'Picking your partner up from work so they do not commute alone is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Слова поддержки', textEn: 'Words of affirmation' },
      { id: 'd', text: 'Физическое прикосновение', textEn: 'Physical touch' },
    ],
  },
  {
    id: 'loveLanguages-15',
    categoryId: 'loveLanguages',
    text: 'Купить любимый чай партнёра без повода — какой язык любви?',
    textEn: "Buying your partner's favorite tea for no special reason is which love language?",
    correctId: 'a',
    options: [
      { id: 'a', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'b', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'c', text: 'Качественное время', textEn: 'Quality time' },
      { id: 'd', text: 'Слова поддержки', textEn: 'Words of affirmation' },
    ],
  },
  {
    id: 'loveLanguages-16',
    categoryId: 'loveLanguages',
    text: 'Прогулка вдвоём без наушников и телефонов — какой язык любви?',
    textEn: 'A walk together without headphones or phones is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Качественное время', textEn: 'Quality time' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'd', text: 'Физическое прикосновение', textEn: 'Physical touch' },
    ],
  },
  {
    id: 'loveLanguages-17',
    categoryId: 'loveLanguages',
    text: 'Сказать вслух «я тебя люблю» — какой язык любви?',
    textEn: 'Saying “I love you” out loud is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Слова поддержки', textEn: 'Words of affirmation' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'd', text: 'Физическое прикосновение', textEn: 'Physical touch' },
    ],
  },
  {
    id: 'loveLanguages-18',
    categoryId: 'loveLanguages',
    text: 'Что из этого НЕ является языком любви у Чепмена?',
    textEn: "Which of these is NOT one of Chapman's love languages?",
    correctId: 'a',
    options: [
      { id: 'a', text: 'Деньги', textEn: 'Money' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Качественное время', textEn: 'Quality time' },
      { id: 'd', text: 'Помощь', textEn: 'Acts of service' },
    ],
  },
  {
    id: 'loveLanguages-19',
    categoryId: 'loveLanguages',
    text: 'Обниматься на диване — какой язык любви?',
    textEn: 'Cuddling on the sofa is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Физическое прикосновение', textEn: 'Physical touch' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'd', text: 'Слова поддержки', textEn: 'Words of affirmation' },
    ],
  },
  {
    id: 'loveLanguages-20',
    categoryId: 'loveLanguages',
    text: 'Помочь с уборкой, когда партнёр устал, — какой язык любви?',
    textEn: 'Helping with chores when your partner is tired is which love language?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Помощь', textEn: 'Acts of service' },
      { id: 'b', text: 'Подарки', textEn: 'Receiving gifts' },
      { id: 'c', text: 'Качественное время', textEn: 'Quality time' },
      { id: 'd', text: 'Физическое прикосновение', textEn: 'Physical touch' },
    ],
  },
  {
    id: 'holidays-1',
    categoryId: 'holidays',
    text: 'В какой день отмечают Новый год?',
    textEn: 'On which date is New Year’s Day celebrated?',
    correctId: 'a',
    options: [
      { id: 'a', text: '1 января', textEn: 'January 1' },
      { id: 'b', text: '1 марта', textEn: 'March 1' },
      { id: 'c', text: '31 октября', textEn: 'October 31' },
      { id: 'd', text: '8 марта', textEn: 'March 8' },
    ],
  },
  {
    id: 'holidays-2',
    categoryId: 'holidays',
    text: 'Какой праздник отмечают 8 марта?',
    textEn: 'Which holiday is celebrated on March 8?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Международный женский день', textEn: "International Women's Day" },
      { id: 'b', text: 'День труда', textEn: 'Labor Day' },
      { id: 'c', text: 'Рождество', textEn: 'Christmas' },
      { id: 'd', text: 'Хэллоуин', textEn: 'Halloween' },
    ],
  },
  {
    id: 'holidays-3',
    categoryId: 'holidays',
    text: 'Какое дерево традиционно украшают на Новый год?',
    textEn: 'Which tree is traditionally decorated for the New Year?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Ель', textEn: 'Spruce / Christmas tree' },
      { id: 'b', text: 'Берёза', textEn: 'Birch' },
      { id: 'c', text: 'Пальма', textEn: 'Palm' },
      { id: 'd', text: 'Дуб', textEn: 'Oak' },
    ],
  },
  {
    id: 'holidays-4',
    categoryId: 'holidays',
    text: 'В каком месяце отмечают Хэллоуин?',
    textEn: 'In which month is Halloween celebrated?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Октябрь', textEn: 'October' },
      { id: 'b', text: 'Май', textEn: 'May' },
      { id: 'c', text: 'Июль', textEn: 'July' },
      { id: 'd', text: 'Январь', textEn: 'January' },
    ],
  },
  {
    id: 'holidays-5',
    categoryId: 'holidays',
    text: 'Когда отмечают Рождество в западной традиции?',
    textEn: 'When is Christmas celebrated in the Western tradition?',
    correctId: 'a',
    options: [
      { id: 'a', text: '25 декабря', textEn: 'December 25' },
      { id: 'b', text: '1 января', textEn: 'January 1' },
      { id: 'c', text: '14 февраля', textEn: 'February 14' },
      { id: 'd', text: '4 июля', textEn: 'July 4' },
    ],
  },
  {
    id: 'holidays-6',
    categoryId: 'holidays',
    text: 'Какой весенний праздник традиционно отмечают крашеными яйцами?',
    textEn: 'Which spring holiday is traditionally celebrated with painted eggs?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Пасха', textEn: 'Easter' },
      { id: 'b', text: 'Хэллоуин', textEn: 'Halloween' },
      { id: 'c', text: 'День труда', textEn: 'Labor Day' },
      { id: 'd', text: 'Холи', textEn: 'Holi' },
    ],
  },
  {
    id: 'holidays-7',
    categoryId: 'holidays',
    text: 'Какой праздник во многих странах отмечают 1 мая?',
    textEn: 'Which holiday do many countries celebrate on May 1?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'День труда', textEn: 'Labor Day' },
      { id: 'b', text: 'Рождество', textEn: 'Christmas' },
      { id: 'c', text: 'Хэллоуин', textEn: 'Halloween' },
      { id: 'd', text: 'День матери', textEn: "Mother's Day" },
    ],
  },
  {
    id: 'holidays-8',
    categoryId: 'holidays',
    text: 'Что традиционно едят на Масленицу?',
    textEn: 'What food is traditional for Maslenitsa / Pancake Week?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Блины', textEn: 'Pancakes' },
      { id: 'b', text: 'Пицца', textEn: 'Pizza' },
      { id: 'c', text: 'Суши', textEn: 'Sushi' },
      { id: 'd', text: 'Гамбургер', textEn: 'Hamburger' },
    ],
  },
  {
    id: 'holidays-9',
    categoryId: 'holidays',
    text: 'Международный день защиты детей отмечают какого числа июня?',
    textEn: 'On which June date is International Children’s Day celebrated?',
    correctId: 'a',
    options: [
      { id: 'a', text: '1 июня', textEn: 'June 1' },
      { id: 'b', text: '12 июня', textEn: 'June 12' },
      { id: 'c', text: '21 июня', textEn: 'June 21' },
      { id: 'd', text: '30 июня', textEn: 'June 30' },
    ],
  },
  {
    id: 'holidays-10',
    categoryId: 'holidays',
    text: 'Какой цвет ассоциируют с Днём святого Патрика?',
    textEn: "Which color is associated with St. Patrick's Day?",
    correctId: 'a',
    options: [
      { id: 'a', text: 'Зелёный', textEn: 'Green' },
      { id: 'b', text: 'Красный', textEn: 'Red' },
      { id: 'c', text: 'Чёрный', textEn: 'Black' },
      { id: 'd', text: 'Розовый', textEn: 'Pink' },
    ],
  },
  {
    id: 'holidays-11',
    categoryId: 'holidays',
    text: 'Кто в западной традиции приносит подарки на Рождество?',
    textEn: 'In Western tradition, who brings gifts at Christmas?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Санта-Клаус', textEn: 'Santa Claus' },
      { id: 'b', text: 'Пасхальный кролик', textEn: 'Easter Bunny' },
      { id: 'c', text: 'Купидон', textEn: 'Cupid' },
      { id: 'd', text: 'Тыква', textEn: 'A pumpkin' },
    ],
  },
  {
    id: 'holidays-12',
    categoryId: 'holidays',
    text: 'Какая дата у Хэллоуина?',
    textEn: 'What is the date of Halloween?',
    correctId: 'a',
    options: [
      { id: 'a', text: '31 октября', textEn: 'October 31' },
      { id: 'b', text: '1 апреля', textEn: 'April 1' },
      { id: 'c', text: '25 декабря', textEn: 'December 25' },
      { id: 'd', text: '8 марта', textEn: 'March 8' },
    ],
  },
  {
    id: 'holidays-13',
    categoryId: 'holidays',
    text: 'В каком месяце в США обычно отмечают День благодарения?',
    textEn: 'In which month is Thanksgiving usually celebrated in the USA?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Ноябрь', textEn: 'November' },
      { id: 'b', text: 'Март', textEn: 'March' },
      { id: 'c', text: 'Июнь', textEn: 'June' },
      { id: 'd', text: 'Август', textEn: 'August' },
    ],
  },
  {
    id: 'holidays-14',
    categoryId: 'holidays',
    text: 'Какой праздник отмечают 1 апреля?',
    textEn: 'Which holiday is celebrated on April 1?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'День смеха', textEn: "April Fools' Day" },
      { id: 'b', text: 'Рождество', textEn: 'Christmas' },
      { id: 'c', text: 'Пасха', textEn: 'Easter' },
      { id: 'd', text: 'Новый год', textEn: 'New Year' },
    ],
  },
  {
    id: 'holidays-15',
    categoryId: 'holidays',
    text: 'Какой праздник отмечают 4 июля в США?',
    textEn: 'Which holiday is celebrated on July 4 in the USA?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'День независимости', textEn: 'Independence Day' },
      { id: 'b', text: 'День труда', textEn: 'Labor Day' },
      { id: 'c', text: 'Рождество', textEn: 'Christmas' },
      { id: 'd', text: 'Хэллоуин', textEn: 'Halloween' },
    ],
  },
  {
    id: 'holidays-16',
    categoryId: 'holidays',
    text: 'Какой индийский праздник отмечают яркими красками?',
    textEn: 'Which Indian festival is celebrated with bright colored powders?',
    correctId: 'a',
    options: [
      { id: 'a', text: 'Холи', textEn: 'Holi' },
      { id: 'b', text: 'Хэллоуин', textEn: 'Halloween' },
      { id: 'c', text: 'Масленица', textEn: 'Maslenitsa' },
      { id: 'd', text: 'День благодарения', textEn: 'Thanksgiving' },
    ],
  },
  {
    id: 'holidays-17',
    categoryId: 'holidays',
    text: 'День взятия Бастилии во Франции отмечают какого числа июля?',
    textEn: 'On which July date is Bastille Day celebrated in France?',
    correctId: 'a',
    options: [
      { id: 'a', text: '14 июля', textEn: 'July 14' },
      { id: 'b', text: '4 июля', textEn: 'July 4' },
      { id: 'c', text: '1 июля', textEn: 'July 1' },
      { id: 'd', text: '31 июля', textEn: 'July 31' },
    ],
  },
  {
    id: 'holidays-18',
    categoryId: 'holidays',
    text: 'Когда в западной традиции отмечают День святого Николая?',
    textEn: "When is St. Nicholas Day celebrated in the Western tradition?",
    correctId: 'a',
    options: [
      { id: 'a', text: '6 декабря', textEn: 'December 6' },
      { id: 'b', text: '14 февраля', textEn: 'February 14' },
      { id: 'c', text: '1 апреля', textEn: 'April 1' },
      { id: 'd', text: '8 марта', textEn: 'March 8' },
    ],
  },
  {
    id: 'holidays-19',
    categoryId: 'holidays',
    text: 'Какая дата у рождественского сочельника в западной традиции?',
    textEn: 'What is the date of Christmas Eve in the Western tradition?',
    correctId: 'a',
    options: [
      { id: 'a', text: '24 декабря', textEn: 'December 24' },
      { id: 'b', text: '31 октября', textEn: 'October 31' },
      { id: 'c', text: '1 мая', textEn: 'May 1' },
      { id: 'd', text: '8 марта', textEn: 'March 8' },
    ],
  },
  {
    id: 'holidays-20',
    categoryId: 'holidays',
    text: 'Когда в западной христианской традиции отмечают Богоявление?',
    textEn: 'When is Epiphany celebrated in the Western Christian tradition?',
    correctId: 'a',
    options: [
      { id: 'a', text: '6 января', textEn: 'January 6' },
      { id: 'b', text: '14 февраля', textEn: 'February 14' },
      { id: 'c', text: '4 июля', textEn: 'July 4' },
      { id: 'd', text: '31 октября', textEn: 'October 31' },
    ],
  },
];
