/** Вопросы 21–40 для каждой категории (второе дополнение пула). */
export const QUIZ_QUESTIONS_EXTRA_2 = [
  // Любовь
  { id: 'love-21', categoryId: 'love', text: 'Как называют 10-летнюю годовщину свадьбы (международная традиция)?', answers: ['алюминиевая', 'оловянная', 'tin', 'aluminum', 'aluminium'] },
  { id: 'love-22', categoryId: 'love', text: 'Как называют 15-летнюю годовщину свадьбы (международная традиция)?', answers: ['хрустальная', 'crystal', 'стеклянная', 'glass'] },
  { id: 'love-23', categoryId: 'love', text: 'Как называют 30-летнюю годовщину свадьбы (международная традиция)?', answers: ['жемчужная', 'pearl'] },
  { id: 'love-24', categoryId: 'love', text: 'Как называют 40-летнюю годовщину свадьбы (международная традиция)?', answers: ['рубиновая', 'ruby'] },
  { id: 'love-25', categoryId: 'love', text: 'Как называют 60-летнюю годовщину свадьбы (международная традиция)?', answers: ['алмазная', 'diamond'] },
  { id: 'love-26', categoryId: 'love', text: 'На каком пальце традиционно носят обручальное кольцо?', answers: ['безымянный', 'безымянном', 'на безымянном'] },
  { id: 'love-27', categoryId: 'love', text: 'Как называется приглашение на свадьбу?', answers: ['пригласительное', 'приглашение', 'пригласительный'] },
  { id: 'love-28', categoryId: 'love', text: 'Как называется вечеринка невесты перед свадьбой?', answers: ['девичник', 'девичья вечеринка', 'bachelorette party', 'hen party'] },
  { id: 'love-29', categoryId: 'love', text: 'Как называется вечеринка жениха перед свадьбой?', answers: ['мальчишник', 'холостяцкая вечеринка', 'bachelor party', 'stag party'] },
  { id: 'love-30', categoryId: 'love', text: 'Как называется букет, который бросают незамужние подруги?', answers: ['букет невесты', 'букет', 'свадебный букет'] },
  { id: 'love-31', categoryId: 'love', text: 'Как называется ужин только для двоих при свечах?', answers: ['романтический ужин', 'свидание', 'ужин при свечах'] },
  { id: 'love-32', categoryId: 'love', text: 'Как называется письмо с признанием в чувствах?', answers: ['любовное письмо', 'письмо', 'валентинка'] },
  { id: 'love-33', categoryId: 'love', text: 'Как называется пара, которая только начала встречаться?', answers: ['влюбленные', 'новая пара', 'молодые'] },
  { id: 'love-34', categoryId: 'love', text: 'Как называется официальный союз мужчины и женщины?', answers: ['брак', 'супружество', 'семья'] },
  { id: 'love-35', categoryId: 'love', text: 'Кто традиционно ведёт невесту к алтарю?', answers: ['отец', 'папа', 'родитель'] },
  { id: 'love-36', categoryId: 'love', text: 'Как называется обмен клятвами на свадьбе?', answers: ['обеты', 'клятва', 'свадебные обеты'] },
  { id: 'love-37', categoryId: 'love', text: 'Как называется первая встреча родителей будущих супругов?', answers: ['знакомство', 'знакомство родителей', 'встреча родителей'] },
  { id: 'love-38', categoryId: 'love', text: 'Как называется обещание жениться?', answers: ['помолвка', 'обручение', 'предложение'] },
  { id: 'love-39', categoryId: 'love', text: 'Как называется танец пары перед гостями на свадьбе?', answers: ['свадебный танец', 'первый танец', 'открытие бала'] },
  { id: 'love-40', categoryId: 'love', text: 'Как называется совместный отдых только для двоих?', answers: ['романтический отпуск', 'отпуск вдвоем', 'уикенд вдвоем'] },
  // Кино
  { id: 'cinema-21', categoryId: 'cinema', text: 'Как зовут главного героя «Крёстного отца»?', answers: ['вито корлеоне', 'корлеоне', 'дон корлеоне'] },
  { id: 'cinema-22', categoryId: 'cinema', text: 'Как зовут героя «Побега из Шоушенка»?', answers: ['энди', 'dufresne', 'энди dufresne'] },
  { id: 'cinema-23', categoryId: 'cinema', text: 'Кто режиссёр фильма «Начало» (Inception)?', answers: ['нолан', 'кристофер нолан', 'christopher nolan'] },
  { id: 'cinema-24', categoryId: 'cinema', text: 'Как зовут героя «Гладиатора»?', answers: ['максимус', 'maximus'] },
  { id: 'cinema-25', categoryId: 'cinema', text: 'Как зовут волшебника в «Гарри Поттере»?', answers: ['гарри', 'harry', 'гарри поттер'] },
  { id: 'cinema-26', categoryId: 'cinema', text: 'Как зовут робота в мультфильме «WALL-E»?', answers: ['wall-e', 'валли', 'walle'] },
  { id: 'cinema-27', categoryId: 'cinema', text: 'Как зовут принцессу в «Красавице и Чудовище» (Disney)?', answers: ['бель', 'belle'] },
  { id: 'cinema-28', categoryId: 'cinema', text: 'Кто режиссёр «Криминального чтива»?', answers: ['тарантино', 'квентин тарантино', 'tarantino'] },
  { id: 'cinema-29', categoryId: 'cinema', text: 'Как зовут археолога в «Индиане Джонсе»?', answers: ['индиана', 'indiana', 'индиана джонс'] },
  { id: 'cinema-30', categoryId: 'cinema', text: 'Как зовут капитана «Пиратов Карибского моря»?', answers: ['джек воробей', 'воробей', 'jack sparrow'] },
  { id: 'cinema-31', categoryId: 'cinema', text: 'Как зовут крысёна-повара в «Ratatouille»?', answers: ['реми', 'remy'] },
  { id: 'cinema-32', categoryId: 'cinema', text: 'Кто режиссёр «Interstellar»?', answers: ['нолан', 'кристофер нолан', 'christopher nolan'] },
  { id: 'cinema-33', categoryId: 'cinema', text: 'В каком мультфильме поют «Let It Go»?', answers: ['холодное сердце', 'frozen'] },
  { id: 'cinema-34', categoryId: 'cinema', text: 'Кто сыграл Терминатора (актер)?', answers: ['шварценеггер', 'шварц', 'арнольд'] },
  { id: 'cinema-35', categoryId: 'cinema', text: 'Кто сыграл Джокера в «Тёмном рыцаре»?', answers: ['леджер', 'хит леджер', 'heath ledger'] },
  { id: 'cinema-36', categoryId: 'cinema', text: 'Как зовут злодея с маской в «Тёмном рыцаре»?', answers: ['джокер', 'joker'] },
  { id: 'cinema-37', categoryId: 'cinema', text: 'Как зовут героя «Назад в будущее»?', answers: ['марти', 'marty', 'макфлай'] },
  { id: 'cinema-38', categoryId: 'cinema', text: 'Как зовут главного динозавра в «Парке юрского периода»?', answers: ['t-rex', 'тираннозавр', 'rex'] },
  { id: 'cinema-39', categoryId: 'cinema', text: 'Как называется студия мультфильмов «Zootropolis» и «Moana»?', answers: ['disney', 'дисней'] },
  { id: 'cinema-40', categoryId: 'cinema', text: 'Как зовут героя «Бойцовского клуба»?', answers: ['тайлер', 'tyler'] },
  // Путешествия
  { id: 'travel-21', categoryId: 'travel', text: 'Столица Турции?', answers: ['анкара', 'ankara'] },
  { id: 'travel-22', categoryId: 'travel', text: 'Столица Южной Кореи?', answers: ['сеул', 'seoul'] },
  { id: 'travel-23', categoryId: 'travel', text: 'Столица Аргентины?', answers: ['буэнос-айрес', 'buenos aires'] },
  { id: 'travel-24', categoryId: 'travel', text: 'Столица Норвегии?', answers: ['осло', 'oslo'] },
  { id: 'travel-25', categoryId: 'travel', text: 'Столица Швеции?', answers: ['стокгольм', 'stockholm'] },
  { id: 'travel-26', categoryId: 'travel', text: 'Столица Португалии?', answers: ['лиссабон', 'lisbon'] },
  { id: 'travel-27', categoryId: 'travel', text: 'Столица Греции?', answers: ['афины', 'athens'] },
  { id: 'travel-28', categoryId: 'travel', text: 'Столица Чехии?', answers: ['прага', 'prague'] },
  { id: 'travel-29', categoryId: 'travel', text: 'Столица Польши?', answers: ['варшава', 'warsaw'] },
  { id: 'travel-30', categoryId: 'travel', text: 'Столица Индии?', answers: ['нью-дели', 'дели', 'new delhi'] },
  { id: 'travel-31', categoryId: 'travel', text: 'Столица Мексики?', answers: ['мехико', 'mexico city'] },
  { id: 'travel-32', categoryId: 'travel', text: 'Столица Таиланда?', answers: ['бангкок', 'bangkok'] },
  { id: 'travel-33', categoryId: 'travel', text: 'Столица Египта?', answers: ['каир', 'cairo'] },
  { id: 'travel-34', categoryId: 'travel', text: 'Столица Австрии?', answers: ['вена', 'vienna'] },
  { id: 'travel-35', categoryId: 'travel', text: 'Столица Швейцарии?', answers: ['берн', 'bern'] },
  { id: 'travel-36', categoryId: 'travel', text: 'В какой стране находится Тадж-Махал?', answers: ['индия', 'индии'] },
  { id: 'travel-37', categoryId: 'travel', text: 'В какой стране находится Сиднейский оперный театр?', answers: ['австралия', 'австралии'] },
  { id: 'travel-38', categoryId: 'travel', text: 'Самое глубокое место океана?', answers: ['марианская впадина', 'марианский желоб'] },
  { id: 'travel-39', categoryId: 'travel', text: 'Столица Финляндии?', answers: ['хельсинки', 'helsinki'] },
  { id: 'travel-40', categoryId: 'travel', text: 'Столица Ирландии?', answers: ['дублин', 'dublin'] },
  // Общее
  { id: 'general-21', categoryId: 'general', text: 'Сколько планет в Солнечной системе?', answers: ['8', 'восемь'] },
  { id: 'general-22', categoryId: 'general', text: 'Какая планета известна кольцами?', answers: ['сатурн'] },
  { id: 'general-23', categoryId: 'general', text: 'Сколько континентов на Земле (классическая модель)?', answers: ['6', 'шесть', '7', 'семь'] },
  { id: 'general-24', categoryId: 'general', text: 'Какой металл обозначается Cu?', answers: ['медь'] },
  { id: 'general-25', categoryId: 'general', text: 'Какой металл обозначается Ag?', answers: ['серебро'] },
  { id: 'general-26', categoryId: 'general', text: 'Сколько секунд в одной минуте?', answers: ['60', 'шестьдесят'] },
  { id: 'general-27', categoryId: 'general', text: 'Какой орган у человека отвечает за кровообращение?', answers: ['сердце'] },
  { id: 'general-28', categoryId: 'general', text: 'Сколько зубов у взрослого человека (обычно)?', answers: ['32', 'тридцать два'] },
  { id: 'general-29', categoryId: 'general', text: 'Какой газ горит с голубым пламенем (бытовой)?', answers: ['метан', 'газ', 'природный газ'] },
  { id: 'general-30', categoryId: 'general', text: 'Сколько букв в русском алфавите?', answers: ['33', 'тридцать три'] },
  { id: 'general-31', categoryId: 'general', text: 'Какой океан самый маленький?', answers: ['северный ледовитый', 'arctic'] },
  { id: 'general-32', categoryId: 'general', text: 'Сколько игроков в шахматной партии?', answers: ['2', 'два'] },
  { id: 'general-33', categoryId: 'general', text: 'Какой цвет получается при смешении синего и жёлтого?', answers: ['зеленый', 'зелёный'] },
  { id: 'general-34', categoryId: 'general', text: 'Сколько костей в теле взрослого человека (примерно)?', answers: ['206', 'двести шесть'] },
  { id: 'general-35', categoryId: 'general', text: 'Какая единица измеряет силу тока?', answers: ['ампер', 'a'] },
  { id: 'general-36', categoryId: 'general', text: 'Сколько граммов в одном килограмме?', answers: ['1000', 'тысяча'] },
  { id: 'general-37', categoryId: 'general', text: 'Какой орган у человека отвечает за дыхание?', answers: ['легкие', 'легкое'] },
  { id: 'general-38', categoryId: 'general', text: 'Сколько дней в феврале в обычном году?', answers: ['28', 'двадцать восемь'] },
  { id: 'general-39', categoryId: 'general', text: 'Какой химический элемент обозначается Na?', answers: ['натрий'] },
  { id: 'general-40', categoryId: 'general', text: 'Сколько углов у треугольника?', answers: ['3', 'три'] },
  // Музыка
  { id: 'music-21', categoryId: 'music', text: 'Как называется музыкальный знак «#»?', answers: ['диез', 'sharp'] },
  { id: 'music-22', categoryId: 'music', text: 'Как называется музыкальный знак понижения ноты?', answers: ['бемоль', 'б'] },
  { id: 'music-23', categoryId: 'music', text: 'Какой композитор написал оперу «Кармен»?', answers: ['бизе', 'bizet'] },
  { id: 'music-24', categoryId: 'music', text: 'Как называется ансамбль из четырёх музыкантов?', answers: ['квартет'] },
  { id: 'music-25', categoryId: 'music', text: 'Как называется ансамбль из трёх музыкантов?', answers: ['трио'] },
  { id: 'music-26', categoryId: 'music', text: 'Какой инструмент играют, дуя в отверстие?', answers: ['флейта', 'свирель', 'блокфлейта'] },
  { id: 'music-27', categoryId: 'music', text: 'Как называется большой ударный инструмент с мембраной на стойке?', answers: ['литавры', 'барабан', 'тимпаны'] },
  { id: 'music-28', categoryId: 'music', text: 'Какой стиль музыки родом из Ямайки?', answers: ['регги', 'reggae'] },
  { id: 'music-29', categoryId: 'music', text: 'Как называется текст песни?', answers: ['лирика', 'слова', 'текст'] },
  { id: 'music-30', categoryId: 'music', text: 'Какой композитор написал «Времена года»?', answers: ['вивальди', 'vivaldi'] },
  { id: 'music-31', categoryId: 'music', text: 'Как называется повторяющаяся мелодия в песне?', answers: ['припев', 'refrain', 'chorus'] },
  { id: 'music-32', categoryId: 'music', text: 'Какой инструмент имеет клавиши и молоточки?', answers: ['фортепиано', 'пианино', 'рояль'] },
  { id: 'music-33', categoryId: 'music', text: 'Как называется жанр оперного пения для мужчин с низким голосом?', answers: ['бас', 'bass'] },
  { id: 'music-34', categoryId: 'music', text: 'Какой инструмент — большая медная труба в оркестре?', answers: ['туба', 'tuba'] },
  { id: 'music-35', categoryId: 'music', text: 'Как называется запись нескольких песен на одном носителе?', answers: ['альбом', 'album'] },
  { id: 'music-36', categoryId: 'music', text: 'Какой композитор написал «Реквием»?', answers: ['моцарт', 'mozart'] },
  { id: 'music-37', categoryId: 'music', text: 'Как называется устройство для настройки инструмента?', answers: ['тюнер', 'tuner', 'камертон'] },
  { id: 'music-38', categoryId: 'music', text: 'Какой жанр музыки ассоциируют с Нью-Орлеаном?', answers: ['джаз', 'jazz'] },
  { id: 'music-39', categoryId: 'music', text: 'Как называется начало музыкального произведения?', answers: ['вступление', 'intro', 'интро'] },
  { id: 'music-40', categoryId: 'music', text: 'Какой инструмент играют, щипая струны?', answers: ['гитара', 'банджо', 'banjo'] },
  // Еда и кухня
  { id: 'food-21', categoryId: 'food', text: 'Как называется итальянское мороженое?', answers: ['джелато', 'gelato'] },
  { id: 'food-22', categoryId: 'food', text: 'Как называется мексиканская лепёшка с начинкой?', answers: ['тако', 'burrito', 'taco'] },
  { id: 'food-23', categoryId: 'food', text: 'Какой соус делают из томатов для пасты?', answers: ['томатный', 'marinara', 'болоньезе'] },
  { id: 'food-24', categoryId: 'food', text: 'Как называется французский суп из лука?', answers: ['луковый суп', 'суп'] },
  { id: 'food-25', categoryId: 'food', text: 'Какой орех — основа соуса песто?', answers: ['кедровый', 'кедровые орехи'] },
  { id: 'food-26', categoryId: 'food', text: 'Как называется грузинское блюдо из теста с сыром?', answers: ['хачапури'] },
  { id: 'food-27', categoryId: 'food', text: 'Какой напиток делают из ферментированного винограда?', answers: ['вино', 'wine'] },
  { id: 'food-28', categoryId: 'food', text: 'Как называется испанский холодный овощной суп?', answers: ['гаспачо', 'gazpacho'] },
  { id: 'food-29', categoryId: 'food', text: 'Какая специя даёт жёлтый цвет карри?', answers: ['куркума', 'turmeric'] },
  { id: 'food-30', categoryId: 'food', text: 'Как называется тонкое тесто для пиццы?', answers: ['тесто', 'dough'] },
  { id: 'food-31', categoryId: 'food', text: 'Какой фрукт — основа guacamole?', answers: ['авокадо', 'avocado'] },
  { id: 'food-32', categoryId: 'food', text: 'Как называется русское блюдо из теста с мясом?', answers: ['пельмени', 'pelmeni'] },
  { id: 'food-33', categoryId: 'food', text: 'Какой продукт — основа хумуса?', answers: ['нут', 'chickpeas'] },
  { id: 'food-34', categoryId: 'food', text: 'Как называется сладкая глазурь на торте?', answers: ['глазурь', 'glaze'] },
  { id: 'food-35', categoryId: 'food', text: 'Какой напиток делают из какао-бобов без сахара?', answers: ['какао', 'горький шоколад'] },
  { id: 'food-36', categoryId: 'food', text: 'Как называется индийское блюдо из риса со специями?', answers: ['бирьяни', 'biryani', 'плов'] },
  { id: 'food-37', categoryId: 'food', text: 'Какой сыр с дырками из Швейцарии?', answers: ['эмменталь', 'emmental'] },
  { id: 'food-38', categoryId: 'food', text: 'Как называется корейское блюдо из капусты?', answers: ['кимчи', 'kimchi'] },
  { id: 'food-39', categoryId: 'food', text: 'Какой хлеб традиционен для багета?', answers: ['французский', 'baguette', 'багет'] },
  { id: 'food-40', categoryId: 'food', text: 'Как называется русский суп из рыбы?', answers: ['уха', 'рыбный суп'] },
  // Природа и животные
  { id: 'nature-21', categoryId: 'nature', text: 'Какое животное меняет цвет для маскировки?', answers: ['хамелеон'] },
  { id: 'nature-22', categoryId: 'nature', text: 'Какое млекопитающее умеет летать?', answers: ['летучая мышь', 'мышь'] },
  { id: 'nature-23', categoryId: 'nature', text: 'Какой хищник — самый быстрый в море?', answers: ['марлин', 'рыба-меч', 'marlin'] },
  { id: 'nature-24', categoryId: 'nature', text: 'Какое дерево сбрасывает иголки зимой (хвойное исключение)?', answers: ['лиственница', 'larch'] },
  { id: 'nature-25', categoryId: 'nature', text: 'Какой цветок — символ Голландии?', answers: ['тюльпан', 'tulip'] },
  { id: 'nature-26', categoryId: 'nature', text: 'Какое животное носит дом на спине?', answers: ['улитка', 'черепаха'] },
  { id: 'nature-27', categoryId: 'nature', text: 'Какая птица имеет яркий расписной хвост?', answers: ['павлин', 'peacock'] },
  { id: 'nature-28', categoryId: 'nature', text: 'Какое насекомое светится ночью?', answers: ['светлячок', 'firefly'] },
  { id: 'nature-29', categoryId: 'nature', text: 'Какое животное охотится из-под льда в Арктике?', answers: ['морж', 'walrus'] },
  { id: 'nature-30', categoryId: 'nature', text: 'Какое растение ловит насекомых ловушками?', answers: ['росянка', 'венерина мухоловка'] },
  { id: 'nature-31', categoryId: 'nature', text: 'Какой зверь строит плотины на реках?', answers: ['бобр', 'beaver'] },
  { id: 'nature-32', categoryId: 'nature', text: 'Какая птица не умеет летать, но быстро бегает?', answers: ['страус', 'ostrich'] },
  { id: 'nature-33', categoryId: 'nature', text: 'Какое животное спит стоя?', answers: ['лошадь', 'конь'] },
  { id: 'nature-34', categoryId: 'nature', text: 'Какой газ составляет большую часть солнечной атмосферы?', answers: ['водород', 'h2'] },
  { id: 'nature-35', categoryId: 'nature', text: 'Какое млекопитающее откладывает яйца?', answers: ['утконос', 'platypus'] },
  { id: 'nature-36', categoryId: 'nature', text: 'Какой цветок часто распускается первым весной?', answers: ['подснежник', 'snowdrop'] },
  { id: 'nature-37', categoryId: 'nature', text: 'Какое животное меняет шкуру при линьке?', answers: ['змея', 'рептилия'] },
  { id: 'nature-38', categoryId: 'nature', text: 'Какой океан омывает восточное побережье США?', answers: ['атлантический', 'atlantic'] },
  { id: 'nature-39', categoryId: 'nature', text: 'Какое насекомое строит соты?', answers: ['пчела', 'bee'] },
  { id: 'nature-40', categoryId: 'nature', text: 'Какой хищник живёт стайами и охотится ночью?', answers: ['волк', 'wolf'] },
  // Праздники и традиции
  { id: 'holidays-21', categoryId: 'holidays', text: 'Во многих странах учебный год в школе начинается в каком месяце?', answers: ['сентябрь', 'сентябре', 'september'] },
  { id: 'holidays-22', categoryId: 'holidays', text: 'Всемирный день учителя (ЮНЕСКО) отмечают 5 октября — в каком месяце?', answers: ['октябрь', 'октябре', 'october'] },
  { id: 'holidays-23', categoryId: 'holidays', text: 'День взятия Бастилии (национальный праздник Франции) — какое число июля?', answers: ['14', '14 июля', 'четырнадцатое июля', 'july 14', '14 july'] },
  { id: 'holidays-24', categoryId: 'holidays', text: 'День прав человека (ООН) отмечают 10 декабря — в каком месяце?', answers: ['декабрь', 'декабре', 'december'] },
  { id: 'holidays-25', categoryId: 'holidays', text: 'Сочельник (канун Рождества) в западной традиции — какая дата?', answers: ['24 декабря', 'двадцать четвертое декабря', 'december 24', '24 december', 'christmas eve'] },
  { id: 'holidays-26', categoryId: 'holidays', text: 'Какой праздник связан с поминовением усопших (ноябрь)?', answers: ['день всех святых', '1 ноября'] },
  { id: 'holidays-27', categoryId: 'holidays', text: 'Какой осенний праздник в США связан с тыквами и благодарностью?', answers: ['день благодарения', 'thanksgiving'] },
  { id: 'holidays-28', categoryId: 'holidays', text: 'Какой символ вешают на дверь на китайский Новый год?', answers: ['фонарик', 'красный фонарь'] },
  { id: 'holidays-29', categoryId: 'holidays', text: 'Какой индийский праздник отмечают с красками?', answers: ['holi', 'холи'] },
  { id: 'holidays-30', categoryId: 'holidays', text: 'Когда отмечают День святого Николая (западная традиция)?', answers: ['6 декабря', 'шестое декабря'] },
  { id: 'holidays-31', categoryId: 'holidays', text: 'Какой праздник отмечают с тыквами и костюмами?', answers: ['хэллоуин', 'halloween'] },
  { id: 'holidays-32', categoryId: 'holidays', text: 'Всемирный день шоколада часто отмечают 7 июля — в каком месяце?', answers: ['июль', 'июле', 'july'] },
  { id: 'holidays-33', categoryId: 'holidays', text: 'Какой праздник отмечают 4 июля в США?', answers: ['день независимости', 'independence day'] },
  { id: 'holidays-34', categoryId: 'holidays', text: 'В каком году человек впервые ступил на Луну (программа Apollo)?', answers: ['1969'] },
  { id: 'holidays-35', categoryId: 'holidays', text: 'Как называется церемония окончания средней школы?', answers: ['выпускной', 'graduation', 'prom'] },
  { id: 'holidays-36', categoryId: 'holidays', text: 'Международный день мужчин отмечают 19 ноября — в каком месяце?', answers: ['ноябрь', 'ноябре', 'november'] },
  { id: 'holidays-37', categoryId: 'holidays', text: 'Фестиваль Сан-Фермин в Испании известен бегом с чем?', answers: ['быками', 'быков', 'bulls', 'bull run'] },
  { id: 'holidays-38', categoryId: 'holidays', text: 'Когда отмечают День благодарения в США (обычно)?', answers: ['ноябрь', 'thanksgiving'] },
  { id: 'holidays-39', categoryId: 'holidays', text: 'Какой итальянский праздник связан с подарками в сапогах?', answers: ['befana', 'бефана'] },
  { id: 'holidays-40', categoryId: 'holidays', text: 'Богоявление (Epiphany) в западной христианской традиции — какая дата?', answers: ['6 января', 'шестое января', 'january 6', '6 january', 'epiphany'] },
  // Языки любви
  { id: 'loveLanguages-21', categoryId: 'loveLanguages', text: 'Подарок «просто так» относится к какому языку?', answers: ['receiving gifts', 'подарки', 'получение подарков'] },
  { id: 'loveLanguages-22', categoryId: 'loveLanguages', text: 'Совместная прогулка без телефона — какой язык?', answers: ['quality time', 'качественное время', 'время вместе'] },
  { id: 'loveLanguages-23', categoryId: 'loveLanguages', text: 'Слова «я горжусь тобой» — какой язык?', answers: ['words of affirmation', 'слова поддержки', 'слова похвалы'] },
  { id: 'loveLanguages-24', categoryId: 'loveLanguages', text: 'Приготовить завтрак партнёру — какой язык?', answers: ['acts of service', 'помощь', 'дела', 'служение'] },
  { id: 'loveLanguages-25', categoryId: 'loveLanguages', text: 'Держаться за руки — какой язык?', answers: ['physical touch', 'прикосновения', 'физическое прикосновение'] },
  { id: 'loveLanguages-26', categoryId: 'loveLanguages', text: 'Как переводится acts of service?', answers: ['помощь', 'служение', 'дела'] },
  { id: 'loveLanguages-27', categoryId: 'loveLanguages', text: 'Как переводится receiving gifts?', answers: ['подарки', 'получение подарков'] },
  { id: 'loveLanguages-28', categoryId: 'loveLanguages', text: 'Как переводится physical touch?', answers: ['прикосновения', 'физическое прикосновение'] },
  { id: 'loveLanguages-29', categoryId: 'loveLanguages', text: 'Слушать партнёра без перебивания — пример какого языка?', answers: ['quality time', 'качественное время', 'время вместе'] },
  { id: 'loveLanguages-30', categoryId: 'loveLanguages', text: 'Записка «спасибо, что ты есть» — какой язык?', answers: ['words of affirmation', 'слова поддержки', 'слова похвалы'] },
  { id: 'loveLanguages-31', categoryId: 'loveLanguages', text: 'Починить сломанную вещь для партнёра — какой язык?', answers: ['acts of service', 'помощь', 'дела', 'служение'] },
  { id: 'loveLanguages-32', categoryId: 'loveLanguages', text: 'Обнимать при встрече — какой язык?', answers: ['physical touch', 'прикосновения', 'физическое прикосновение'] },
  { id: 'loveLanguages-33', categoryId: 'loveLanguages', text: 'Сюрприз-билеты в кино — это время и …?', answers: ['подарки', 'receiving gifts', 'качественное время'] },
  { id: 'loveLanguages-34', categoryId: 'loveLanguages', text: 'Похвала за внешний вид — какой язык?', answers: ['words of affirmation', 'слова поддержки', 'слова похвалы'] },
  { id: 'loveLanguages-35', categoryId: 'loveLanguages', text: 'Выслушать после трудного дня — какой язык?', answers: ['quality time', 'качественное время', 'время вместе'] },
  { id: 'loveLanguages-36', categoryId: 'loveLanguages', text: 'Массаж плеч — какой язык?', answers: ['physical touch', 'прикосновения', 'физическое прикосновение'] },
  { id: 'loveLanguages-37', categoryId: 'loveLanguages', text: 'Купить любимый чай партнёру — какой язык?', answers: ['receiving gifts', 'подарки', 'получение подарков'] },
  { id: 'loveLanguages-38', categoryId: 'loveLanguages', text: 'Сказать «я тебя люблю» вслух — какой язык?', answers: ['words of affirmation', 'слова поддержки', 'слова похвалы'] },
  { id: 'loveLanguages-39', categoryId: 'loveLanguages', text: 'Забрать партнёра с работы — какой язык?', answers: ['acts of service', 'помощь', 'дела', 'служение'] },
  { id: 'loveLanguages-40', categoryId: 'loveLanguages', text: 'Сидеть рядом на диване — какой язык?', answers: ['physical touch', 'quality time', 'прикосновения'] },
  // Технологии и интернет
  { id: 'tech-21', categoryId: 'tech', text: 'Как называется видеохостинг от Google?', answers: ['youtube', 'ютуб'] },
  { id: 'tech-22', categoryId: 'tech', text: 'Как называется операционная система для iPhone?', answers: ['ios', 'айос'] },
  { id: 'tech-23', categoryId: 'tech', text: 'Как называется язык разметки веб-страниц?', answers: ['html', 'html5'] },
  { id: 'tech-24', categoryId: 'tech', text: 'Как называется каскадная таблица стилей для веба?', answers: ['css', 'css3'] },
  { id: 'tech-25', categoryId: 'tech', text: 'Как называется язык программирования для браузера?', answers: ['javascript', 'js'] },
  { id: 'tech-26', categoryId: 'tech', text: 'Как называется беспроводная технология для наушников?', answers: ['bluetooth', 'блютуз'] },
  { id: 'tech-27', categoryId: 'tech', text: 'Как называется сервис стриминга музыки от Spotify?', answers: ['spotify', 'спотифай'] },
  {
    id: 'tech-28',
    categoryId: 'tech',
    text: 'Как называется линейка процессоров Apple для Mac?',
    answers: [
      'м-серия',
      'm series',
      'm-серия',
      'm серия',
      'apple silicon',
      'apple m',
      'm chip',
      'm-чип',
      'm1',
      'm2',
    ],
  },
  { id: 'tech-29', categoryId: 'tech', text: 'Как называется виртуальный помощник Amazon?', answers: ['alexa', 'алекса'] },
  { id: 'tech-30', categoryId: 'tech', text: 'Как называется виртуальный помощник Apple?', answers: ['siri', 'сири'] },
  { id: 'tech-31', categoryId: 'tech', text: 'Как называется формат сжатия изображений с потерями?', answers: ['jpeg', 'jpg'] },
  { id: 'tech-32', categoryId: 'tech', text: 'Как называется протокол защищённого сайта?', answers: ['ssl', 'tls', 'https'] },
  { id: 'tech-33', categoryId: 'tech', text: 'Как называется соцсеть для фото с Stories?', answers: ['instagram', 'insta', 'инстаграм'] },
  { id: 'tech-34', categoryId: 'tech', text: 'Как называется сервис видеозвонков от Microsoft?', answers: ['teams', 'microsoft teams', 'skype'] },
  { id: 'tech-35', categoryId: 'tech', text: 'Как называется электронная почта Google?', answers: ['gmail', 'джимейл'] },
  { id: 'tech-36', categoryId: 'tech', text: 'Как называется карта мира от Google?', answers: ['google maps', 'maps', 'гугл карты'] },
  { id: 'tech-37', categoryId: 'tech', text: 'Как называется облачный диск от Google?', answers: ['google drive', 'drive', 'гугл диск'] },
  { id: 'tech-38', categoryId: 'tech', text: 'Как называется ИИ-чатбот от OpenAI?', answers: ['chatgpt', 'gpt', 'chat gpt'] },
  { id: 'tech-39', categoryId: 'tech', text: 'Как называется порт для зарядки современных Android?', answers: ['usb-c', 'usbc', 'type c'] },
  { id: 'tech-40', categoryId: 'tech', text: 'Как называется двухфакторная аутентификация (аббревиатура)?', answers: ['2fa', 'two factor', 'двухфакторная'] },
  // Спорт
  { id: 'sport-21', categoryId: 'sport', text: 'Сколько игроков в волейбольной команде на площадке?', answers: ['6', 'шесть'] },
  { id: 'sport-22', categoryId: 'sport', text: 'Сколько игроков в регби-команде на поле (стандарт)?', answers: ['15', 'пятнадцать'] },
  { id: 'sport-23', categoryId: 'sport', text: 'В каком спорте используют рапиру, саблю и шпагу?', answers: ['фехтование', 'fencing'] },
  { id: 'sport-24', categoryId: 'sport', text: 'В каком спорте есть «home run»?', answers: ['бейсбол', 'baseball'] },
  { id: 'sport-25', categoryId: 'sport', text: 'Сколько очков за трёхочковый бросок в баскетболе?', answers: ['3', 'три'] },
  { id: 'sport-26', categoryId: 'sport', text: 'В каком спорте гоняют на лошадях через препятствия?', answers: ['конкур', 'equestrian'] },
  { id: 'sport-27', categoryId: 'sport', text: 'Как называется площадка для бокса?', answers: ['ринг', 'ring'] },
  { id: 'sport-28', categoryId: 'sport', text: 'В каком спорте используют клюшку и маленький мяч на льду?', answers: ['керлинг', 'curling'] },
  { id: 'sport-29', categoryId: 'sport', text: 'Сколько сетов нужно выиграть в мужском теннисе на Wimbledon (обычно)?', answers: ['3', 'три'] },
  { id: 'sport-30', categoryId: 'sport', text: 'В каком спорте есть «spare» и «strike»?', answers: ['боулинг', 'bowling'] },
  { id: 'sport-31', categoryId: 'sport', text: 'Как называется дисциплина: бег, плавание, велосипед подряд?', answers: ['triathlon', 'триатлон'] },
  { id: 'sport-32', categoryId: 'sport', text: 'В каком спорте используют шлем и доску на волне?', answers: ['серфинг', 'surfing'] },
  { id: 'sport-33', categoryId: 'sport', text: 'Сколько игроков в команде по водному поло в бассейне?', answers: ['7', 'семь'] },
  { id: 'sport-34', categoryId: 'sport', text: 'В каком спорте есть «шах и мат» на доске 8x8?', answers: ['шахматы', 'chess'] },
  { id: 'sport-35', categoryId: 'sport', text: 'Как называется зимний спорт: прыжки с трамплина на лыжах?', answers: ['ski jumping', 'прыжки с трамплина'] },
  { id: 'sport-36', categoryId: 'sport', text: 'В каком спорте используют мяч и сетку, но нельзя касаться сетки?', answers: ['волейбол', 'volleyball'] },
  { id: 'sport-37', categoryId: 'sport', text: 'Сколько игроков в команде по гандболу на площадке?', answers: ['7', 'семь'] },
  { id: 'sport-38', categoryId: 'sport', text: 'В каком спорте разыгрывают Кубок Стэнли?', answers: ['хоккей', 'hockey'] },
  { id: 'sport-39', categoryId: 'sport', text: 'Как называется бег на короткую дистанцию до 400 м?', answers: ['sprint', 'спринт'] },
  { id: 'sport-40', categoryId: 'sport', text: 'В каком спорте используют ракетку и воланчик?', answers: ['badminton', 'бадминтон'] },
  // Искусство и литература
  { id: 'art-21', categoryId: 'art', text: 'Кто написал «Анну Каренину»?', answers: ['толстой', 'лев толстой', 'л. н. толстой'] },
  { id: 'art-22', categoryId: 'art', text: 'Кто написал «Гамлет»?', answers: ['шекспир', 'shakespeare'] },
  { id: 'art-23', categoryId: 'art', text: 'Кто написал «Тихий Дон»?', answers: ['шолохов', 'михаил шолохов'] },
  { id: 'art-24', categoryId: 'art', text: 'Кто написал «Героя нашего времени»?', answers: ['лермонтов', 'михаил лермонтов'] },
  { id: 'art-25', categoryId: 'art', text: 'Кто написал «Капитанскую дочку»?', answers: ['пушкин', 'александр пушкин'] },
  { id: 'art-26', categoryId: 'art', text: 'Кто написал «Идиота»?', answers: ['достоевский', 'федор достоевский'] },
  { id: 'art-27', categoryId: 'art', text: 'Кто написал «Обломов»?', answers: ['гончаров', 'иван гончаров'] },
  { id: 'art-28', categoryId: 'art', text: 'Кто написал «Грозу»?', answers: ['островский', 'александр островский'] },
  { id: 'art-29', categoryId: 'art', text: 'Кто написал поэму «Мертвые души»?', answers: ['гоголь', 'николай гоголь'] },
  { id: 'art-30', categoryId: 'art', text: 'Кто написал «Вишнёвый сад»?', answers: ['чехов', 'антон чехов'] },
  { id: 'art-31', categoryId: 'art', text: 'Кто написал «Двенадцать стульев»?', answers: ['ильф', 'петров', 'ильф и петров'] },
  { id: 'art-32', categoryId: 'art', text: 'Кто написал «Доктор Живаго»?', answers: ['пастернак', 'борис пастернак'] },
  { id: 'art-33', categoryId: 'art', text: 'Кто написал картину «Девочка с персиками»?', answers: ['серов', 'валентин серов'] },
  { id: 'art-34', categoryId: 'art', text: 'Кто написал икону «Богоматерь Владимирская»?', answers: ['рублев', 'андрей рублев'] },
  { id: 'art-35', categoryId: 'art', text: 'Кто написал «Утро в сосновом лесу»?', answers: ['шишкин', 'иван шишкин'] },
  { id: 'art-36', categoryId: 'art', text: 'Кто написал «Явление Христа народу»?', answers: ['крамской', 'иван крамской'] },
  { id: 'art-37', categoryId: 'art', text: 'Кто написал картину «Танец» (Matisse)?', answers: ['матисс', 'matisse'] },
  { id: 'art-38', categoryId: 'art', text: 'Кто написал «Звёздную ночь»?', answers: ['ван гог', 'van gogh'] },
  { id: 'art-39', categoryId: 'art', text: 'Кто написал «Девушку с жемчужной серьгой»?', answers: ['вермеер', 'vermeer'] },
  { id: 'art-40', categoryId: 'art', text: 'Кто написал триптих «Сад земных наслаждений»?', answers: ['босх', 'hieronymus bosch'] },
  // Дом и быт
  { id: 'home-21', categoryId: 'home', text: 'Какой прибор охлаждает воздух летом?', answers: ['кондиционер', 'кондиционером'] },
  { id: 'home-22', categoryId: 'home', text: 'Как называется прибор для выпечки хлеба?', answers: ['духовка', 'печь'] },
  { id: 'home-23', categoryId: 'home', text: 'Чем режут овощи на кухне?', answers: ['нож', 'ножом'] },
  { id: 'home-24', categoryId: 'home', text: 'Как называется ёмкость для мусора на кухне?', answers: ['ведро', 'мусорное ведро', 'урна'] },
  { id: 'home-25', categoryId: 'home', text: 'Где сушат бельё после стирки?', answers: ['сушилка', 'балкон', 'веревка'] },
  { id: 'home-26', categoryId: 'home', text: 'Как называется мягкая мебель для двоих?', answers: ['диван', 'софа'] },
  { id: 'home-27', categoryId: 'home', text: 'Чем накрывают стол перед едой?', answers: ['скатерть', 'салфетки'] },
  { id: 'home-28', categoryId: 'home', text: 'В чём обычно варят яйца?', answers: ['кастрюля', 'яйцеварка'] },
  { id: 'home-29', categoryId: 'home', text: 'Где хранят обувь при входе в квартиру?', answers: ['прихожая', 'обувница'] },
  { id: 'home-30', categoryId: 'home', text: 'Как называется шторка в ванной?', answers: ['шторка', 'занавеска'] },
  { id: 'home-31', categoryId: 'home', text: 'Чем закрывают окно от солнца?', answers: ['шторы', 'жалюзи'] },
  { id: 'home-32', categoryId: 'home', text: 'Как называется прибор для приготовления кофе?', answers: ['кофеварка', 'кофемашина', 'turka'] },
  { id: 'home-33', categoryId: 'home', text: 'Где готовят суп на плите?', answers: ['кастрюля', 'кастрюле'] },
  { id: 'home-34', categoryId: 'home', text: 'Как называется коврик у входной двери?', answers: ['коврик', 'коврик для ног'] },
  { id: 'home-35', categoryId: 'home', text: 'Чем вытирают посуду после мытья?', answers: ['полотенце', 'салфетка'] },
  { id: 'home-36', categoryId: 'home', text: 'Как называется ящик для хранения вещей под кроватью?', answers: ['короб', 'ящик'] },
  { id: 'home-37', categoryId: 'home', text: 'Где вешают верхнюю одежду зимой?', answers: ['шкаф', 'вешалка', 'прихожая'] },
  { id: 'home-38', categoryId: 'home', text: 'Как называется прибор для увлажнения воздуха?', answers: ['увлажнитель', 'увлажнитель воздуха'] },
  { id: 'home-39', categoryId: 'home', text: 'Чем застилают кровать сверху?', answers: ['простыня', 'покрывало', 'одеяло'] },
  { id: 'home-40', categoryId: 'home', text: 'Как называется розетка для электроприборов?', answers: ['розетка', 'rozetka'] },
];
