/** Дополнительные вопросы (6–20) для каждой категории. */
export const QUIZ_QUESTIONS_EXTRA = [
  // Любовь
  { id: 'love-6', categoryId: 'love', text: 'Как называется годовщина 25 лет брака?', answers: ['серебряная свадьба', 'серебряная'] },
  { id: 'love-7', categoryId: 'love', text: 'Как называется традиционная поездка сразу после свадьбы?', answers: ['медовый месяц'] },
  { id: 'love-8', categoryId: 'love', text: 'Какой цвет платья невесты принят в западной традиции?', answers: ['белый', 'белое', 'белого'] },
  { id: 'love-9', categoryId: 'love', text: 'Как называется римский бог любви?', answers: ['купидон', 'амур', 'эрос'] },
  { id: 'love-10', categoryId: 'love', text: 'Что традиционно дарят на помолвку в виде камня?', answers: ['кольцо', 'бриллиант', 'алмаз', 'помолвочное кольцо'] },
  { id: 'love-11', categoryId: 'love', text: 'Под чем традиционно целуются на Рождество?', answers: ['омела', 'омелой', 'под омелой'] },
  { id: 'love-12', categoryId: 'love', text: 'Как называется первый танец молодожёнов?', answers: ['первый танец', 'свадебный танец', 'вальс'] },
  { id: 'love-13', categoryId: 'love', text: 'Какой цветок часто считают символом любви?', answers: ['роза', 'розы', 'красная роза'] },
  { id: 'love-14', categoryId: 'love', text: 'Как по-английски «любовь»?', answers: ['love'] },
  { id: 'love-15', categoryId: 'love', text: 'Как называется годовщина 1 год брака?', answers: ['ситцевая свадьба', 'ситцевая', 'хлопковая'] },
  { id: 'love-16', categoryId: 'love', text: 'Что символизирует разбитое сердце на открытке?', answers: ['расставание', 'грусть', 'печаль'] },
  { id: 'love-17', categoryId: 'love', text: 'Как называется обещание верности при свадьбе?', answers: ['клятва', 'обеты', 'свадебные обеты'] },
  { id: 'love-18', categoryId: 'love', text: 'Какой жест чаще всего означает романтический интерес?', answers: ['поцелуй', 'поцелуи', 'целовать'] },
  { id: 'love-19', categoryId: 'love', text: 'Как называется пара без официального брака, живущая вместе?', answers: ['сожители', 'гражданский брак', 'партнеры'] },
  { id: 'love-20', categoryId: 'love', text: 'Какой праздник отмечают 14 февраля?', answers: ['день святого валентина', 'валентин', 'день влюбленных', 'valentine', 'valentines day'] },

  // Кино
  { id: 'cinema-6', categoryId: 'cinema', text: 'Как зовут главного героя «Матрицы»?', answers: ['нео', 'neo', 'андерсон'] },
  { id: 'cinema-7', categoryId: 'cinema', text: 'Как зовут льва в мультфильме «Король Лев»?', answers: ['симба', 'simba'] },
  { id: 'cinema-8', categoryId: 'cinema', text: 'Кто сыграл Железного человека в киновселенной Marvel?', answers: ['дауни', 'дауни младший', 'роберт дауни', 'robert downey'] },
  { id: 'cinema-9', categoryId: 'cinema', text: 'Кто режиссёр фильма «Аватар» (2009)?', answers: ['кэмерон', 'джеймс кэмерон', 'cameron'] },
  { id: 'cinema-10', categoryId: 'cinema', text: 'В каком фильме герои едят в парке и видят динозавров?', answers: ['парк юрского периода', 'jurassic park'] },
  { id: 'cinema-11', categoryId: 'cinema', text: 'Как зовут рыбку-клоуна в «В поисках Немо»?', answers: ['немо', 'nemo', 'марлин'] },
  { id: 'cinema-12', categoryId: 'cinema', text: 'Как зовут зелёного огра в одноимённом мультфильме?', answers: ['шрек', 'shrek'] },
  { id: 'cinema-13', categoryId: 'cinema', text: 'Какой шпион носит кодовый номер 007?', answers: ['джеймс бонд', 'бонд', 'james bond'] },
  { id: 'cinema-14', categoryId: 'cinema', text: 'Как зовут ковбоя в «Истории игрушек»?', answers: ['вуди', 'woody'] },
  { id: 'cinema-15', categoryId: 'cinema', text: 'Как зовут снежную королеву в «Холодном сердце»?', answers: ['эльза', 'elsa'] },
  { id: 'cinema-16', categoryId: 'cinema', text: 'Кто несёт кольцо в «Властелине колец»?', answers: ['фродо', 'frodo', 'бэггинс'] },
  { id: 'cinema-17', categoryId: 'cinema', text: 'Какой фильм 1994 года про коробку шоколадных конфет и скамейку в Саванне?', answers: ['форрест гамп', 'forrest gump', 'forest gump'] },
  { id: 'cinema-18', categoryId: 'cinema', text: 'В каком фильме герой бежит с коробкой шоколадных конфет?', answers: ['форрест гамп', 'forrest gump'] },
  { id: 'cinema-19', categoryId: 'cinema', text: 'Как зовут злодея с перчаткой в «Мстителях»?', answers: ['танос', 'thanos'] },
  { id: 'cinema-20', categoryId: 'cinema', text: 'Как называется студия мультфильмов создавшая «Вверх» и «Головоломку»?', answers: ['pixar', 'пиксар'] },

  // Путешествия
  { id: 'travel-6', categoryId: 'travel', text: 'Столица Италии?', answers: ['рим', 'roma'] },
  { id: 'travel-7', categoryId: 'travel', text: 'В какой стране находится Великая Китайская стена?', answers: ['китай', 'китае', 'кнр'] },
  { id: 'travel-8', categoryId: 'travel', text: 'Столица Японии?', answers: ['токио', 'tokyo'] },
  { id: 'travel-9', categoryId: 'travel', text: 'Статуя Свободы находится в каком городе США?', answers: ['нью-йорк', 'нью йорк', 'new york'] },
  { id: 'travel-10', categoryId: 'travel', text: 'Столица Испании?', answers: ['мадрид', 'madrid'] },
  { id: 'travel-11', categoryId: 'travel', text: 'Столица Германии?', answers: ['берлин', 'berlin'] },
  { id: 'travel-12', categoryId: 'travel', text: 'Колизей находится в каком городе?', answers: ['рим', 'roma'] },
  { id: 'travel-13', categoryId: 'travel', text: 'Биг-Бен находится в каком городе?', answers: ['лондон', 'london'] },
  { id: 'travel-14', categoryId: 'travel', text: 'В какой стране город Венеция на воде?', answers: ['италия', 'италии'] },
  { id: 'travel-15', categoryId: 'travel', text: 'Самая высокая гора мира?', answers: ['эверест', 'джомолунгма', 'everest'] },
  { id: 'travel-16', categoryId: 'travel', text: 'Пирамиды Гизы находятся в какой стране?', answers: ['египет', 'египте'] },
  { id: 'travel-17', categoryId: 'travel', text: 'Столица Бразилии?', answers: ['бразилиа', 'brasilia'] },
  { id: 'travel-18', categoryId: 'travel', text: 'Какое явление видят в полярных широтах (северное)?', answers: ['северное сияние', 'полярное сияние', 'аврора'] },
  { id: 'travel-19', categoryId: 'travel', text: 'Река Нил протекает в основном по какому континенту?', answers: ['африка', 'африке'] },
  { id: 'travel-20', categoryId: 'travel', text: 'Столица Канады?', answers: ['оттава', 'ottawa'] },

  // Общее
  { id: 'general-6', categoryId: 'general', text: 'Химическая формула воды?', answers: ['h2o', 'вода'] },
  { id: 'general-7', categoryId: 'general', text: 'Сколько дней в обычной неделе?', answers: ['7', 'семь'] },
  { id: 'general-8', categoryId: 'general', text: 'Какой океан самый большой?', answers: ['тихий', 'тихий океан', 'pacific'] },
  { id: 'general-9', categoryId: 'general', text: 'Сколько сезонов в году (в умеренном климате)?', answers: ['4', 'четыре'] },
  { id: 'general-10', categoryId: 'general', text: 'При какой температуре вода замерзает (°C)?', answers: ['0', 'ноль', '0 градусов'] },
  { id: 'general-11', categoryId: 'general', text: 'Сколько цветов в радуге (классическая модель)?', answers: ['7', 'семь'] },
  { id: 'general-12', categoryId: 'general', text: 'Какая страна по площади самая большая?', answers: ['россия', 'рф', 'russia'] },
  { id: 'general-13', categoryId: 'general', text: 'Сколько сторон у квадрата?', answers: ['4', 'четыре'] },
  { id: 'general-14', categoryId: 'general', text: 'Какой металл обозначается Fe?', answers: ['железо'] },
  { id: 'general-15', categoryId: 'general', text: 'Сколько часов в сутках?', answers: ['24', 'двадцать четыре'] },
  { id: 'general-16', categoryId: 'general', text: 'Как называется естественный спутник Земли?', answers: ['луна', 'луну'] },
  { id: 'general-17', categoryId: 'general', text: 'Сколько месяцев в году?', answers: ['12', 'двенадцать'] },
  { id: 'general-18', categoryId: 'general', text: 'Какой газ чаще всего в атмосфере Земли?', answers: ['азот', 'n2'] },
  { id: 'general-19', categoryId: 'general', text: 'Сколько градусов в прямом угле?', answers: ['90', 'девяносто'] },
  { id: 'general-20', categoryId: 'general', text: 'В каком году человек впервые высадился на Луну?', answers: ['1969'] },

  // Музыка
  { id: 'music-6', categoryId: 'music', text: 'Группа The Beatles из какой страны?', answers: ['великобритания', 'англия', 'uk', 'британия'] },
  { id: 'music-7', categoryId: 'music', text: 'Как называется ударный инструмент с мембраной?', answers: ['барабан', 'барабаны', 'ударные'] },
  { id: 'music-8', categoryId: 'music', text: 'Как называется высокий женский певческий голос?', answers: ['сопрано', 'soprano'] },
  { id: 'music-9', categoryId: 'music', text: 'Кого называют королём рок-н-ролла?', answers: ['элвис пресли', 'пресли', 'элвис', 'elvis'] },
  { id: 'music-10', categoryId: 'music', text: 'Первая нота сольфеджио?', answers: ['до', 'c'] },
  { id: 'music-11', categoryId: 'music', text: 'Как называется человек, управляющий оркестром?', answers: ['дирижер', 'дирижёр'] },
  { id: 'music-12', categoryId: 'music', text: 'Сколько линий на стандартном нотном стане?', answers: ['5', 'пять'] },
  { id: 'music-13', categoryId: 'music', text: 'Какой духовой инструмент изогнут и золотист?', answers: ['саксофон', 'саксофона'] },
  { id: 'music-14', categoryId: 'music', text: 'Как называется групповое пение?', answers: ['хор', 'хоровое пение'] },
  { id: 'music-15', categoryId: 'music', text: 'Какой композитор написал «Лунную сонату»?', answers: ['бетховен', 'бетховен людвиг', 'beethoven'] },
  { id: 'music-16', categoryId: 'music', text: 'Как называется струнный инструмент с смычком?', answers: ['скрипка', 'виолончель', 'альт'] },
  { id: 'music-17', categoryId: 'music', text: 'Сколько клавиш у стандартного пианино (приблизительно)?', answers: ['88', 'восемьдесят восемь'] },
  { id: 'music-18', categoryId: 'music', text: 'Как называется запись на виниловом диске?', answers: ['пластинка', 'винил', 'грампластинка'] },
  { id: 'music-19', categoryId: 'music', text: 'Какой инструмент играет на губной мембране?', answers: ['тромбон', 'труба', 'валторна', 'флюгельгорн'] },
  { id: 'music-20', categoryId: 'music', text: 'Как называется ритмический рисунок в музыке?', answers: ['ритм', 'бит', 'размер'] },

  // Еда и кухня
  { id: 'food-6', categoryId: 'food', text: 'Главный овощ в классическом борще?', answers: ['свекла', 'свёкла'] },
  { id: 'food-7', categoryId: 'food', text: 'Круассан ассоциируют с какой страной?', answers: ['франция', 'франции'] },
  { id: 'food-8', categoryId: 'food', text: 'Васаби — традиционная приправа какой кухни?', answers: ['япония', 'японии', 'японской'] },
  { id: 'food-9', categoryId: 'food', text: 'Оливковое масло чаще делают из какого плода?', answers: ['оливки', 'олива'] },
  { id: 'food-10', categoryId: 'food', text: 'Гамбургер как символ быстрой еды из какой страны?', answers: ['сша', 'америка', 'usa'] },
  { id: 'food-11', categoryId: 'food', text: 'Как называется итальянская паста в виде трубочек?', answers: ['макароны', 'паста', 'пенне', 'ригатони'] },
  { id: 'food-12', categoryId: 'food', text: 'Какой напиток заваривают из листьев куста?', answers: ['чай'] },
  { id: 'food-13', categoryId: 'food', text: 'Мёд производят насекомые — какие?', answers: ['пчелы', 'пчела'] },
  { id: 'food-14', categoryId: 'food', text: 'Какой овощ — основа классических щей?', answers: ['капуста'] },
  { id: 'food-15', categoryId: 'food', text: 'Шоколад делают из каких бобов?', answers: ['какао', 'какао-бобы'] },
  { id: 'food-16', categoryId: 'food', text: 'Как называется молочный продукт из ферментации молока?', answers: ['йогурт', 'кефир', 'творог'] },
  { id: 'food-17', categoryId: 'food', text: 'Кленовый сироп ассоциируют с какой страной?', answers: ['канада', 'канаде'] },
  { id: 'food-18', categoryId: 'food', text: 'Что добавляют в тесто, чтобы оно поднялось?', answers: ['дрожжи', 'разрыхлитель', 'сода'] },
  { id: 'food-19', categoryId: 'food', text: 'Какой фрукт — основа лимонада?', answers: ['лимон', 'лимоны'] },
  { id: 'food-20', categoryId: 'food', text: 'Как называется тонкая японская лапша в супе?', answers: ['рамен', 'удон', 'соба'] },

  // Природа и животные
  { id: 'nature-6', categoryId: 'nature', text: 'Кого называют «царём зверей»?', answers: ['лев', 'льва', 'lion'] },
  { id: 'nature-7', categoryId: 'nature', text: 'Какое животное живёт на полюсе и ест рыбу (белый)?', answers: ['белый медведь', 'полярный медведь'] },
  { id: 'nature-8', categoryId: 'nature', text: 'У какого животного самая длинная шея?', answers: ['жираф', 'жирафа'] },
  { id: 'nature-9', categoryId: 'nature', text: 'Какая птица охотится ночью и умеет поворачивать голову?', answers: ['сова', 'совы'] },
  { id: 'nature-10', categoryId: 'nature', text: 'Дельфин — это рыба или млекопитающее?', answers: ['млекопитающее', 'млекопитающие'] },
  { id: 'nature-11', categoryId: 'nature', text: 'Где живут пингвины в дикой природе (континент)?', answers: ['антарктида', 'антарктиде'] },
  { id: 'nature-12', categoryId: 'nature', text: 'Какое насекомое производит шелк?', answers: ['шелкопряд', 'гусеница', 'паук', 'паукообразные'] },
  { id: 'nature-13', categoryId: 'nature', text: 'Какой цветок поворачивается к солнцу?', answers: ['подсолнух', 'подсолнечник'] },
  { id: 'nature-14', categoryId: 'nature', text: 'Летучая мышь — птица или млекопитающее?', answers: ['млекопитающее', 'млекопитающие'] },
  { id: 'nature-15', categoryId: 'nature', text: 'Что ест панда в основном?', answers: ['бамбук', 'бамбука'] },
  { id: 'nature-16', categoryId: 'nature', text: 'Сколько ног у насекомого?', answers: ['6', 'шесть'] },
  { id: 'nature-17', categoryId: 'nature', text: 'Какой хищник полосатый и похож на кошку?', answers: ['тигр', 'полосатый тигр'] },
  { id: 'nature-18', categoryId: 'nature', text: 'Как называется место обитания кораллов в море?', answers: ['риф', 'коралловый риф'] },
  { id: 'nature-19', categoryId: 'nature', text: 'Какое дерево даёт кокосы?', answers: ['пальма', 'кокосовая пальма'] },
  { id: 'nature-20', categoryId: 'nature', text: 'Какой газ поглощают деревья при фотосинтезе?', answers: ['углекислый газ', 'co2', 'диоксид углерода'] },

  // Праздники и традиции
  { id: 'holidays-6', categoryId: 'holidays', text: 'Когда отмечают Рождество (западная традиция)?', answers: ['25 декабря', 'двадцать пятое декабря'] },
  { id: 'holidays-7', categoryId: 'holidays', text: 'Какой христианский праздник весной отмечают яйцами?', answers: ['пасха', 'пасху'] },
  { id: 'holidays-8', categoryId: 'holidays', text: 'Во многих странах День труда (1 мая) отмечают в каком месяце?', answers: ['май', 'мае', 'may'] },
  { id: 'holidays-9', categoryId: 'holidays', text: 'Какое блюдо традиционно едят на Масленицу / Pancake Day?', answers: ['блины', 'блин', 'блинами', 'pancakes', 'pancake'] },
  { id: 'holidays-10', categoryId: 'holidays', text: 'Международный день защиты детей — какое число июня?', answers: ['1', '1 июня', 'первое июня', 'june 1', '1 june'] },
  { id: 'holidays-11', categoryId: 'holidays', text: 'Какой цвет ассоциируют с Днём святого Патрика?', answers: ['зеленый', 'зелёный', 'зеленого'] },
  { id: 'holidays-12', categoryId: 'holidays', text: 'Кто традиционно приносит подарки на Рождество в западной культуре?', answers: ['санта клаус', 'santa claus', 'father christmas', 'дед мороз', 'santa'] },
  { id: 'holidays-13', categoryId: 'holidays', text: 'Как называется карнавал в Рио-де-Жанейро?', answers: ['карнавал', 'рио карнавал', 'бразильский карнавал'] },
  { id: 'holidays-14', categoryId: 'holidays', text: 'Салют чаще всего запускают в какой праздник?', answers: ['новый год', 'new year', 'independence day', 'день независимости'] },
  { id: 'holidays-15', categoryId: 'holidays', text: 'Хэллоуин — праздник какой ночи?', answers: ['31 октября', 'канун всех святых'] },
  { id: 'holidays-16', categoryId: 'holidays', text: 'День благодарения в США обычно отмечают в каком месяце?', answers: ['ноябрь', 'ноябре', 'november', 'thanksgiving'] },
  { id: 'holidays-17', categoryId: 'holidays', text: 'Марди Гра празднуют перед началом какого христианского периода?', answers: ['великий пост', 'пост', 'lent', 'great lent'] },
  { id: 'holidays-18', categoryId: 'holidays', text: 'Свадьба — это личный или государственный праздник?', answers: ['личный', 'семейный', 'не государственный'] },
  { id: 'holidays-19', categoryId: 'holidays', text: 'Какой символ часто вешают на дверь на Пасху (христиане)?', answers: ['пасхальное яйцо', 'яйцо', 'венок'] },
  { id: 'holidays-20', categoryId: 'holidays', text: 'День смеха (April Fools\' Day) — какая дата?', answers: ['1 апреля', 'первое апреля', 'april 1', '1 april'] },

  // Языки любви
  { id: 'loveLanguages-6', categoryId: 'loveLanguages', text: 'Кто автор книги «Пять языков любви»?', answers: ['чепмен', 'гэри чепмен', 'gary chapman'] },
  { id: 'loveLanguages-7', categoryId: 'loveLanguages', text: 'Язык «служение» на английском?', answers: ['acts of service', 'служение', 'дела'] },
  { id: 'loveLanguages-8', categoryId: 'loveLanguages', text: 'Что НЕ является языком любви в модели Чепмена: деньги, подарки, время?', answers: ['деньги', 'money'] },
  { id: 'loveLanguages-9', categoryId: 'loveLanguages', text: 'Объятия относятся к какому языку?', answers: ['physical touch', 'прикосновения', 'физическое прикосновение'] },
  { id: 'loveLanguages-10', categoryId: 'loveLanguages', text: 'Совместный ужин без телефона — пример какого языка?', answers: ['quality time', 'качественное время', 'время вместе'] },
  { id: 'loveLanguages-11', categoryId: 'loveLanguages', text: 'Комплимент — пример какого языка?', answers: ['words of affirmation', 'слова поддержки', 'слова похвалы'] },
  { id: 'loveLanguages-12', categoryId: 'loveLanguages', text: 'Помочь с уборкой — пример какого языка?', answers: ['acts of service', 'дела', 'служение'] },
  { id: 'loveLanguages-13', categoryId: 'loveLanguages', text: 'Сюрприз-подарок — пример какого языка?', answers: ['receiving gifts', 'подарки'] },
  { id: 'loveLanguages-14', categoryId: 'loveLanguages', text: 'Как переводится quality time буквально?', answers: ['качественное время', 'время качества'] },
  { id: 'loveLanguages-15', categoryId: 'loveLanguages', text: 'Модель языков любви помогает парам улучшить что?', answers: ['общение', 'отношения', 'понимание'] },
  { id: 'loveLanguages-16', categoryId: 'loveLanguages', text: 'У каждого человека обычно есть основной и … язык?', answers: ['вторичный', 'второй', 'дополнительный'] },
  { id: 'loveLanguages-17', categoryId: 'loveLanguages', text: 'Письмо с признанием — words of …?', answers: ['affirmation', 'аффирмация', 'поддержки'] },
  { id: 'loveLanguages-18', categoryId: 'loveLanguages', text: 'Погладить по голове — какой язык?', answers: ['physical touch', 'прикосновения'] },
  { id: 'loveLanguages-19', categoryId: 'loveLanguages', text: 'Сколько языков нужно знать, чтобы понять партнёра в модели?', answers: ['5', 'пять', 'его язык'] },
  { id: 'loveLanguages-20', categoryId: 'loveLanguages', text: '«Бак любви» — метафора из книг о …?', answers: ['языках любви', 'любви', 'отношениях'] },

  // Технологии и интернет
  { id: 'tech-6', categoryId: 'tech', text: 'Соцсеть Facebook теперь называется …?', answers: ['meta', 'мета'] },
  { id: 'tech-7', categoryId: 'tech', text: 'Символ @ в email называют …?', answers: ['собака', 'эт', 'at'] },
  { id: 'tech-8', categoryId: 'tech', text: 'Операционная система для смартфонов от Google?', answers: ['android', 'андроид'] },
  { id: 'tech-9', categoryId: 'tech', text: 'Что означает USB?', answers: ['universal serial bus', 'юсб', 'универсальная последовательная шина'] },
  { id: 'tech-10', categoryId: 'tech', text: 'Как называется беспроводной интернет дома?', answers: ['wi-fi', 'wifi', 'вайфай'] },
  { id: 'tech-11', categoryId: 'tech', text: 'Мессенджер с синим самолётиком в логотипе?', answers: ['telegram', 'телеграм', 'телеграмм'] },
  { id: 'tech-12', categoryId: 'tech', text: 'Хранение файлов в облаке — это …?', answers: ['облако', 'cloud', 'облачное хранилище'] },
  { id: 'tech-13', categoryId: 'tech', text: 'Символ # в соцсетях для тем?', answers: ['хештег', 'хэштег', 'hashtag'] },
  { id: 'tech-14', categoryId: 'tech', text: 'Как называется портативный компьютер?', answers: ['ноутбук', 'лэптоп', 'laptop'] },
  { id: 'tech-15', categoryId: 'tech', text: 'Компания Tesla известна чем?', answers: ['электромобили', 'машины', 'авто'] },
  { id: 'tech-16', categoryId: 'tech', text: 'Минимальная единица изображения на экране?', answers: ['пиксель', 'pixel'] },
  { id: 'tech-17', categoryId: 'tech', text: 'Оперативная память компьютера — аббревиатура?', answers: ['ram', 'озу', 'оперативка'] },
  { id: 'tech-18', categoryId: 'tech', text: 'Защищённое соединение в интернете — аббревиатура?', answers: ['vpn', 'впн'] },
  { id: 'tech-19', categoryId: 'tech', text: 'Поисковая система от Яндекса?', answers: ['яндекс', 'yandex'] },
  { id: 'tech-20', categoryId: 'tech', text: 'Смайлики в переписке называют …?', answers: ['эмодзи', 'emoji', 'смайлы'] },

  // Спорт
  { id: 'sport-6', categoryId: 'sport', text: 'Олимпийские игры проводят раз в сколько лет?', answers: ['4', 'четыре'] },
  { id: 'sport-7', categoryId: 'sport', text: 'Сколько игроков в баскетбольной командии на площадке?', answers: ['5', 'пять'] },
  { id: 'sport-8', categoryId: 'sport', text: 'Марафон — бег на дистанцию около скольких км?', answers: ['42', '42.195', 'сорок два'] },
  { id: 'sport-9', categoryId: 'sport', text: 'Золото, серебро и … — медали Олимпиады?', answers: ['бронза', 'бронзовая'] },
  { id: 'sport-10', categoryId: 'sport', text: 'В каком спорте есть «шах и мат»?', answers: ['шахматы', 'шахматах'] },
  { id: 'sport-11', categoryId: 'sport', text: 'Фигурное катание — зимний или летний вид?', answers: ['зимний', 'зима', 'зимний вид'] },
  { id: 'sport-12', categoryId: 'sport', text: 'В каком спорте бьют по мячу ракеткой через сетку?', answers: ['теннис', 'бадминтон', 'сквош'] },
  { id: 'sport-13', categoryId: 'sport', text: 'Tour de France — соревнование по …?', answers: ['велосипед', 'велоспорт', 'велогонка'] },
  { id: 'sport-14', categoryId: 'sport', text: 'Сколько периодов в хоккейном матче (основное время)?', answers: ['3', 'три'] },
  { id: 'sport-15', categoryId: 'sport', text: 'В каком спорте используют перчатки и ринг?', answers: ['бокс', 'боксе', 'боксер'] },
  { id: 'sport-16', categoryId: 'sport', text: 'Плавание — в какой среде?', answers: ['вода', 'воде', 'бассейн'] },
  { id: 'sport-17', categoryId: 'sport', text: 'Стрельба из лука — олимпийский вид …?', answers: ['спорт', 'стрельба'] },
  { id: 'sport-18', categoryId: 'sport', text: 'Судья показывает жёлтую карточку в …?', answers: ['футбол', 'футболе', 'соккер'] },
  { id: 'sport-19', categoryId: 'sport', text: 'Лыжи — зимний вид спорта на …?', answers: ['снег', 'снегу', 'склон'] },
  { id: 'sport-20', categoryId: 'sport', text: 'Сколько очков за гол в футболе (стандарт)?', answers: ['1', 'один'] },

  // Искусство и литература
  { id: 'art-6', categoryId: 'art', text: 'Кто написал «Преступление и наказание»?', answers: ['достоевский', 'федор достоевский', 'достоевский федор'] },
  { id: 'art-7', categoryId: 'art', text: 'Кто написал «Евгения Онегина»?', answers: ['пушкин', 'александр пушкин', 'пушкин александр'] },
  { id: 'art-8', categoryId: 'art', text: 'Картина «Богатыри» — кто художник?', answers: ['васнецов', 'виктор васнецов'] },
  { id: 'art-9', categoryId: 'art', text: 'Музей Лувр находится в каком городе?', answers: ['париж', 'paris'] },
  { id: 'art-10', categoryId: 'art', text: 'Кто написал «Ромео и Джульетту»?', answers: ['шекспир', 'уильям шекспир', 'shakespeare'] },
  { id: 'art-11', categoryId: 'art', text: 'Балет «Щелкунчик» написал …?', answers: ['чайковский', 'п. и. чайковский'] },
  { id: 'art-12', categoryId: 'art', text: 'Кубизм ассоциируют с каким художником?', answers: ['пикассо', 'picasso', 'пабло пикассо'] },
  { id: 'art-13', categoryId: 'art', text: '«Мёртвые души» — автор?', answers: ['гоголь', 'николай гоголь'] },
  { id: 'art-14', categoryId: 'art', text: 'Стихи пишет …?', answers: ['поэт', 'поэты'] },
  { id: 'art-15', categoryId: 'art', text: 'Скульптура «Мыслитель» — автор?', answers: ['роден', 'одюард роден', 'roden'] },
  { id: 'art-16', categoryId: 'art', text: '«Мастер и Маргарита» — автор?', answers: ['булгаков', 'михаил булгаков'] },
  { id: 'art-17', categoryId: 'art', text: 'Театр «Глобус» связан с каким драматургом?', answers: ['шекспир', 'шекспира'] },
  { id: 'art-18', categoryId: 'art', text: 'Акварель — техника с …?', answers: ['водой', 'водяными красками'] },
  { id: 'art-19', categoryId: 'art', text: '«Крик» написал норвежский художник …?', answers: ['мунк', 'эдвард мунк', 'munch'] },
  { id: 'art-20', categoryId: 'art', text: 'Репин написал «Бурлаки на …»?', answers: ['волге', 'волга'] },

  // Дом и быт
  { id: 'home-6', categoryId: 'home', text: 'Какой прибор убирает пыль с ковра?', answers: ['пылесос', 'пылесосом'] },
  { id: 'home-7', categoryId: 'home', text: 'Как называется мебель для сидения в гостиной?', answers: ['диван', 'кресло', 'софа'] },
  { id: 'home-8', categoryId: 'home', text: 'Чем разогревают еду быстро в кухне?', answers: ['микроволновка', 'микроволновой печи', 'свч'] },
  { id: 'home-9', categoryId: 'home', text: 'Чем открывают дверь?', answers: ['ключ', 'ключом'] },
  { id: 'home-10', categoryId: 'home', text: 'Какой прибор гладит одежду?', answers: ['утюг', 'утюгом'] },
  { id: 'home-11', categoryId: 'home', text: 'Где в ванной моются под струёй воды?', answers: ['душ', 'душе', 'душевой'] },
  { id: 'home-12', categoryId: 'home', text: 'Чайник предназначен для …?', answers: ['кипячения воды', 'чая', 'воды'] },
  { id: 'home-13', categoryId: 'home', text: 'Полотенце обычно висит в …?', answers: ['ванной', 'ванна', 'санузел'] },
  { id: 'home-14', categoryId: 'home', text: 'Зеркало обычно висит в …?', answers: ['ванной', 'прихожей', 'спальне', 'ванна'] },
  { id: 'home-15', categoryId: 'home', text: 'Метла используется для …?', answers: ['подметания', 'уборки', 'пола'] },
  { id: 'home-16', categoryId: 'home', text: 'Тарелка — посуда для …?', answers: ['еды', 'пищи', 'блюд'] },
  { id: 'home-17', categoryId: 'home', text: 'Лампочка даёт …?', answers: ['свет', 'освещение'] },
  { id: 'home-18', categoryId: 'home', text: 'Мусор выбрасывают в …?', answers: ['ведро', 'урну', 'контейнер', 'мусорку'] },
  { id: 'home-19', categoryId: 'home', text: 'Посудомоечная машина моет …?', answers: ['посуду', 'тарелки'] },
  { id: 'home-20', categoryId: 'home', text: 'Одеяло кладут на …?', answers: ['кровать', 'кровати', 'матрас'] },
];
